### ISSUE TITLE
[py2py3] check the use of str in src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10378] opened 2021-03-24 18:45 UTC
**Impact of the bug**

Should involve `src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py` only

**Describe the bug**

We have not observed any bug at the moment, but this is to create some problems.

As described in #10363,

- `src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py`: 
  - format input of `classad.quote(input)`, which should accept a `str` input in py3 as well [as they claim](https://htcondor.readthedocs.io/en/latest/apis/python-bindings/api/classad.html#classad.quote), but better be safe than sorry and check this.
  - format a ton of keys of a dict that is appended to `JobParameters`, such as `ad['My.OriginalCpus'] = str(origCores)`. If this is used only by us in `SimpleCondorPlugin.createSubmitRequest` and not by WMCore clients, we may be in a good spot.

We did not change  anything, driven by the ["native string"](https://portingguide.readthedocs.io/en/latest/strings.html#the-native-string) hope that trying to be consistent and use `str` in both py2 and py3 will not cause problems in`SimpleCondorPlugin.py`, but we need to check that this is the case

**Expected behavior**
`SimpleCondorPlugin` should work properly in both py2 and py3

**Comment by amaltaro** [comment] 2021-08-17 10:37
This is working fine with Py3 WMAgent `>= 1.5.2.pre2`.
To be confirmed from a T0 replay in the next days.

**Comment by amaltaro** [comment] 2021-08-30 07:56
The T0 team is migrating the T0 agent to python3, and since this has been fully validated in Python3, I'm closing this issue (we can always reopen it if a new issue is found in this module).

**Closed by amaltaro** 2021-08-30 07:56 UTC
Labels: Medium Priority, Python3, Low effort, py3 potential bug, Testing
