### ISSUE TITLE
Verify the Campaign APIs and define a schema

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9139] opened 2019-04-09 09:42 UTC
We need to make sure Ops can properly create new Campaign configurations, edit and delete using the REST APIs. Documentation also needs to be created.

On top of it, we need to revisit the Campaign structure and define (and enforce) a schema.

Here is the schema discussed along this thread:
```
{
 "CampaignName": "blah2019",
 "PrimaryAAA": boolean, # default false
 "SecondaryAAA": boolean, # default false
 "SiteWhiteList": ["T1_*", "T2_*"],
 "SiteBlackList": [...],
 "SecondaryLocation": ["list with sites to hold a whole copy of the dataset"],
 "Secondaries": {"datasetA": ["list of sites for SiteWhitelist"], "datasetB": ["list of sites for SiteWhitelist"]},
 "MaxCopies": integer
}
```

where:
* `CampaignName`: string corresponding to the campaign name; which is the top level keys of the campaign.json file.
* `PrimaryAAA`: boolean to flag whether to use AAA for the primary dataset; mapped from the `primary_AAA` top level key.
* `SecondaryAAA`: boolean to flag whether to use AAA for the secondary dataset; mapped from the `secondary_AAA` key, which can be *either* at top level or under the `secondaries` dictionary. If it appears multiple times, we make an OR of the values.
* `SiteWhiteList`: list of sites where the workflow gets assigned to and where the primary and secondary CLASSIC MIX dataset is placed (likely in chunks of data); mapped from the `SiteWhitelist` key which can be AFAIK in multiple places, like: top level dict, under the `parameters` key and under the `secondaries` dictionary. If it appears multiple times, we make an intersection of the values.
* `SiteBlackList`: list of sites where the workflow does NOT get assigned to and where the primary and secondary CLASSIC MIX dataset is NOT placed; mapped from the `SiteBlacklist` key which can be AFAIK in multiple places, like: top level dict, under the `parameters` key and under the `secondaries` dictionary. If it appears multiple times, we make an *union* of the values.
* `SecondaryLocation`: list of sites where the secondary PREMIX dataset has to be placed as a whole (not necessarily also assigned to those). mapped from the `SecondaryLocation` key, which can be *either* at top level or under the `secondaries` dictionary. If it appears multiple times, we make an intersection of the values.
* `Secondaries`: dictionary with a map of allowed secondary datasets and where they are supposed to be placed; mapped from the key top level `secondaries`.
  * the value of each dataset key comes from their correspondent `SiteWhitelist` key/value
* `MaxCopies`: integer representing the number of copies for each dataset/block that has to be transferred; mapped from the top level `maxcopies` key. Default to 1

**Comment by vkuznet** [comment] 2019-04-09 15:36
Alan,
I already checked this and found that
WMCore/Services/ReqMgrAux/ReqMgrAux.py
does not supply configuration. In fact, I don't really see how it fetches them
in a first place since I can't figure out where local cache is populated.

I also tested this in my VM and I only got exceptions since local cache does not
exists.

To be precise, you can look at
https://github.com/dmwm/WMCore/pull/8379/files#diff-f32be4d04ca179a17b9ba0d263be2019R130
and see for yourself.

The ReqMgrAux should get campaign from somewhere and in setup I have its cache
is always empty.

Feel free to have a look since I'll be traveling tomorrow anyway.

**Comment by vkuznet** [comment] 2019-04-11 20:18
Alan, here is more info for you to digest. As far as I can tell ReqMgrAux class was designed to store results into local cache from reqmgr2 data-service. As such the existing APIs should look-up data from
- URL/reqmgr2/data/campaignconfig
- URL/reqmgr2/data/cmsswversions
- URL/reqmgr2/data/wmagentconfig

These APIs provided by ReqMgr (ReqMgr/Service/Auxiliary.py) classes, see corresponding classes over there, e.g. CampaignConfig. The latter refers to reqmgr_aux_db 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Auxiliary.py#L152
which according to ReqMgr configuration (see https://github.com/dmwm/deployment/blob/master/reqmgr2/config.py#L64) refers to `reqmgr_auxilary` couchdb (https://cmsweb.cern.ch/couchdb/_utils/database.html?reqmgr_auxiliary)

But `reqmgr_auxilary` couchdb does not have campaign, cmsswversion or wmagentconfig databases/documents. I think it was in Seangchan plans to expand it. Therefore the ReqMgrAux cache I'm using is empty all the time.

So far I have no idea who suppose to create these DBs/docs, may be you know.

**Comment by vkuznet** [comment] 2019-05-28 19:30
With this code: https://gist.github.com/vkuznet/044b3bf8bd5e7450c71b253c6bd9a8d7
I parsed existing [campaigns.json](https://github.com/CMSCompOps/WmAgentScripts/blob/master/campaigns.json) file. Here is the stats:

Total number of campaign configuration: 258

Campaign configuration keys: ["ignoreduplicates", "secondary_AAA", "labels", "NO_tune", "NONONO_force-complete", "force-complete", "go", "recover", "secondaries", "primary_AAA", "NO_NO_tune", "parameters", "MergedLFNBase", "DDMcopies", "force-timeout", "tune", "SiteWhitelist", "NO_overflow", "maxcopies", "partial_copy", "SecondaryLocation", "custodial", "fractionpass", "NONONO_force-timeout", "overflow", "resize", "custodial_override", "truncate-complete", "SiteWhiteList", "NO_NO_fractionpass", "lumisize", "toDDM", "NONONO_partial_copy", "SiteBlacklist", "banned_tier", "earlyannounce"]

The campaign's configuration keys are only first level of nest-ness in campaign dicts. Each campaign has almost unique configuration. Just to give you an idea, here is a few last records I dumped
```
campain: 2023SHCALUpg14DR
{"go": false}


campain: StoreResults
{"go": true, "ignoreduplicates": true, "primary_AAA": false, "maxcopies": 1}


campain: RunIISummer18wmLHEGS
{"lumisize": -1, "force-complete": 0.99, "go": true, "overflow": {"LHE": {"site_list": "sites_AAA"}}, "tune": true, "fractionpass": 0.95}


campain: RunIIFall17FSDR
{"secondary_AAA": false, "maxcopies": 1, "lumisize": -1, "fractionpass": 0.95, "go": true, "tune": true, "secondaries": {"/MinBias_TuneCP2_13TeV-pythia8/RunIIFall17FSPremix-PUMoriond17_94X_mc2017_realistic_v11-v1/GEN-SIM-RECO": {"SiteWhitelist": ["T2_BE_IIHE", "T2_AT_Vienna", "T2_CH_CERN", "T1_US_FNAL"]}}, "resize": "auto"}


campain: RunIIWinter15pLHE
{"go": true, "recover": false, "parameters": {"EventsPerLumi": 200}}
```

Therefore it would be cumbersome to come up with common schema and it means that parsing campaign configuration can be nightmare in a code (i.e. each campaign has its own set of keys and I bet code will need lots of if/else statements).

I rather prefer to define campaign configuration schema on our own and adjust this records according to the schema.

**Comment by amaltaro** [comment] 2019-05-29 05:39
I completely agree, Valentin. There is one caveat though, which is the inconsistency/incompatibility between Ops+MongoDB and WMCore+CouchDB documents and schema. If we want to make a smooth data placement transition from Unified to ReqMgr2MS, we'll likely have to keep campaign configuration in two different places (Mongo and Couch), in a transparent way not to add any overhead to Ops.

There are a few ways out though - might have to be discussed with P&R though - for instance:
1) define a proper campaign schema, discuss with P&R and adapt their code and campaign configuration
2) implement a code that parses Ops campaigns and convert it to "WMCore" campaign 

2nd option is easier and doesn't depend on anyone, so it's also quicker to get all the pieces in place. But then we'll likely need another piece of software that polls Unified mongodb from time to time, does the conversion, and inserts new documents. OR we add something directly to Unified such that everytime there are campaign changes, it does the same to the couch record. Maybe we should follow that up in a separate thread.

**Comment by amaltaro** [comment] 2019-05-29 06:31
Just a note, we only need a subset of the campaign configuration. We're not going to run the full unified functionality, so we could drop anything that is not important for data placement (and future workflow completion).

**Comment by vkuznet** [comment] 2019-05-29 13:31
Ok, I'm in favor of option 2 as well. Can we define the schema then. I'm not sure I'm the right person to do that. From campaigns records I see that we may use:
- SiteWhiteList
- SiteBlackList
- custodial site
- dataset name
- dataset type

And, I'm in favor of flat data-structure. This brings me to the following format (similar to workflow records):
```
{
  "campaign_A": [record1, record2],
  "campaign_B: [...]
}
```
where individual record will have the following format:
```
{"SiteWhiteList": ["T1", "T2"], "SiteBlackList": [...], "custodialSite": "T1", "dataset":"/a/b/c", "type":"secondary"}
```
Using this records we can expand their structure as necessary, e.g. add `"EventsPerJob":123`, and still maintain backward compatibility of entire format.

Then, we declare that if dataset name is not specified the record can be applied to any dataset, etc.

Please provide your input and correct whatever you feel necessary.

**Comment by vkuznet** [comment] 2019-05-29 17:33
and, if we don't want single record, we can use aforementioned records to feed in couchDB with additional campaign name, e.g.
```
{"campaign": "SiteWhiteList": ["T1", "T2"], "SiteBlackList": [...], "custodialSite": "T1", "dataset":"/a/b/c", "type":"secondary"}
```
This will create series of records with identical structure in couchdb.

**Comment by amaltaro** [comment] 2019-05-29 19:01
The way I see it is that the campaign name will be actually the document id. So we can have a flat dictionary as data structure for each campaign configuration, for instance (basically what you suggested above):
```
{"SiteWhiteList": ["T1", "T2"], "SiteBlackList": [...], "custodialSite": "T1", "dataset":"/a/b/c", "type":"secondary"}
```

**Comment by vkuznet** [comment] 2019-05-29 19:24
Fine with me. Now, with [parse_campaigns.py](https://gist.github.com/vkuznet/044b3bf8bd5e7450c71b253c6bd9a8d7) I can generate new records. If you'll tell me how to upload them to CouchDB I can do that. I suggest to use temp db which we can re-create/clean-up/play-with until we reach the state of the code when we can feed data into final db.

**Comment by amaltaro** [comment] 2019-05-29 19:39
https://github.com/dmwm/WMCore/wiki/ReqMgr2-apis#create-a-new-campaign-configuration-document-in-couchdb

please use of my VMs first: alancc7-cloud1 or alancc7-cloud2
IF everything goes fine, then you can upload them to cmsweb-testbed (please do NOT push these docs to production yet)

**Comment by vkuznet** [comment] 2019-05-29 20:49
Alan, I was able to insert records into my VM, e.g. see
https://vk-reqmgr.cern.ch/couchdb/_utils/document.html?reqmgr_auxiliary/WMAGENT_CONFIG_RunIIFall17FSDR

Please have a look at other records too that we'll be sure that everything is what we need.

I inserted records by running the following:
```
./parse_campaigns.py --fin=campaigns.json --verbose 1 --url=https://vk-reqmgr.cern.ch/reqmgr2
```

Instead of using curl (my favorite method and the one you posted) I used ReaMgrAux class from python code since this I bet what we'll need at the end if we'll want to migrate campaign records from MongoDB to CouchDB. The [parse_campaigns.py](https://gist.github.com/vkuznet/044b3bf8bd5e7450c71b253c6bd9a8d7) just does that. Feel free to inspect code and decide how to maintain it (if we'll need to periodically insert MongoDB records into the couch we may need this script). Once I'll get access to MongoDB on Unified node I'll adjust this script accordingly to read records from MongoDB and we'll be all set. So you may decide to keep it around somewhere in WMCore codebase.

**Comment by amaltaro** [comment] 2019-06-03 09:12
Valentin, it looks like you're running an old'ish WMCore version because it doesn't have a fix a made to the campaign api, thus those doc type are marked as `WMAGENT_CONFIG`. BTW, I just noticed it overwrote the `type` document key, so we can't use `type` as a campaign configuration parameter.

In addition to that, and even more important, we should make sure we have all the necessary parameters (in our WMCore schema) for the correct data placement. Scanning the list you posted above, I found the following candidates:
```
secondary_AAA, go, secondaries, primary_AAA, SiteWhitelist, maxcopies, partial_copy, SecondaryLocation, SiteBlacklist
### these 3 will likely be needed in the near future
DDMcopies, fractionpass, banned_tier
```

Can you please go through the Unified logic for data placement and collect the necessary parameters?

About the `parse_campaigns.py` script, yes I agree that using the ReqMgrAux WMCore module is the way to go here. Perhaps we could rename it, write a nice description at the top of the module, and store it here:
https://github.com/dmwm/WMCore/tree/master/bin/adhoc-scripts

**Comment by vkuznet** [comment] 2019-06-03 13:19
So far I found these keys in transferor code (but I didn't scan all dependencies):
labels secondaries maxcopies SecondaryLocation custodial banned_tier

The issue here is two-fold:
- do you want to take campaigns configuration and store keys as is, or adjust to common naming convention, e.g. unified used all possible key combinations, e.g. camel case (`SiteWhitelist`), underscore case (`partial_copy`), lower cases (`secondaries`), one-word cases (`fractionpass`)
- how to deal with nested structures, e.g. `secondaries`, contains another dict structure

If we'd like to make maintainable code, schema, I suggest to use one common naming convention and adjust code/keys/conf accordingly as we go and adapt the code.

**Comment by vkuznet** [comment] 2019-06-03 13:26
Alan,
regarding old'ish WMCore version. Please be specific which one should I use, otherwise I have no idea.

And, regarding `type` we can easily adapt `campaignType` instead.

**Comment by vkuznet** [comment] 2019-07-02 13:24
So I already in this ticket outlined flat structure for campaigns.
The parser script from #9273 can read them from Unified MongoDB. Here is an examples
(see full list here: /afs/cern.ch/user/v/valya/public/UnifiedCampaigns.txt)
```
{"campaignType": null, "Campaign": "HINPbPbSpring18DR", "maxCopies": 1, "SiteWhiteList": [], "custodialSite": "T1_FR_CCIN2P3_MSS", "dataset": null, "fractionPass": 0.95, "SiteBlackList": ["T1_US_FNAL", "T2_US_Purdue", "T2_US_Caltech", "T2_US_Florida", "T2_US_Nebraska", "T2_US_UCSD", "T2_US_Wisconsin"]}
```

But I am not the one who should decide which attributes should be present in a
schema, I don't use these records and do not have much knowledge where/how these
campaigns records should be used. I better rely on your opinion or others
to tell me which attributes should be used in these records.

**Comment by amaltaro** [comment] 2019-07-11 12:27
After asking many questions to CompOps over slack, I believe this is what will be our final Campaign schema:
```
{
 "CampaignName": "blah2019",
 "SiteWhiteList": ["T1", "T2"],
 "SiteBlackList": [...],
 "custodial": "blah",           # likely not used for input data placement
 "secondaries": {"datasetA": ["list of sites for SiteWhitelist"], "datasetB": ["list of sites for SiteWhitelist"]},
 "maxcopies": integer  # max replicas for the primary data (it overrides the CPU/h calculation thingy)
}
```

And here are my notes for some questions I had about these keys usage and key duplication in different places of the campaign configuration.
"""
* if there is SiteWhitelist/SiteBlacklist at the top level campaign configuration, then it’s used for both workflow assignment and InputDataset placement
* if there is SiteWhitelist under the `secondaries` key (I saw no occurrences of SiteBlacklist there), then it’s also used for workflow assignment AND pileup data placement.
"""

Then about `SecondaryLocation`.
"""
* it can be either at top level and under the `secondaries` key. It makes no difference!
* the difference between `SiteWhitelist` and `SecondaryLocation` is that the former is meant to be used for MinBias, while the second is used for premixed samples (Neutrino). The reason for that is likely that `SecondaryLocation` is only used for data placement, while `SiteWhitelist` is also used for workflow assignment.
"""

I'll discuss this again during the P&R meeting today at 3pm. There are a few trick things to be sorted out and we'll have to update the transferor algorithm as well. But this is the right moment for that, or we live forever with confusions.

**Comment by amaltaro** [comment] 2019-07-11 14:32
@sharad1126 and @thongonary , I updated the example above as we discussed during the meeting.
Can you please have another look at it and give your opinion whether it looks complete or not?
Would you also know the default value for those two AAA flags? Thanks

**Comment by sharad1126** [comment] 2019-07-12 11:00
@amaltaro looks good to me. regarding the default value, we keep it true for premix DR and false for standard mix DR.

**Comment by amaltaro** [comment] 2019-07-12 12:29
@sharad1126 my point is, if those parameters are not defined in a campaign, should we assume their value is `False` or should it be `True`? I believe it's false, but better confirming.

**Comment by amaltaro** [comment] 2019-07-12 12:49
According to Sharad, old campaigns might still have `SecondaryLocation` under the `secondaries` key, but newer stuff will always have it under the top level dict.

Also talked to Sharad and the default `primary_AAA` and `secondary_AAA` value is `false`.

**Comment by sharad1126** [comment] 2019-07-12 13:01
yes exactly. Thanks @amaltaro

**Comment by vkuznet** [comment] 2019-07-13 00:59
We need full set of instructions or logic how to extract these attributes from existing campaigns.json or MongoDB. Please provide concrete instructions for **EVERY** single attribute you propose to store. For example, here is an example of record which I took from campaigns.json file
```
  "HINPbPbAutumn18DR": {
    "custodial": "T1_FR_CCIN2P3_MSS",
    "fractionpass": 0.95,
    "go": true,
    "lumisize": -1,
    "maxcopies": 1,
    "parameters": {
      "MergedLFNBase": "/store/himc",
      "SiteBlacklist": [
        "T1_US_FNAL",
        "T2_US_Purdue",
        "T2_US_Caltech",
        "T2_US_Florida",
        "T2_US_Nebraska",
        "T2_US_UCSD",
        "T2_US_Wisconsin",
        "T2_CH_CERN",
        "T2_CH_CERN_HLT"
      ]
    },
    "secondaries": {
      "/MinBias_Hydjet_Drum5F_2018_5p02TeV/HINPbPbAutumn18GS-103X_upgrade2018_realistic_HI_v11-v1/GEN-SIM
": {
        "SiteWhitelist": [
          "T1_RU_JINR",
          "T1_FR_CCIN2P3"
        ]
      }
    },
    "tune": true
  }
```
My questions are:
- `CampaignName` is HINPbPbAutumn18DR
- `PrimaryAAA` ???
- `SecondaryAAA` ???
- `SiteWhiteList/SiteBlackList` should come from parameters, right? If not where else to look for them, otherwise should the list be empty?
- `secondaries` is clear here
- `MaxCopies` is clear here

Please provide full details for all possible type of records you have that we can write a parser. Without this knowledge I don't know what to implement, i.e. I need to know where/how to extract proposed attributes from campaigns.json or MongoDB.

**Comment by amaltaro** [comment] 2019-07-13 06:41
Besides the `CampaignName`, which is the campaign.json.keys(), so yes `HINPbPbAutumn18DR`; all the rest has been described above on how to extract, from where, and what to do in case of multiple definitions within the same campaign.

Check this comment https://github.com/dmwm/WMCore/issues/9139#issuecomment-510464706
and the comments I made in the data structure.

**Comment by vkuznet** [comment] 2019-07-15 15:02
Alan, this statement is ambiguous and can't be done for boolean data types:
```
SecondaryAAA: boolean to flag whether to use AAA for the secondary dataset; mapped from the secondary_AAA key, which can be either at top level or under the secondaries dictionary. If it appears multiple times, we make an intersection of the values.
```
If we have multiple values we can't take intersection of boolean data-types, e.g. what is a value ifor this list `[true, false]`, is it true is is it false? What is priority a top-level value or secondary value? What if we have multiple values in secondaries, how to treat them? Please clarify this with data ops.

**Comment by amaltaro** [comment] 2019-07-15 15:15
I meant an OR (as written down in a few other places). I also updated that comment.

**Comment by vkuznet** [comment] 2019-07-15 19:30
Alan, I adjusted the code according to listed rules and generated new set of config records in  /afs/cern.ch/user/v/valya/public/UnifiedCampaigns.txt Please review them again. Once you're ok with them I suggest to pass them to data ops for review and then we can inject them to couch.

**Comment by amaltaro** [comment] 2019-07-24 09:21
Just an update here from what I observed after staring at those campaign configurations.
> if there is SiteWhitelist/SiteBlacklist at the top level campaign configuration, then it’s used for both workflow assignment and InputDataset placement

Regarding the comment/conclusion above, I think it's mistaken. There are campaigns with multiple secondary datasets, where each dataset has its own SiteWhitelist. So I believe the placement of such secondary datasets should be driven by its internal SiteWhitelist (not the one set at the top level).

Which leaves us with another open question. What to do when a secondary dataset/MinBias doesn't have any SiteWhitelist?

@sharad1126 and @thongonary , can you please comment on it once you get back from vacation/conference? Thanks

**Comment by thongonary** [comment] 2019-07-24 09:52
- If the secondary dataset doesn't any have internal SiteWhitelist key, it will use the whitelist obtained from the workflow (top-level white list / primary dataset whitelist / or all eligible sites etc.) and then distribute the secondary to those sites.
- If the secondary dataset has internal SiteWhitelist = {} (blank), then the workflow will simply not run.

**Comment by amaltaro** [comment] 2019-07-25 06:07
Thanks, Thong.

I think we addressed what we were meant to address on this issue. @vkuznet if you agree, I'd close this issue and create a new one to enforce the campaign schema when pushing/updating a Campaign document in Couch (that can probably be done once we have things in production though).

**Comment by vkuznet** [comment] 2019-07-29 12:55
fine with me

**Closed** 2019-07-30 08:16 UTC
Labels: Feature change, High Priority, ReqMgr2, ReqMgr2MS, Unified Porting
