### ISSUE TITLE
Remove/replace MySQL-python library by something else that supports python3

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9805] opened 2020-07-07 08:34 UTC
**Impact of the new feature**
WMCore in general (and perhaps other services depending on it)

**Is your feature request related to a problem? Please describe.**
Yes, this package `MySQL-python` does not support python3. Actually, its last commit dates back from 2014...

**Describe the solution you'd like**
Either completely deprecate this package from the COMP cmsdist repo:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py2-mysqldb.spec

and update all the other specs depending on it. Or if this functionality is needed in WMCore (or other DMWM services), we need to find a library that supports python3 (and probably works still in python2), like `PyMySQL`:
https://pypi.org/project/PyMySQL/

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
Issue initially created here: https://github.com/cms-sw/cmsdist/issues/6025

**Comment by amaltaro** [comment] 2020-07-07 08:36
From a quick look in WMCore, it seems this is the only place still depending on this library:
https://github.com/dmwm/WMCore/blob/master/src/python/WMQuality/TestInit.py#L23

so it can be easily deprecated in WMCore.

**Comment by mapellidario** [comment] 2020-07-14 10:32
Currently, `MySQL-python` source code is hosted at https://github.com/farcepest/MySQLdb1 . The python package name is `MySQLdb`. In addition to the the occurrence that you found, where we can drop the dependency by using a more generic exception, there are some occurrences of `MySQLdb` in `src/python/WMCore/REST/Server.py`, such as

* [L1250](https://github.com/dmwm/WMCore/blob/4f58231e34ee256deb1a93d8ad6bf9af6cece61a/src/python/WMCore/REST/Server.py#L1250)
* [L1519](https://github.com/dmwm/WMCore/blob/4f58231e34ee256deb1a93d8ad6bf9af6cece61a/src/python/WMCore/REST/Server.py#L1519)
* [L1535](https://github.com/dmwm/WMCore/blob/4f58231e34ee256deb1a93d8ad6bf9af6cece61a/src/python/WMCore/REST/Server.py#L1535)
* [L1825](https://github.com/dmwm/WMCore/blob/4f58231e34ee256deb1a93d8ad6bf9af6cece61a/src/python/WMCore/REST/Server.py#L1825)

It does not seem that this dependency is playing a big role. It seems to be used just to set some metadata in the form of some class members, or to select some errorcode depending on the DB backend. We can either make some changes to state clearly that we are not using `MySQL-python` / `MySQLdb` or we can leave this module untouched and avoid to insert any bug and simply drop the dependency.

**Comment by amaltaro** [comment] 2020-07-14 12:02
Hmm, from the package dependencies:
https://github.com/dmwm/WMCore/blob/master/setup_dependencies.py#L8

it looks like such change in the REST module would affect:
* reqmgr2
* reqmgr2ms
* workqueue
* crabcache
* crabserver
* reqmon

I though DBS was also relying on it... So my concern is with CRABServer (and maybe CRABCache). In case you come up with a PR to remove this functionality from WMCore, we should ping Stefano to test things before we merge anything.

**Comment by mapellidario** [comment] 2020-07-14 15:55
That is why I would actually only drop the dependency for now and leave all the code cleaning for the future.

I assume that "discarding the dependency" for us only means

* changing https://github.com/cms-sw/cmsdist/blob/42f35692d6547ac859e017a05ebc221e6f611e77/wmagent.spec#L9
* changing https://github.com/dmwm/WMCore/blob/4f58231e34ee256deb1a93d8ad6bf9af6cece61a/requirements.wmagent.txt#L4
* changing https://github.com/dmwm/WMCore/blob/4f58231e34ee256deb1a93d8ad6bf9af6cece61a/requirements.txt#L5

Am I correct? Do you see any problem in just changing our dependencies and trying to run our agents without that dependency before contacting others?

**Comment by amaltaro** [comment] 2020-07-15 22:22
I was going to remove `py2-mysqldb` from the `Requires` list for the t0.spec and wmagent.spec, but I think it's too risky to make this change just before I'm gone. I will keep this issue open and resume working on it in August.

**Comment by amaltaro** [comment] 2020-10-08 11:56
@mapellidario I guess this issue is still opened because there was this pending item to remove the dependency from the spec files in cmsdist, right?

**Comment by mapellidario** [comment] 2020-10-08 12:05
Yes, you are correct.

**Comment by amaltaro** [comment] 2020-10-08 12:15
Sigh... I forgot testing it this week when a new WMAgent production release was made. Will try again in the coming days. Thanks Dario.

**Comment by mapellidario** [comment] 2020-10-30 11:32
We continued our investigations to understand if a repository uses `MySQL-python`.

Purpose: 
* drop `py2-mysqldb` from the list of dependencies in WMCore packages spec files and WMCore clients spec files, such as [crabserver.spec](https://github.com/cms-sw/cmsdist/blob/130fe6e899f1a2a625ff6b248e93cd2efaac2db5/crabserver.spec)

References:
* [py2-mysqldb.spec - v1.2.4b4](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py2-mysqldb.spec)
* [pypi MySQL-python](https://pypi.org/project/MySQL-python/)
* [github MySQLdb1 - v1.2.4b4](https://github.com/farcepest/MySQLdb1/tree/0f8d86cc8729efee304b15ae8c022bbc05f844db)

How can this package be imported

```python
import MySQLdb
# or also
import _mysql_exceptions.py
```

WMCore does not contain such import. It should be safe to drop py2-mysqldb from WMCore pacakges spec files

**Comment by mapellidario** [comment] 2020-10-30 11:45
We opened a similar issue in dmwm/CRABServer: https://github.com/dmwm/CRABServer/issues/6228

**Comment by amaltaro** [comment] 2020-11-02 23:38
I have not debugged this problem yet, but deployment of 1.4.2.pre7 - which no longer has the dependency on py2-mysqldb - failed when installing the database, see:
```
*** Starting services ***
WMAgent with Rucio enabled: true
Starting Services...
starting couch...
CouchDB has not been initialised... running pre initialisation
Initialising CouchDB on 127.0.0.1:5984...
Apache CouchDB has started, time to relax.
CouchDB has not been initialised... running post initialisation
Starting mysql...
MySQL has not been initialised... running pre initialisation
Installing the mysql database area...
./manage: line 336: mysql_install_db: command not found
starting mysqld_safe...
Checking MySQL Socket file exists...
ERROR: Timeout waiting for mysqld to start.
Done!
```

Dario, this is likely something that we have to discuss and see what our options are.

**Comment by amaltaro** [comment] 2020-11-02 23:39
And another problem while stopping the agent
```
cmst1@vocms0262:/data/srv/wmagent/current $ $manage stop-agent
WMAgent with Rucio enabled: true
Shutting down WMAgent...
Checking default database connection... Unable to make connection to using 
parameters provided in mysql://cmst1:Someslc7Senha@localhost/wmagent
No module named MySQLdb
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.2.pre7/sw/slc7_amd64_gcc630/cms/wmagent/1.4.2.pre7/bin/wmcoreD", line 351, in <module>
    connectionTest(config)
  File "/data/srv/wmagent/v1.4.2.pre7/sw/slc7_amd64_gcc630/cms/wmagent/1.4.2.pre7/bin/wmcoreD", line 191, in connectionTest
    raise ex
ImportError: No module named MySQLdb
```

**Comment by amaltaro** [comment] 2020-12-16 21:38
Since we failed to get rid of this library, let me get it reassigned to you Dario ;-)

**Comment by amaltaro** [comment] 2021-02-15 08:26
@mapellidario as we discussed in the past week, I'm setting this issue free such that others can pick it, if they want.

**Comment by todor-ivanov** [comment] 2021-04-15 07:52
Adding some more command output here, just for logging purposes.
```
cmst1@vocms0260:/data/srv/wmagent $  /data/srv/wmagent/current/config/wmagentpy3/manage stop-services
Shutting down services...
stopping couch...
Apache CouchDB has been shutdown.
stopping mysql...
/data/srv/wmagent/current/config/wmagentpy3/manage: line 390: mysqladmin: command not found
Making sure the MySQL socket file is removed...
MySQL is shutdown.
```

**Comment by todor-ivanov** [comment] 2021-04-15 08:59
Hi @amaltaro Regarding this  comment: https://github.com/dmwm/WMCore/issues/9805#issuecomment-705519358

Can you please, provide a pointer to the so pending issue in cmsdist. Because it seems to me the dependency from `py2-mysqldb.spec` has already been dropped in the `wmagentpy3.spec` which basically drops the dependency regarding the client, but strangely enough, the MariaDB server dependency is somehow referred through this spec file [1]. So the final result is - no MariaDB service installed on the py3 wmagent version, hence the lack of all the admin commands needed by the `$manage` script like `mysql_install_db` and `mysqladmin`, hence the errors above. I also wonder if we should just link the dependency of mariadb directly into the `wmagentpy3.spec` or we should swap the `MySQL-python` package with it's fork for py3 [2], which is supposed to provide full compatibility with the `MySQLdb1` library provided by `MySQL-python` package.

Please let me know your opinion here. But there is one thing I am sure about - there is no MariDB installed on the py3 wmagent currently. 

[1]
https://github.com/cms-sw/cmsdist/blob/9d61b122cbf0b69f8cc601408895637c55253e42/py2-mysqldb.spec#L6

[2]
https://pypi.org/project/mysqlclient/

info taken from this reply in stackoverflow:
https://stackoverflow.com/questions/4960048/how-can-i-connect-to-mysql-in-python-3-on-windows

**Comment by amaltaro** [comment] 2021-04-15 12:12
> Hi @amaltaro Regarding this comment: #9805 (comment)
> Can you please, provide a pointer to the so pending issue in cmsdist.

So, I did test WMAgent without the `py2-mysqldb` dependency and the result is the failure reported here
https://github.com/dmwm/WMCore/issues/9805#issuecomment-720787167

meaning, we somehow still need it (not sure what for though).

> Because it seems to me the dependency from py2-mysqldb.spec has already been dropped in the wmagentpy3.spec

Yes, I didn't even try to create the mysqldb package on python3 (thus py3-mysqldb.spec) because the developers say there is no support for python3. So there was no point in trying to build it and/or add it as a dependency for the python3 stack.

> but strangely enough, the MariaDB server dependency is somehow referred through this spec file [2]

good catch! That means, our wmagentpy3.spec file has no dependency at all in `mariadb`. We could try adding this dependency and try to deploy wmagent again (both in py2 and py3 stacks).

> I also wonder if we should just link the dependency of mariadb directly into the wmagentpy3.spec

Yes, this is the first attempt I would chase. If it does not work, then we need to build a `py3-mysqlclient.spec` file to ship the python3 supported `mysqlclient`, and if needed, add MariaDB in there as a "Requires".

Just to wrap up these comments, here is what I would suggest to change (ordered):
* add `mariadb` dependency directly to the wmagentpy3.spec file and try to deploy it (it might be needed to do the same with wmagent.spec, just to have a solid comparison baseline)
* create a `py3-mysqlclient.spec` spec to ship `mysqlclient` library in python3 stack (without MariaDB, to start with). Add this spec as a dependency to `wmagentpy3.spec` and test deployment/running.
* last option, create the spec above but adding `mariadb` as a dependency inside this spec. Add it to the `wmagentpy3.spec` and test deployment/running.

What do you think? Have I missed anything? Thanks for this investigation, Todor.

**Comment by todor-ivanov** [comment] 2021-04-15 12:20
Hi @amaltaro thanks. This plan is exactly what I was having in my mind too. So we are on the same page here. But just to be sure: should we try the first two bullets separately/consequently or both together from the very first attempt?

**Comment by todor-ivanov** [comment] 2021-04-16 09:22
Just before I forget I need to log two additional steps which are a must in order to put the above plan in action.
   * We need to fix the fact that with installing the `wmagentpy3` package the deployment area changes and we need a soft link of the type:
```
cmst1@vocms0260:/data/srv $ ln -s /data/srv/wmagent/current/config/wmagentpy3/  /data/srv/wmagent/current/config/wmagent
/data/srv/wmagent/current/config/wmagent -> /data/srv/wmagent/current/config/wmagentpy3/
```

Should be notified here too https://github.com/dmwm/WMCore/pull/10302

   * When installing from a personal repository in `cmsrep` (adding the option `-r comp=comp.<username>` to the deployment script) the deployment area is created as `/data/srv/wmagent/current/sw.<username>`, but all sort of *PATH variables in the environment point to `/data/srv/wmagent/current/sw`. An example is: 
```
/data/srv/wmagent/current/apps/wmagent -> ../sw/slc7_amd64_gcc630/cms/wmagentpy3/1.4.7.patch1-comp
```

Which is crucial for the rest of the software to initiate and run. So we will have to fix the deployment script such that it also creates the following symlink:
```
/data/srv/wmagent/current/sw -> sw.<username>
``` 

Otherwise even if the `MariaDB` dependency is properly set in the rpm [1], we still experience the previous errors, only because the environment is not set properly.

[1]
```
cmst1@vocms0260:/data/srv $ rpm -q --requires -p cms+wmagentpy3+1.4.7.patch1-comp-1-1.slc7_amd64_gcc630.rpm  |grep mariadb
external+mariadb+10.1.21-comp3
```

FYI @amaltaro

**Comment by amaltaro** [comment] 2021-04-16 10:14
Todor, on your first bullet above. Another option would be to update the env.sh script, as mentioned in #10302

**Comment by todor-ivanov** [comment] 2021-04-16 10:41
Hi @amaltaro. Yes, indeed this is an option, but it would require a manual intervention every time we deploy with `-py3`, which is error prone. (I personally tend to forget those procedural peculiarities the minute I am done with the first deployment after the PR introducing the change). So I'd rather put the link and let the deployment script do the rest for me.

**Comment by todor-ivanov** [comment] 2021-04-16 11:31
Following the first scenario from this comment : https://github.com/dmwm/WMCore/issues/9805#issuecomment-820374596 and adding the `MariaDB` dependency directly into the `wmagentpy3.spec`: https://github.com/cms-sw/cmsdist/pull/6817 ,  together with the proposed changes to the deployment script from https://github.com/dmwm/WMCore/pull/10454 I managed to properly deploy the WMAgent and the relevant mysql databases [1]. I am fighting with another error now [2]. But I think we already agreed the later is a problem related to a separate set of package dependency. 

So @amaltaro if you think we may merge those two PRs (in WMCore and cmsdist repositories) and close the current issue it would be great.  The error mentioned in [2],  we can follow in it's dedicated GH issue.

[1]
```
To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system

PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following commands:

'/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/external/mariadb/10.1.21-comp3/bin/mysqladmin' -u root password 'new-password'
'/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/external/mariadb/10.1.21-comp3/bin/mysqladmin' -u root -h vocms0260.cern.ch password 'new-password'

Alternatively you can run:
'/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/external/mariadb/10.1.21-comp3/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at http://mariadb.com/kb or the
MySQL manual for more instructions.

You can start the MariaDB daemon with:
cd '/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/external/mariadb/10.1.21-comp3' ; /data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/external/mariadb/10.1.21-comp3/bin/mysqld_safe --datadir='/data/srv/wmagent/v1.4.7.patch1-comp/install/mysql/database'

You can test the MariaDB daemon with mysql-test-run.pl
cd '/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/external/mariadb/10.1.21-comp3/mysql-test' ; perl mysql-test-run.pl

Please report any problems at http://mariadb.org/jira

The latest information about MariaDB is available at http://mariadb.org/.
You can find additional information about the MySQL part at:
http://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

starting mysqld_safe...
Checking MySQL Socket file exists...
Socket file exists: /data/srv/wmagent/v1.4.7.patch1-comp/install/mysql/logs/mysql.sock
MySQL has not been initialised... running post initialisation
Installing the mysql schema...
Socket file exists, proceeding with schema install...
Installing WMAgent Database: wmagent
Checking Server connection...
Connection OK
Done!
```

[2]
```
*** Initializing the agent ***
Initialising Agent...
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.7.patch1-comp/bin/wmagent-mod-config", line 14, in <module>
    standard_library.install_aliases()
  File "/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/external/py3-future/0.18.2/lib/python3.8/site-packages/future/standard_library/__init__.py", line 453, in install_aliases
    __import__(newmodname)
ImportError: No module named reprlib
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.7.patch1-comp/bin/wmcore-db-init", line 19, in <module>
    from WMCore.Configuration import loadConfigurationFile
ImportError: No module named WMCore.Configuration
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.7.patch1-comp/bin/wmagent-couchapp-init", line 9, in <module>
    standard_library.install_aliases()
  File "/data/srv/wmagent/v1.4.7.patch1-comp/sw.tivanov/slc7_amd64_gcc630/external/py3-future/0.18.2/lib/python3.8/site-packages/future/standard_library/__init__.py", line 453, in install_aliases
    __import__(newmodname)
ImportError: No module named reprlib
Done!

*** Checking if couchdb migration is needed ***
Done!

```

**Comment by amaltaro** [comment] 2021-04-16 12:11
Perfect! Thanks for spotting these issues and providing these fixes.

However, I think those were pre-requirements to get you to be able to debug the actual issue reported in this issue. There has been quite some discussion here, but I'm still not sure whether we need `MySQL-python` (or a python3 version of it) integrated into WMAgent or not.

As we have already discussed in other venues, when creating the wmagentpy3 spec file, `py2-mysqldb.spec` was not added because that library does not support python3. That said, it does not mean we don't need it, because our codebase might be trying to use it somewhere in the code.

So, the expected outcome of this issue will be either:
a) WMCore codebase no longer depends in `MySQL-python` and there is nothing else to be done in wmagentpy3.spec
b) WMCore codebase still depends on `MySQL-python` and we have to find a python3 base library replacement; then update the WMCore codebase with the new library.

Could you please investigate it?

**Comment by todor-ivanov** [comment] 2021-04-16 13:48
Oook then. Let me take a deep breath and I am about to dive deeper now :)

**Comment by todor-ivanov** [comment] 2021-04-16 16:29
Hi  @amaltaro . So far, from what I am capable of tracing as imports in WMCore, I can not spot any direct or indirect import of the library `MySQLdb` (which is the one provided by the `MySQL-python` package). And also @mapellidario managed to run the `pythondep` tool as explained  here [1], and confirmed my observation. All that said, I dare to state that we are in the position:  
> a) WMCore codebase no longer depends in MySQL-python and there is nothing else to be done in wmagentpy3.spec

[1]
https://cms-dmwm-test.docs.cern.ch/py2py3/tools/pydeps/

**Comment by amaltaro** [comment] 2021-04-19 08:25
Wonderful! Thanks Todor and Dario. 

Just a note, if we face issues related with this in the future, we might want to directly add the "mariadb" dependency in wmagent.spec and drop "py2-mysqldb" one. This way we can compare things against something that we know is solid and working.

**Comment by amaltaro** [comment] 2021-05-19 13:08
Now that I managed to progress with the python3 environment, we seem to have missed one usage of this library (but I could be wrong as well...):
```
No module named 'MySQLdb'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre1/bin/wmcore-db-init", line 158, in <module>
    connectionTest(cfgObject)
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre1/bin/wmcore-db-init", line 123, in connectionTest
    raise ex
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre1/bin/wmcore-db-init", line 115, in connectionTest
    wmInit.setDatabaseConnection(dbConfig = config.CoreDatabase.connectUrl,
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre1/lib/python3.8/site-packages/WMCore/WMInit.py", line 131, in setDatabaseConnection
    myThread.dbFactory = DBFactory(logging, dbConfig, options)
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre1/lib/python3.8/site-packages/WMCore/Database/DBFactory.py", line 84, in __init__
    create_engine(self.dburl,
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/data/srv/wmagent/v1.4.9.pre1/sw.amaltaro/slc7_amd64_gcc630/external/py3-sqlalchemy/1.3.3/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
```

debugging

**Comment by todor-ivanov** [comment] 2021-05-19 15:08
@amaltaro 
Where is this StackTrace from?

**Comment by amaltaro** [comment] 2021-05-19 20:10
It looks like we have a couple of optional drivers to use for MySQL which are supported in python3:
https://docs.sqlalchemy.org/en/14/core/engines.html#mysql

I had a quick look and `PyMySQL` seems to be easier to integrate with our stack, given that it's purely written in python. However, I have also found a few places suggesting that it delivers a performance worse than `mysqlclient`, another driver supported in python3 and based in the mysql library (c?). 

I guess I will try to build `mysqlclient` in our COMP repo first. If it works, we will have to change the connect string in WMCore.

**Comment by vkuznet** [comment] 2021-05-19 20:23
@amaltaro , in python if you need speed it is accomplished by Python-C bindings, therefore "pure" python is always slow with respect to Python-C binding implementation. Therefore, based on your use-case you need to decide to go with pure python or c-based implementation. The latter will always require gcc/glibc stack and therefore will be dependent on it. All high-performance tasks/libraries in python, e.g. NumPy, are basically Python-C binding to underlying C libraries.

**Comment by todor-ivanov** [comment] 2021-05-19 20:34
@amaltaro I am trying to create a pip build backage of `mysqlclient` and installing in a minute
I will post the result here.

**Comment by todor-ivanov** [comment] 2021-05-19 21:09
@amaltaro  here [1] is the PR providing a properly build package `mysqlclient` for py3 but the error during the deployment still persists. I am checking what else is missing. 

https://github.com/cms-sw/cmsdist/pull/6926

**Comment by todor-ivanov** [comment] 2021-05-19 22:12
Hi again @amaltaro,

Actually I figured out why it was having troubles. I had to put some more dependencies here and there - like making `py3-sqlachemy` depending on `py3-mysqlclien`[1], which was basically the reason for the error we were facing (The one from Alan's stack trace). Now  my deployment passed through it  and hit another wall [2], but this one I believe is no longer related to `MySQLdb` for py3.


[1]
https://github.com/cms-sw/cmsdist/pull/6926/commits/af7fc4a9e85b1005d2e14cd8d3063c8a76e1f1ab

[2] 
```
*** Populating resource-control ***
Adding only T1 and T2 sites to resource-control...
Executing wmagent-resource-control --add-T1s --plugin=SimpleCondorPlugin --pending-slots=50 --running-slots=50 --down ...
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/bin/wmagent-resource-control", line 16, in <module>
    from WMCore.ResourceControl.ResourceControl import ResourceControl
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/ResourceControl/ResourceControl.py", line 11, in <module>
    from WMCore.BossAir.BossAirAPI import BossAirAPI
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/BossAir/BossAirAPI.py", line 23, in <module>
    from WMCore.JobStateMachine.ChangeState import ChangeState
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 20, in <module>
    from WMCore.Services.Dashboard.DashboardReporter import DashboardReporter
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Services/Dashboard/DashboardReporter.py", line 13, in <module>
    from WMCore.Services.Dashboard.DashboardAPI import DashboardAPI
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Services/Dashboard/DashboardAPI.py", line 12, in <module>
    from WMCore.Services.Dashboard import apmon
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Services/Dashboard/apmon.py", line 55, in <module>
    from types import LongType
ImportError: cannot import name 'LongType' from 'types' (/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/types.py)
Executing wmagent-resource-control --add-T2s --plugin=SimpleCondorPlugin --pending-slots=50 --running-slots=50 --down ...
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/bin/wmagent-resource-control", line 16, in <module>
    from WMCore.ResourceControl.ResourceControl import ResourceControl
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/ResourceControl/ResourceControl.py", line 11, in <module>
    from WMCore.BossAir.BossAirAPI import BossAirAPI
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/BossAir/BossAirAPI.py", line 23, in <module>
    from WMCore.JobStateMachine.ChangeState import ChangeState
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 20, in <module>
    from WMCore.Services.Dashboard.DashboardReporter import DashboardReporter
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Services/Dashboard/DashboardReporter.py", line 13, in <module>
    from WMCore.Services.Dashboard.DashboardAPI import DashboardAPI
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Services/Dashboard/DashboardAPI.py", line 12, in <module>
    from WMCore.Services.Dashboard import apmon
  File "/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/cms/wmagentpy3/1.4.9.pre2-comp2/lib/python3.8/site-packages/WMCore/Services/Dashboard/apmon.py", line 55, in <module>
    from types import LongType
ImportError: cannot import name 'LongType' from 'types' (/data/srv/wmagent/v1.4.9.pre2-comp2/sw.tivanov/slc7_amd64_gcc630/external/python3/3.8.2-comp/lib/python3.8/types.py)
Done!
```

**Comment by todor-ivanov** [comment] 2021-05-19 22:29
Actually I think the dependency I've put in `py3-sqlachemy` is redundant. The `py3-mysqlclient` is already properly referred by `wmagentpy3.spec`. Maybe during the first deployment attempt I messed up the `wmagentpy3` package versions compiled and uploaded in my repository. So I am removing this from the `py3-sqlalchemy.spec` file and we are ready to go now ... I think...

**Comment by amaltaro** [comment] 2021-05-20 16:08
Thanks for providing a swift fix to this issue, Todor.
It's been fixed with this cmsdist PR: https://github.com/cms-sw/cmsdist/pull/6926

@todor-ivanov shall we close it? If so, please go ahead.

**Comment by todor-ivanov** [comment] 2021-05-20 16:33
I think we are safe  to close it again. 
Thanks @amaltaro

**Closed by todor-ivanov** 2021-05-20 16:33 UTC
Labels: High Priority, New Feature, Python3

**Comment by amaltaro** [comment] 2021-05-20 17:49
@todor-ivanov can you please open a new issue where we should have a basic benchmark between the two MySQL drivers that we have (for the different python stack)? 

It's important to assess what the performance impact might be with this new library, to avoid surprises on the FNAL nodes.
I think I saw some script examples while I was googling for this.
