### ISSUE TITLE
reqmgr_workload_cache db and wmstats reporting wrong # events

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5486] opened 2014-11-24 21:40 UTC
It looks like reqmgr_workload_cache db documents sometimes report an incorrect number of TotalInputEvents, TotalInputLumis and I guess also TotalEstimatedJobs, as can be seen in this example:
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_TRK-TP2023HGCALGS-00001_00001_v0__141113_160840_557

I've seen this in testbed already but I guess I did not manage to easily reproduce it.
Taking a quick look at the code, it seems it's coming from here:
https://github.com/dmwm/WMCore/blob/master/src/couchapps/ReqMgr/updates/totalstats.js#L17

but to be honest, I have no idea where/what "req.query.input_events" goes here.

**Comment by julianbadillo** [comment] 2015-10-16 08:42
Some recent cases:
https://cms-logbook.cern.ch/elog/Workflow+processing/21867
The issue is the following, we get double TotalInputLumis and TotalInputEvents of the actual expected value (according to schema or input dataset).

**Comment by vlimant** [comment] 2015-10-16 09:03
Maybe a one line debug could be inserted here
https://github.com/dmwm/WMCore/blob/e810ce4ab489770a258f2b129b9da8c0fff235be/src/python/WMCore/WorkQueue/WorkQueue.py#L1048
and there
https://github.com/dmwm/WMCore/blob/5358025f419a299d3d4842b00167fd93e060d50b/src/python/WMCore/ReqMgr/Service/Request.py#L372
so that we could catch why the updated is called twice once in a while

**Comment by vlimant** [comment] 2015-10-16 10:13
could this be related to #6258 where two workload are concurrently being updated, one is updated twice (could expected lumi), the other none (missing members)

**Comment by ticoann** [comment] 2015-10-19 20:40
Just for my records,
If the update is successful here
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L1049
but failed somewhere in below in the try block, this could happen.
Next time, it is retried it will add the stats one more time. However, this doesn't explain how the total stats are missing (#6258).  - Need more investigation

**Comment by vlimant** [comment] 2015-12-03 21:57
new cases
https://cms-logbook.cern.ch/elog/Workflow+processing/22430
pdmvserv_HIG-Summer12pLHE-00498_00161_v0__151117_225132_9229
...
please reopen

**Comment by amaltaro** [comment] 2016-04-27 07:57
@vlimant do you have a workaround in Unified, or it has not happened anymore since Dec 2015?

**Comment by vlimant** [comment] 2016-04-27 08:15
I use max(lumi_fraction, event_fraction) and therefore do not see when this is happening anymore. it must still be happening if no further fix was added. we'd have to browse all for consistency check

**Comment by amaltaro** [comment] 2016-08-12 09:11
Ok, I think I just found one type of request which we can reproduce these issues. All these backfills cloned from the same request present twice the stats:
vlimant_TOP-RunIISummer16DR80-Backfill-00001_00001_v0__160807_165411_1343
vlimant_TOP-RunIISummer16DR80-Backfill-00001_00001_v0__160807_165425_8488
vlimant_TOP-RunIISummer16DR80-Backfill-00001_00001_v0__160807_165306_7975

**Comment by ticoann** [comment] 2016-08-12 14:45
Thanks Alan, I will investigate.

**Comment by ticoann** [comment] 2016-08-12 16:05
This is original workflow right?
vlimant_TOP-RunIISummer16DR80-00001_00001_v0__160802_141647_490

input events: 78949480
input lumis: 989998

So original data also reported twice more events?

**Comment by amaltaro** [comment] 2016-08-12 16:15
I think so. Hmm, perhaps the clone script is also uploading this key/value when cloning the request and then it's not uploaded afterwards?

@vlimant can you point us to the exact script you used to create these clones please?

**Comment by ticoann** [comment] 2016-08-12 16:33
It shouldn't be clone script. That numbers should be calculated by WQ and put them there.
Let me check which number it gives from workqueue call (which uses dbs call)  and I will compare with dbs call directly.

**Comment by ticoann** [comment] 2016-08-12 19:59
can we clone this workflow again and set the team name with none existing team so it will be stuck in GQ? I would like to investigate the WQ elements. (We can do this on testbed).

**Comment by vlimant** [comment] 2016-08-12 21:10
vlimant_TOP-RunIISummer16DR80-Backfill-00001_00001_v0__160812_230729_125 have fun

**Comment by ticoann** [comment] 2016-08-12 21:11
Thanks Jean-Roch

**Comment by ticoann** [comment] 2016-08-12 21:11
Just for the record. 
I ran the test with WQ function, it returns correct values.

{'input_lumis': 494999, 'input_num_files': 11165, 'input_events': 39474740, 'total_jobs': 13746.0}

Which means we all calling this twice somewhere.
Looking at the code, problem seems to be here.

When dataset is keep adding the block,  following is called to add new element.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L653

This will split again spec even if already exists.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L1071

If the element exist it will be ignored in insert procedure.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueue.py#L1076
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueueBackend.py#L148

but it is adding the new stat even for the existing elements.

I am not sure why it is only inserted twice though, It could be inserted multiple times.  Still need to investigate.

**Comment by vlimant** [comment] 2016-08-12 21:17
cannot seem to be able to assign to non-existing team. 500 error : very self explanatory ...

**Comment by amaltaro** [comment] 2016-08-12 21:44
Try assigning to `mc` team, there are no agents available but team exist.

**Comment by ticoann** [comment] 2016-08-18 13:15
I think Alan's guess was right. (looking at the original of original workflow it has the correct event, lumi, etc).

https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/pdmvserv_TOP-RunIISummer16DR80-00001_00001_v0__160802_024437_5970

The way algorithm works about updating total event, etc is following.

1. If the new workflow is assigned, when it creates WQE from workqueue inbox, it calls dbs and update the events, etc.
2. events are updated not inserted so if there is values from original workflow in cloned workflow, it will be added.
(The reason doing this is to support the following case.
Even if input dataset is not completed, WQ can start pulling the job periodically and update newly created blocks)

For a short term solution.

@vlimant, Jean-Roch, could you check clone script to remove following property from original workflow,

```
"TotalEstimatedJobs": 13746, 
"TotalInputEvents": 39474740,
"TotalInputLumis": 494999,
"TotalInputFiles": 11165,
```
We will have a proper solution in reqmgr/workqueue side.

**Comment by vlimant** [comment] 2016-08-22 12:51
Hi, we can live with the double counting until it's fixed at the source. thanks for tracking this down.

**Comment by ticoann** [comment] 2016-08-22 15:45
@vlimant Thank Jean-Roch, We will fix this for this deployment.
Could you confirm that cloning copies following params from existing original request? Just make sure whether it is the case.

```
"TotalEstimatedJobs": 13746, 
"TotalInputEvents": 39474740,
"TotalInputLumis": 494999,
"TotalInputFiles": 11165,
```

**Comment by vlimant** [comment] 2016-08-22 17:36
https://github.com/CMSCompOps/WmAgentScripts/blob/master/resubmit.py#L41 likely it does copy these values over.
While the recent wf showing this issue were clones, the ones initiating that GH issue are not, which makes me wonder if there isn't another source of this double counting

**Comment by ticoann** [comment] 2016-08-22 18:22
There is another case counting could mess up. (If workflow is running-open status, this case it wouldn't be just double counting. It could be more that that) - we will fix that case together. Anyway, if you have example which is not cloned workflow. Please give us a pointer. Thanks,

**Comment by vlimant** [comment] 2016-08-29 13:17
https://cmsweb.cern.ch/reqmgr/view/details/vlimant_TOP-RunIISummer16DR80-Backfill-00001_00001_v0__160812_230729_125 if you do not need it, can you please reject it ?

**Comment by amaltaro** [comment] 2016-10-07 13:05
@ticoann has this issue been fixed?

**Closed** 2018-01-12 03:46 UTC
Labels: Bug, Medium Priority
