### ISSUE TITLE
Keep record and address new bugs from MariaDB upgrade to 10.6.x

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10837] opened 2021-09-28 15:19 UTC
**Impact of the bug**
WMCore Jenkins and WMAgent

**Describe the bug**
Sub task of https://github.com/dmwm/WMCore/issues/9241

**How to reproduce it**
Jenkins will tell

**Expected behavior**
This issue is just a placeholder. Actual new issues with the MariaDB upgrade will have their own GH issue. We can of course link the new issues to this one though.
Once all the known issues have been resolved, this one can be closed as well and we can start considering upgrading WMAgents to this latest stable MariaDB version 10.6.x.

**Additional context and error message**
Dependent on Jenkins tests: https://github.com/dmwm/WMCore/issues/10836
and a sub-task of https://github.com/dmwm/WMCore/issues/9241

**Comment by amaltaro** [comment] 2021-12-16 09:05
For the record, these are the 2 new unit tests that failed in master/head last night:
```
WMCore_t.JobSplitting_t.RunBased_t.RunBasedTest.testMultipleRunsCombine
WMComponent_t.JobSubmitter_t.JobSubmitter_t.JobSubmitterTest.testB_thresholdTest
```

@goughes if you'd rather have a new GH issue to address those, please go ahead and replace this one by the two new issues.

**Comment by amaltaro** [comment] 2021-12-16 09:12
I forgot to mention that we have 12 new failures in python2 unit tests, they are:
```
WMCore_t.WMBS_t.JobSplitting_t.SizeBased_t.SizeBasedTest.testExactEvents
WMCore_t.ResourceControl_t.ResourceControl_t.ResourceControlTest.testInsertSite
WMCore_t.WMBS_t.JobSplitting_t.SiblingProcessingBased_t.SiblingProcessingBasedTest.testFilesWithoutOtherSubscriptions
WMComponent_t.JobSubmitter_t.JobSubmitterCaching_t.JobSubmitterCachingTest.testCaching
WMCore_t.WMBS_t.JobSplitting_t.RunBased_t.EventBasedTest.testMultipleRuns
WMCore_t.WMBS_t.JobSplitting_t.RunBased_t.EventBasedTest.testSingleRunsCombineUneven
WMCore_t.WMBS_t.JobSplitting_t.RunBased_t.EventBasedTest.testMoreRuns
WMCore_t.WMBS_t.JobSplitting_t.SizeBased_t.SizeBasedTest.testMultipleFiles
WMCore_t.WMBS_t.JobSplitting_t.SizeBased_t.SizeBasedTest.testMultipleFiles2500
WMComponent_t.JobSubmitter_t.JobSubmitter_t.JobSubmitterTest.testB_thresholdTest
WMCore_t.WMBS_t.JobSplitting_t.ParentlessMergeBySize_t.ParentlessMergeBySizeTest.testMinMergeSize1aNoRunMerge
WMCore_t.WMBS_t.JobSplitting_t.RunBased_t.EventBasedTest.testSingleRunsMultipleLumiCombineUneven
```

however, it looks like we are very soon going to stop supporting Python2 within WMCore, so I would suggest not to invest any effort on these.

**Comment by goughes** [comment] 2021-12-16 18:44
Sure, I will close this one out after I create the new issues. I have a 3rd as well, which I found when deploying my agent.

```
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'cmst1'@'localhost'
Installing WMAgent Database: wmagent
Checking Server connection...
Connection OK
Done!
```

`/data/srv/wmagent/v1.5.7.pre1/sw/slc7_amd64_gcc630/external/mariadb/10.6.5/scripts/mysql_install_db` now creates the `cmst1@localhost` account. This is due to the default authentication method being changed in 10.4. https://mariadb.com/kb/en/authentication-from-mariadb-104/ 

Now you can connect via the local socket file without a password by default. It might be worth considering removing passwords for the root and cmst1 accounts due to this. In fact, if you install an agent now, it never sets a password for the cmst1 account and everything still works. There are some good points in the link above about why setting a password doesn't make that much sense when connecting via localhost.

**Comment by goughes** [comment] 2022-01-14 19:25
I made this issue for `WMComponent_t.JobSubmitter_t.JobSubmitter_t.JobSubmitterTest.testB_thresholdTest`: https://github.com/dmwm/WMCore/issues/10953

For `WMCore_t.JobSplitting_t.RunBased_t.RunBasedTest.testMultipleRunsCombine`, it looks like that one is flapping for as long as Jenkins remembers. https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMAgentPy3-TestAll/SLICE=6,label=cms-dmwm-cc7/530/testReport/junit/WMCore_t.JobSplitting_t.RunBased_t/RunBasedTest/testMultipleRunsCombine/history/

 I just ran this same test with MariaDB 10.1.21 in an old container and was able to reproduce the inconsistent test results. Shall we leave that one alone then @amaltaro?

**Comment by amaltaro** [comment] 2022-01-31 20:31
@goughes Erik, if we have the remaining python3 issues tracked in a different GH issue, shall we close this one out?

**Comment by goughes** [comment] 2022-01-31 22:10
The remaining pieces are tracked in separate issues. I think we can close this out and open new issues is anything pops up when you deploy the remaining FNAL agents.

**Closed by goughes** 2022-01-31 22:10 UTC
Labels: BUG, ToDo, Medium Priority, Further Discussion, MariaDB
