### ISSUE TITLE
Evaluate WM payload timing for ReReco and TaskChain workflows

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11746] opened 2023-09-26 17:31 UTC
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
We have seen reports of CMS job inefficiencies, where it is said that WMAgent jobs can result in 2% of the overall inefficiency.
We should study production payload to have a better understanding of where time is actually spent and identify potential improvements.

**Describe the solution you'd like**
Study ReReco and TaskChain jobs - only Production/Processing jobs - and map steps executed by WMAgent, time spent in each and potentially identify areas of improvements.

The following setup needs to be evaluated:
* ReReco workflow
* TaskChain without input and pileup data
* TaskChain with input data (single pileup)
* TaskChain with input and pileup data 

**Describe alternatives you've considered**
Ideally we should use the latest WMAgent release (>= 2.2.4.x)

**Additional context**
None

**Comment by khurtado** [comment] 2023-11-27 17:27
@amaltaro @vkuznet Moving the question here

Here is the question I had with respect to time metrics.

What is the definition of the following metrics in a cmsRun step (not in the submit wrapper as a whole):

cmsRun1.WMCMSSWSubprocess.wallClockTime
cmsRun1.performance.cmssw.Timing.TotalJobTime
My understanding was that cmsRun1.performance.cmssw.Timing.TotalJobTime is what the CMSSW executable reports as the total job time, is this correct?
THen, for WMCMSSWSubprocess.wallClockTime, this is what the subprocess routine takes  and is recorded here:
https://github.com/dmwm/WMCore/blob/a3a2b0c6b90ee374d220c2af91242a4b65048e8d/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L321

Where the start and end times are coming from this part:
https://github.com/dmwm/WMCore/blob/a3a2b0c6b90ee374d220c2af91242a4b65048e8d/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L276-L292

So, in principle, the difference should not be much. This is what I see in most cases, but there are some when there is a e.g.: 30% difference. Does anyone undersdand why this could be?

Here is an example:

I have a report from JobArchiver:
/data/srv/wmagent/current/install/wmagentpy3/JobArchiver/logDir/p/pdmvserv_task_TOP-RunIISummer15wmLHEGS-00641__v1_T_231113_190859_2952/JobCluster_4081/Job_4081106.tar.bz2

That basically has the 2 following metrics in the report:

```
/data/cmst1-tmp/Job_4081106 $ python3
Python 3.8.2 (default, Jan 22 2021, 17:57:37)
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import WMCore
>>> import WMCore
>>> import pickle
>>> with open("Report.0.pkl","br") as f:
...     p = pickle.load(f)
...
>>> p.cmsRun1.WMCMSSWSubprocess.wallClockTime
155.0289249420166
>>> p.cmsRun1.performance.cmssw.Timing.TotalJobTime
111.003
```
So, the question is: Why are cmsRun1.WMCMSSWSubprocess.wallClockTime and cmsRun1.performance.cmssw.Timing.TotalJobTime so different in this case? If they are both from the same cmsRun step, I would expect both to be close, which is the case in most jobs, but not in many in this workflow.

The overall metrics I collected from that report are:

```
Report file: /data/srv/wmagent/current/install/wmagentpy3/JobArchiver/logDir/p/pdmvserv_task_TOP-RunIISummer15wmLHEGS-00641__v1_T_231113_190859_2952/JobCluster_4081/Job_4081106.tar.bz2
WMTimes collected: {'WM_wrapper': 225.0, 'cmsRun1': 218.3473665714264, 'cmsRun1--WMCMSSWSubprocess': 155.0289249420166, 'cmsRun1--TotalJobTime': 111.003, 'stageOut1': 2.7826619148254395, 'logArch1': 1.1762380599975586}
```

**Comment by vkuznet** [comment] 2023-11-27 17:50
Kenyi,
you are right in your observation, i.e. as 
WMCore/WMSpec/Steps/Executors/CMSSW.py#L321
call to self.report.updateSubprocessInfo(sysTime, userTime, startTime, endTime)
is calling update of CMSSW subprocess with times defined in
WMCore/WMSpec/Steps/Executors/CMSSW.py#L276-L292 

The difference you see may be explained in different way which depends on kind
of CMSSW subprocess. For example, if subprocess requires to fetch more data, or
generate new data, etc. Your confusion in fact comes from not understanding how
cmssw.Timing.TotalJobTime metrics is calculated. My understanding that it is
CPU total job time which in fact can be smaller than subprocess since the
CMSSW job may sit idle waiting for subprocess to finish its part.

Best,
Valentin.

On  0, Kenyi Hurtado ***@***.***> wrote:
>    ***@***.*** ***@***.*** Moving the question here
> 
>    Here is the question I had with respect to time metrics.
> 
>    What is the definition of the following metrics in a cmsRun step (not
>    in the submit wrapper as a whole):
> 
>    cmsRun1.WMCMSSWSubprocess.wallClockTime
>    cmsRun1.performance.cmssw.Timing.TotalJobTime
>    My understanding was that cmsRun1.performance.cmssw.Timing.TotalJobTime
>    is what the CMSSW executable reports as the total job time, is this
>    correct?
>    THen, for WMCMSSWSubprocess.wallClockTime, this is what the subprocess
>    routine takes and is recorded here:
>    [3]https://github.com/dmwm/WMCore/blob/a3a2b0c6b90ee374d220c2af91242a4b
>    65048e8d/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L321
> 
>    Where the start and end times are coming from this part:
>    [4]https://github.com/dmwm/WMCore/blob/a3a2b0c6b90ee374d220c2af91242a4b
>    65048e8d/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L276-L292
> 
>    So, in principle, the difference should not be much. This is what I see
>    in most cases, but there are some when there is a e.g.: 30% difference.
>    Does anyone undersdand why this could be?
> 
>    Here is an example:
> 

The difference you see may be explained in different way which depends on kind
of CMSSW subprocess. For example, if subprocess requires to fetch more data, or
generate new data, etc, it may be large then original job timing, since CMSSW
relies on concurrent execution of processes. In other words the parent process
can finish earlier then a child one.

**Comment by khurtado** [comment] 2023-11-27 18:02
@vkuznet Thank you for confirming! Since I saw a `TotalJobCPU`, I assumed that was the CPU time and `TotalJobTime` the wallclock time. `TotalJobCPU` is even bigger and I suppose it was accounting for the CPU time of all cores. I will try to find more information of how `TotalJobTime` is calculated, if you have a good reference for it, please let me know.

```
>>> p.cmsRun1.performance.cpu.TotalJobCPU
'477.772'
>>> p.cmsRun1.performance.cpu.TotalJobTime
'111.003'
```

**Comment by amaltaro** [comment] 2023-11-27 20:29
@khurtado I think the best person to ask about FJR performance metrics is either @makortel or @Dr15Jones . Given the apparent confusion in this - which I also share of - I'd suggest to materialize it and the WMCore performance metrics in a basic wiki.

**Comment by amaltaro** [comment] 2023-11-28 22:08
@makortel Matti, with this issue, we plan to study production jobs and categorize where time is spent in production jobs. We will of course focus on the WM side.

I tagged you because Kenyi has some questions about the CMSSW FJR performance metrics and I was wondering if those are documented anywhere? Such that Kenyi can also correlated CMSSW versus WMCore based performance metrics.
Kenyi can correct me if I am missing anything and or misunderstood the actual question.

**Comment by makortel** [comment] 2023-11-28 23:57
Thanks @amaltaro for the clarification. It seems to me the closest documentation is in https://twiki.cern.ch/twiki/bin/view/CMS/FrameworkJobReport (which doesn't really add much to what has been written here). In short,
* `TotalJobTime` is the wall clock time from the beginning of `main()` to end of `endJob` transition. It misses the wall clock time spent before `main()`, and in the shutdown of the framework (i.e. from end of `endJob` to the end of the process)
* `TotalJobCPU` is the total CPU time of all threads and child processes of the `cmsRun` process, up to the end of `endJob` transition.

I think you'd want to compare the WM-side wall clock time measurement to `TotalJobTime`, and CPU time measurement to `TotlaJobCPU`. As mentioned earlier in this issue, ideally these should be close to each other (with WM measurements being tiny bit larger), and cases where they are not would benefit from deeper investigation.

**Comment by khurtado** [comment] 2023-11-30 23:55
@makortel Thank you! I have added your definition in the following wiki, meant to address this github issue.

The link below provides some examples where the difference between `TotalJobTime` and the subprocess call wallclok time 
was not trivial for future further studies (the goal of this issue was to identify potential areas of improvement, not go deeper into each case, so I am just providing the tarballs with the reports, ES links for the jobs, etc, for future reference).

https://github.com/dmwm/WMCore/wiki/WM-payload-timings-on-different-workflow-types

@amaltaro I think I am done with the link above. If there is anything you think is missing, let me know, otherwise, I think I can close this ticket.

**Closed** 2023-12-01 15:13 UTC
Labels: New Feature, WMAgent, R&D

**Comment by amaltaro** [comment] 2023-12-01 21:34
Thank you very much, Kenyi! I planned to look into your thorough documentation today, but didn't manage to get to it. Hopefully I can give you some real feedback by Monday.

**Comment by amaltaro** [comment] 2023-12-02 11:09
After reading the wiki provided, here are some thoughts/questions and minor suggestions to the wiki content.

> Eff_cmsRun_vs_wrapper = TotalJobTime[cmsRun1] / WMCMSSWSubprocess[cmsRun1]

Perhaps you meant to call this metric something like `Eff_cmsRun_vs_subprocess`

> Efficiency of cmsRun subprocess wallclock time vs CmsRun step wallclock time

Do you understand the difference reported on this section? My understanding is that the subprocess timing does not include the CMSSW project bootstrap, neither any of the PSet tweaks. If that is correct, then shouldn't they be very close to each (diff of secs instead of min)?

> 'cmsRun1': 1819.545009613037, 'cmsRun1--WMCMSSWSubprocess': 1490.7139554023743, 'cmsRun1--TotalJobTime': 377.886

Kenyi, this is one of your TaskChain examples and I am afraid I do not understand what they report. I read it as:
* `cmsRun1`: total job time measured by the framework for the cmsRun step.
* `cmsRun1--WMCMSSWSubprocess`: total job time measured by WMAgent at the subprocess level for the cmsRun step
* `cmsRun1--TotalJobTime`: also the total job time measured by the framework for the cmsRun step(?) Shouldn't it be equal to the `cmsRun1` measurement?
Another question is, is there any difference between cmsRun total job time (TotalJobTime) and wallclocktime?

> Most of the 22% remaining jobs come from jobs that less than 200 seconds

"Most of the 22% remaining jobs come from jobs that ran for less than 200 seconds"

> Some RECO jobs were noted to also have lower efficiencies in TaskChain MC jobs. This was noticed when comparing the cmsRun step TotalJobTime vs the WMCMSSWSubprocess.

Similar to one of my points above. I guess I don't fully understand the definition of "cmsRun step TotalJobTime vs the WMCMSSWSubprocess". Shouldn't those be almost equal?

The conclusions section is pretty useful, thanks!

Some take away messages that I have from this analysis are:
* it would be beneficial to start monitoring time spent on the `stageOut1` and `logArch1` steps (I guess only for Production/Processing jobs). With this monitoring, we might find sites with degraded IO patterns.
* I think it would be useful as well to plot time spent in LogCollect and Cleanup jobs (maybe we already have it in one of the dashboards).

**Comment by khurtado** [comment] 2023-12-03 19:48
> Perhaps you meant to call this metric something like `Eff_cmsRun_vs_subprocess`
Yes! Fixed, thank you!

> > Efficiency of cmsRun subprocess wallclock time vs CmsRun step wallclock time
> Do you understand the difference reported on this section? My understanding is that the subprocess timing does not include the CMSSW project bootstrap, neither any of the PSet tweaks. If that is correct, then shouldn't they be very close to each (diff of secs instead of min)?

- TotalJobTime and subprocess wallclock time should be close, as neither of them include boostraping, pset tweaking, etc.
- cmsRun subprocess and cmsRun step wallclock time do not have to be close in deed, but seeing the fraction of time spent in the subprocess routine that executes cmsRun compared to everything done in the CMSSW executor does (again: pset tweaking, etc) is still useful, I believe.

> > 'cmsRun1': 1819.545009613037, 'cmsRun1--WMCMSSWSubprocess': 1490.7139554023743, 'cmsRun1--TotalJobTime': 377.886
> 
> Kenyi, this is one of your TaskChain examples and I am afraid I do not understand what they report. I read it as:
> 
> * `cmsRun1`: total job time measured by the framework for the cmsRun step.

This is the cmsRun1 step wallclock time as defined by the stop and start times in the ExecuteMaster. This is better defined here:
https://github.com/dmwm/WMCore/wiki/WM-payload-timings-on-different-workflow-types#step-wallclock-times

> * `cmsRun1--WMCMSSWSubprocess`: total job time measured by WMAgent at the subprocess level for the cmsRun step
Yes

> * `cmsRun1--TotalJobTime`: also the total job time measured by the framework for the cmsRun step(?) Shouldn't it be equal to the `cmsRun1` measurement?
No, because TotalJobTime only includes what cmsRun sees, while `cmsRun1` includes what we track from the CMSSW executor including pset tweaking, etc.


>   Another question is, is there any difference between cmsRun total job time (TotalJobTime) and wallclocktime?
TotalJobTime is wallclock time, measured by the CMSSW framework. The differences are commented below:
https://github.com/dmwm/WMCore/wiki/WM-payload-timings-on-different-workflow-types#cmsrun-times

> > Most of the 22% remaining jobs come from jobs that less than 200 seconds
> 
> "Most of the 22% remaining jobs come from jobs that ran for less than 200 seconds"

Fixed, thanks!

> > Some RECO jobs were noted to also have lower efficiencies in TaskChain MC jobs. This was noticed when comparing the cmsRun step TotalJobTime vs the WMCMSSWSubprocess.
> 
> Similar to one of my points above. I guess I don't fully understand the definition of "cmsRun step TotalJobTime vs the WMCMSSWSubprocess". Shouldn't those be almost equal?

TotalJobTime and WMCMSSWSubprocess should be almost equal, and they are most of the time, but sometimes they just don't and this requires investigation. This seems to happen in these set of RECO jobs specifically, but once every 100 jobs or so. Subprocess does some check routines, deals with the stream I/O data and other things in the [+2K lines of code](https://github.com/python/cpython/blob/3.12/Lib/subprocess.py) in python, so I guess it can become expensive in some particular times, but we don't know the details.

> 
> The conclusions section is pretty useful, thanks!
> 
> Some take away messages that I have from this analysis are:
> 
> * it would be beneficial to start monitoring time spent on the `stageOut1` and `logArch1` steps (I guess only for Production/Processing jobs). With this monitoring, we might find sites with degraded IO patterns.

Yes
> * I think it would be useful as well to plot time spent in LogCollect and Cleanup jobs (maybe we already have it in one of the dashboards).

Additionally, I think it would be useful to try to isolate one of these RECO jobs with large difference between TotalJobTime and Subprocess time and try to replicate this behavior for further study. Note the difference could be due to at least 2 different things:

1) Subprocess stuff going on (streams, check routines, multithreading handlding, etc?)
2) The other things CMSSW does before and after capturing the time for TotalJobTime: For instance, the wall clock time spent before their main() function, and in the shutdown of the framework (i.e. from end of endJob to the end of the process. E.g.: when [adding the TimeReport logs and creating the report summary](https://github.com/cms-sw/cmssw/blob/895df58e36cff1d7dc27b1bf37aee7f604adc704/FWCore/Services/plugins/Timing.cc#L498-L574) to the report)

**Comment by makortel** [comment] 2023-12-04 15:33
> Additionally, I think it would be useful to try to isolate one of these RECO jobs with large difference between TotalJobTime and Subprocess time and try to replicate this behavior for further study.

From past experience I don't have high hopes for the behavior to reproduce easily. I'd try first to investigate the logs of that kind of jobs.
