### ISSUE TITLE
Update CMSSW in the json templates

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8017] opened 2017-07-24 08:29 UTC
The following workflows are giving failures when ran on singularity nodes:
TaskChain_LumiMask_multiRun
ReDigi_AllFlag
ReDigi_cmsRun2
StepChain_ReDigi3
StepChain_LumiMask
ReDigi_cmsRun3
ReDigi_LumiMask

at least...

Just in case, the error is:
```
An exception of category 'PluginLibraryLoadError' occurred while
   [0] Constructing the EventProcessor
Exception Message:
unable to load /cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_2_0/lib/slc6_amd64_gcc481/pluginCondToolsHcalPlugin.so because libaio.so.1: cannot open shared object file: No such file or directory
```

which seems to be coming from an old bug in singularity/CMSSW that hasn't been backported to 7x releases.

**Comment by bbockelm** [comment] 2018-02-28 03:47
This is fixed.

It was due to an unlisted dependency (`libaio.so`) indirectly brought in via Oracle.  The dependency was reported by the T0 team, confirmed on the core framework mail list, then added to the container image we use for Singularity.

The T0 team confirmed the fix, so I'll preemptively close this one!

**Closed by bbockelm** 2018-02-28 03:47 UTC
Labels: Low Priority

**Comment by amaltaro** [comment] 2018-02-28 08:02
Thanks!
