### ISSUE TITLE
Request not going to completed

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7445] opened 2016-12-05 13:47 UTC
I came across https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_B2G-RunIISummer16DR80Premix-00791_00064_v0__161109_162829_9818 for example that has all WQE Done, but is not completed.
At least not from where I look
FYI @prozober

**Comment by amaltaro** [comment] 2016-12-05 15:16
I have the impression this is related to the reqmgr (one) problem.

The next cmsweb upgrade (tomorrow) should have a fix for this issue. If you cannot wait, then I'll talk to Seangchan, I think he came up with a script to get these workflows moving on.

**Comment by vlimant** [comment] 2016-12-05 15:20
if that can be fixed tomorrow, it is fine.

**Comment by ticoann** [comment] 2016-12-05 16:31
Actually, it seems it is different problem we had with reqmgr1. 
The problem was wq_inbox element (request) is deleted before it changed the request to complete status. Not completely sure how this happened, 
But it might be the case workflow is all finished (reported from wmagent by reqplication between following calls)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueueReqMgrInterface.py#L60
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WorkQueueReqMgrInterface.py#L66

That could happen. 
Anyway, I move the status manually and it is in completed status.
For the fix, instead of fixing this specific case, we are trying to change how the request status status is updated for complete. -archived status.

**Comment by jenimal** [comment] 2016-12-08 19:20
I found another 115 workflows from the EXO-RunIIWinter15pLHE camplaign that are stuck in running-closed:
https://cms-logbook.cern.ch/elog/Workflow+processing/25998

is this the same problem?  should I look for more?

**Comment by vlimant** [comment] 2016-12-08 19:37
@amaltaro @ticoann that's plenty of meat for debugging.

**Comment by ticoann** [comment] 2016-12-08 21:27
I didn't look at all the 115 workflows but it seems to be the same problem as above for the ones I looked at. I will investigate more.

**Comment by vlimant** [comment] 2016-12-09 14:43
Can you guys please do a magic to have them move along asap ?

**Comment by ticoann** [comment] 2016-12-09 15:48
Jean-Roch, I am testing the script to spot this and move the status. It should be done later today.

**Comment by ticoann** [comment] 2016-12-09 20:35
Total 122 requests are moved to completed. It seems the same problem as previous one. And I am pretty sure the cause is the race condition I mentioned above. We will create the patch for next deployment.

**Comment by vlimant** [comment] 2016-12-09 21:02
I see several of them moved to completed, good. thanks.

**Comment by vlimant** [comment] 2016-12-11 19:53
how often is that script running and at what time of the day ?

**Comment by areinsvo** [comment] 2016-12-12 14:48
I second Jean-Roch's question. There were still 18 workflows in this situation earlier today, according to Unified.
pdmvserv_B2G-RunIISummer16MiniAODv2-00718_00149_v0__161210_103438_4845 
pdmvserv_B2G-RunIISummer16MiniAODv2-00731_00151_v0__161211_040850_9428 
pdmvserv_EXO-RunIISummer16DR80Premix-00752_00041_v0__161108_113253_2634 
pdmvserv_EXO-RunIISummer16DR80Premix-01541_00094_v0__161111_123541_4509 
pdmvserv_EXO-RunIISummer16MiniAODv2-04004_00145_v0__161210_040350_6575 
pdmvserv_EXO-RunIISummer16MiniAODv2-04062_00151_v0__161211_044307_3581 
pdmvserv_EXO-RunIISummer16MiniAODv2-04071_00153_v0__161211_072819_5702 
pdmvserv_EXO-RunIIWinter15pLHE-03080_00230_v0__161207_163626_3099 
pdmvserv_EXO-RunIIWinter15pLHE-03085_00230_v0__161207_163701_3143 
pdmvserv_EXO-RunIIWinter15pLHE-03103_00231_v0__161207_163934_2197 
pdmvserv_EXO-RunIIWinter15pLHE-03104_00231_v0__161207_163948_3384 
pdmvserv_EXO-RunIIWinter15pLHE-03209_00234_v0__161207_165657_1098 
pdmvserv_EXO-RunIIWinter15pLHE-03233_00234_v0__161207_170117_6017 
pdmvserv_EXO-RunIIWinter15pLHE-03258_00235_v0__161207_170508_6235 
pdmvserv_EXO-RunIIWinter15pLHE-03296_00236_v0__161207_171058_1541 
pdmvserv_EXO-RunIIWinter15pLHE-03303_00236_v0__161207_171216_3522 
pdmvserv_EXO-RunIIWinter15pLHE-03327_00237_v0__161207_171614_407 
prozober_ACDC0_task_SMP-RunIISummer16DR80Premix-00062__v1_T_161212_100101_9808

**Comment by areinsvo** [comment] 2016-12-28 20:10
Did the patch for this get deployed? I'm still getting lots of Unified critical messages about workflows not moving to completed when they should. The workflows don't stay there very long, but I don't know if that's because @ticoann your script is running to keep them moving, or if they weren't really stuck to begin with.

**Comment by ticoann** [comment] 2016-12-28 21:31
@areinsvo, I am running cronjob in vocms049 every hour for this problem. So workflows with this problem should be moving. If there are workflow should be in completed status but not moving to completed for more than an hour,  please let me know (with the list of them).

**Comment by vlimant** [comment] 2016-12-28 21:46
@ticoann I don't think we want to track workflows like this by the hour, and we should not. So please find out how to fix it and we will live with it in the meantime. Workflow completely stuck in not completed will just be noticed late and make us look bad.
You can take a look at http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=critical&module=GQ&limit=100 for the most recent list of such workflows if you need to investigate.

**Comment by ticoann** [comment] 2016-12-29 00:08
@vlimant, I think there is a misunderstanding between us. What the script tracks is a particular case of the request.
If the request contains a small number of WQEs, it could fall into some race condition and resulting workqueue_inbox db element get deleted first before work_queue db gets deleted.
And those workflows won't be moved to completed. 
What script does it identify that and advance the status to completed. (This is temporary solution. Since next cmsweb update is February,  I thought we need some temporary solution, we will update real patch that time).

Also there are legit cases, there is always small time difference between WQ elements got deleted and status updated which gathers information by falling. 

Since the script only catches a particular case, I would like to check whether there is other stuck case. I will check the list above. 
Thanks,

**Comment by ticoann** [comment] 2016-12-29 04:41
The report below showing are all moved to completed. (How often this script is running?)

These 44 workflows have not toggled further to completed while all WQE are done 

http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=critical&module=GQ&limit=100

**Comment by vlimant** [comment] 2016-12-29 21:28
the module is ran in loop. It just keeps a trace of such and I could add a => completed if you think it is safe. But I'd rather have the full fix in Feb.

**Comment by ticoann** [comment] 2016-12-29 21:33
> the module is ran in loop

which module are you talking about? 

We will put the full fix in February.  But is current script causing any problem? Is United moving them to completed anyway? In that case I will disable that.

**Comment by ticoann** [comment] 2016-12-29 22:03
> "How often this script is running?" => the module is ran in loop

Ah, I meant how often periodically. Every hour? every minute?  Is that mean it is constantly running?

I shouldn't run constantly. It will give you too many false report since it is not instant update when WQ elements change to Done.  

We would add real fix in Feb. but the current script is still needed. Otherwise, we have to do manually move them.

If the 1 hour cycle is too long for the script running, I can make it to 30 min. The query is not so cheap to run. However it will be pretty safe, Iike I mentioned there shouldn't be many (only the case which has small number of WQE in a workflow)

**Comment by amaltaro** [comment] 2017-02-08 08:37
@vlimant is there anything else to be done for this issue? If not, can you close it please?

**Comment by vlimant** [comment] 2017-02-09 10:04
we still have quite a number of workflow that have not gone to completed.

http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=critical&module=GQ&limit=100

aren't we supposed to not have those anymore ?

**Comment by ticoann** [comment] 2017-02-09 15:18
Yes, it shouldn't happen. However, workflows are not instantly moved to completed. There is polling cycle every 10 min. So if you are checking this constantly in Unified it will show some uncompleted list always. 

I checked the list from the link. They are all completed now.   

Could you change this checking to sleep at least 20 min between the call? That was it will minimize false positive alarms. (Even then there should still be some false positive unless you compare previous result and current result.) Let me know if you think the issue is not still resolved.

**Comment by vlimant** [comment] 2017-02-10 10:25
fabozzi_Run2016C-23Sep2016-v1-FSQJets-03Feb2017_8026p1_170203_160332_4166 and  fabozzi_Run2016B-23Sep2016-v2-HighMultiplicity85EOF-03Feb2017_ver1_8026p1_170203_185211_6837  are not since a long time.
the check is effectively running every 3-5h, I'll think of a way to have an alert only on those there in the last cycle.

**Comment by amaltaro** [comment] 2017-02-10 12:44
Fix is created here: https://github.com/dmwm/WMCore/pull/7612
Now we need to follow up with the CMSWEB team to see how we proceed.

**Comment by vlimant** [comment] 2017-02-13 20:24
https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_ACDC0_Run2016C-23Sep2016-v1-FSQJets-03Feb2017_8026p1_170213_104343_3605 is still "assigned" with one WQE done. Should we move by hand to other status

**Comment by ticoann** [comment] 2017-02-13 20:32
I flip the Jobs size to 1. I should be picked up and make the state transition in 20 min. The fix Alan created is in testbed for testing. If everything goes well production reqmgr2 will be updated tomorrow.
Sorry for the inconvenience.

**Comment by amaltaro** [comment] 2017-02-13 20:35
Just a correction, if testbed is really fine, production upgrade will likely be on Wed.

**Comment by ticoann** [comment] 2017-02-15 17:38
I am closing this since this is updated in production today.

**Closed by ticoann** 2017-02-15 17:38 UTC
Labels: High Priority
