### ISSUE TITLE
ACDC with files = {}

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8832] opened 2018-09-27 19:07 UTC
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782%22&include_docs=true&reduce=false

has 

"doc":{"_id":"4efc3f02203a914a9cdc078e59a2f3cb","_rev":"1-6d49de84c2810c5cc4ae48cae383c82e","files":{},"collection_name":"vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782","collection_type":"ACDC.CollectionTypes.DataCollection","fileset_name":"/vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782/JME-RunIIFall17DRPremix-00009_1","timestamp":1533638961.6794159412}}

the files = {} is rather worrisome. The task that failed needs input, has an acdc, but no files to be used, and hence no location to be used ...

**Comment by amaltaro** [comment] 2018-09-28 06:46
I'm looking into this issue. Please keep that original workflow 
vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782

in the system a bit longer.

**Comment by amaltaro** [comment] 2018-09-28 08:52
Those are submitcooloff jobs. WMStats info for one of them as follows:
```
Job Name: 1459a8f6-ab48-454f-b61f-d722b0a00c63-10
WMBS job id: 2950412
Workflow: vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782
Task: /vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782/JME-RunIIFall17DRPremix-00009_1
Status: jobfailed
Input dataset: /QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RunIIFall17GS-93X_mc2017_realistic_v3-v2/GEN-SIM
Site: Unknown
Agent: vocms0253.cern.ch
ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
State Transition
submitcooloff: 2018/8/7 (Tue) 03:32:44 UTC, None
submitcooloff: 2018/8/7 (Tue) 03:37:12 UTC, None
submitcooloff: 2018/8/7 (Tue) 05:07:25 UTC, None
jobfailed: 2018/8/7 (Tue) 10:49:20 UTC, None
Exit code: 0
Retry count: 3
Errors:
Input files:
Lumis:
Output:
Worker Node:
log archive:
```

I found why there is no error reported (and the job actually had an exit code 0).
Now investigating why there are no files...

**Comment by amaltaro** [comment] 2018-09-28 09:47
And looking at the input ACDC collection for this workflow, from
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22pdmvserv_task_JME-RunIIFall17DRPremix-00009__v1_T_180307_174251_2241%22&include_docs=true&reduce=false

we can see things like:
```
"files":{"/store/unmerged/RunIIFall17DRPremix/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM-RAW/PU2017_94X_mc2017_realistic_v11-v1/100000/4A48D019-5B39-E811-9E33-0242AC1C0501.root":{"lfn":"/store/unmerged/RunIIFall17DRPremix/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM-RAW/PU2017_94X_mc2017_realistic_v11-v1/100000/4A48D019-5B39-E811-9E33-0242AC1C0501.root","locations":["T1_UK_RAL_ECHO_Disk"]
```

so another side effect of all that PNN transition that happened in RAL.

We have had a similar issue in the past and that got fixed in #8529 . I'm checking whether we can extend it to files without any location.

Just for the record, this is the job.pkl for the job id mentioned in the previous post:
```
>>> pprint(data)
{'agentName': 'vocms0253.cern.ch',
 'agentNumber': 3,
 'allowOpportunistic': False,
 'attachments': {},
 'cache_dir': u'/data/srv/wmagent/v1.1.14.patch5/install/wmagent/JobCreator/JobCache/vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782/JME-RunIIFall17DRPremix-00009_1/JobCollection_73865_0/job_2950412',
 'couch_record': None,
 'counter': 10000011,
 'custom': {},
 'estimatedDiskUsage': 10000000,
 'estimatedJobTime': 28800,
 'estimatedMemoryUsage': 20000,
 'fileLocations': set([]),
 'fwjr': None,
 'fwjr_path': None,
 'id': 2950412,
 'inputDataset': None,
 'inputDatasetLocations': [],
 'input_files': [{'avgEvtsPerLumi': 914.0,
                  'checksums': {},
                  'events': 22840,
                  'first_event': 0,
                  'id': 6897988,
                  'last_event': 0,
                  'lfn': '/store/unmerged/RunIIFall17DRPremix/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM-RAW/PU2017_94X_mc2017_realistic_v11-v1/100000/4A48D019-5B39-E811-9E33-0242AC1C0501.root',
                  'locations': set([]),
                  'lowestRun': <WMCore.DataStructs.Run.Run object at 0x7f939cddcb10>,
                  'lumiCount': 25,
                  'merged': True,
                  'minrun': 1,
                  'newlocations': set([]),
                  'parents': set([]),
                  'runs': [<WMCore.DataStructs.Run.Run object at 0x7f939cddcb10>],
                  'size': 52541945489},
                 {'avgEvtsPerLumi': 910.0,
                  'checksums': {},
                  'events': 3640,
                  'first_event': 0,
                  'id': 6898100,
                  'last_event': 0,
                  'lfn': '/store/unmerged/RunIIFall17DRPremix/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM-RAW/PU2017_94X_mc2017_realistic_v11-v1/100000/C03C714D-BC39-E811-98F7-0242AC1C0500.root',
                  'locations': set([]),
                  'lowestRun': <WMCore.DataStructs.Run.Run object at 0x7f93a5839350>,
                  'lumiCount': 4,
                  'merged': True,
                  'minrun': 1,
                  'newlocations': set([]),
                  'parents': set([]),
                  'runs': [<WMCore.DataStructs.Run.Run object at 0x7f93a5839350>],
                  'size': 8385586746},
                 {'avgEvtsPerLumi': 910.0,
                  'checksums': {},
                  'events': 10920,
                  'first_event': 0,
                  'id': 6898073,
                  'last_event': 0,
                  'lfn': '/store/unmerged/RunIIFall17DRPremix/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM-RAW/PU2017_94X_mc2017_realistic_v11-v1/100000/029DA9EC-373A-E811-A085-0242AC1C0500.root',
                  'locations': set([]),
                  'lowestRun': <WMCore.DataStructs.Run.Run object at 0x7f939cc4e9d0>,
                  'lumiCount': 12,
                  'merged': True,
                  'minrun': 1,
                  'newlocations': set([]),
                  'parents': set([]),
                  'runs': [<WMCore.DataStructs.Run.Run object at 0x7f939cc4e9d0>],
                  'size': 25116219843}],
 'jobType': 'Processing',
 'jobgroup': 73865,
 'location': None,
 'mask': {'FirstEvent': None,
          'FirstLumi': None,
          'FirstRun': None,
          'LastEvent': None,
          'LastLumi': None,
          'LastRun': None,
          'inclusivemask': True,
          'runAndLumis': {1: [[748, 752],
                              [881, 881],
                              [757, 760],
                              [6056, 6056],
                              [6053, 6055],
                              [16640, 16640]]}},
 'name': '1459a8f6-ab48-454f-b61f-d722b0a00c63-10',
 'numberOfCores': 8,
 'outcome': 'failure',
 'owner': 'pdmvserv',
 'ownerDN': '/DC=ch/DC=cern/OU=computers/CN=pdmvserv/vocms081.cern.ch',
 'ownerGroup': 'unknown',
 'ownerRole': 'unknown',
 'possiblePSN': set([]),
 'retry_count': 0,
 'sandbox': '/data/srv/wmagent/v1.1.14.patch5/install/wmagent/WorkQueueManager/cache/vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782/vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782-Sandbox.tar.bz2',
 'scramArch': ['slc6_amd64_gcc630'],
 'siteBlacklist': [],
 'siteWhitelist': [u'T1_DE_KIT',
                   u'T1_FR_CCIN2P3',
                   u'T1_UK_RAL',
                   u'T1_US_FNAL',
                   u'T2_UK_SGrid_RALPP',
                   u'T2_US_Vanderbilt',
                   u'T2_US_Wisconsin'],
 'spec': '/data/srv/wmagent/v1.1.14.patch5/install/wmagent/WorkQueueManager/cache/vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782/WMSandbox/WMWorkload.pkl',
 'state': 'new',
 'state_time': 1533612528,
 'swVersion': ['CMSSW_9_4_0_patch1'],
 'task': '/vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782/JME-RunIIFall17DRPremix-00009_1',
 'taskType': 'reprocessing',
 'workflow': 'vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782'}
>>> 

```

**Comment by amaltaro** [comment] 2018-10-02 21:49
And getting back to it. Picking one of the input files mentioned above, which has no locations, and looking for it at the ACDC collection for the original workflow:
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22pdmvserv_task_JME-RunIIFall17DRPremix-00009__v1_T_180307_174251_2241%22&include_docs=true&reduce=false

I could find this job failure:
```
{"id":"6953d143ea636e2ff517d89e6bb59a88","key":"pdmvserv_task_JME-RunIIFall17DRPremix-00009__v1_T_180307_174251_2241","value":{"_rev":"1-40e79ac4ca4ec5b075d3a404b4075565","_id":"6953d143ea636e2ff517d89e6bb59a88"},"doc":{"_id":"6953d143ea636e2ff517d89e6bb59a88","_rev":"1-40e79ac4ca4ec5b075d3a404b4075565","files":{"/store/unmerged/RunIIFall17DRPremix/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM-RAW/PU2017_94X_mc2017_realistic_v11-v1/100000/4A48D019-5B39-E811-9E33-0242AC1C0501.root":{"lfn":"/store/unmerged/RunIIFall17DRPremix/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM-RAW/PU2017_94X_mc2017_realistic_v11-v1/100000/4A48D019-5B39-E811-9E33-0242AC1C0501.root","locations":["T1_UK_RAL_ECHO_Disk"],"first_event":0,"checksums":{},"id":6914614,"size":52541945489,"runs":[{"run_number":1,"lumis":[745,746,747,793,794,795,796,801,802,803,804,869,870,871,872]}],"last_event":0,"parents":["/store/mc/RunIIFall17GS/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM/93X_mc2017_realistic_v3-v2/150003/22BA91DD-32B6-E711-8548-FA163EDB696D.root","/store/mc/RunIIFall17GS/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM/93X_mc2017_realistic_v3-v2/150003/D08088D3-49B6-E711-A770-FA163EAB4395.root","/store/mc/RunIIFall17GS/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM/93X_mc2017_realistic_v3-v2/150003/EA09EEB7-2FB6-E711-B897-FA163EBC4CD9.root","/store/mc/RunIIFall17GS/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM/93X_mc2017_realistic_v3-v2/150003/34FEADB4-2FB6-E711-B70C-02163E00AC57.root","/store/mc/RunIIFall17GS/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM/93X_mc2017_realistic_v3-v2/150003/E2F9BCB2-69B6-E711-8268-FA163EF04FEB.root","/store/mc/RunIIFall17GS/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM/93X_mc2017_realistic_v3-v2/150003/A2F7958F-32B6-E711-ADAE-02163E015E22.root","/store/mc/RunIIFall17GS/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/GEN-SIM/93X_mc2017_realistic_v3-v2/150003/865D219F-2FB6-E711-BD4C-FA163E086DDD.root"],"events":22840,"merged":0}},"collection_name":"pdmvserv_task_JME-RunIIFall17DRPremix-00009__v1_T_180307_174251_2241","collection_type":"ACDC.CollectionTypes.DataCollection","fileset_name":"/pdmvserv_task_JME-RunIIFall17DRPremix-00009__v1_T_180307_174251_2241/JME-RunIIFall17DRPremix-00009_0/JME-RunIIFall17DRPremix-00009_1","timestamp":1523637949.9140379429}},
```

so the location for that file was `T1_UK_RAL_ECHO_Disk`.

Looking at the ACDC workflow
https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_ACDC0_task_JME-RunIIFall17DRPremix-00009__v1_T_180807_034901_4782

it wasn't assigned with TrustSitelists, so I believe the GQE would actually not be pulled.
If it was, when the agent was running the wmbsPreparation code, it couldn't find the PNN id in the resource control for the ECHO_Disk endpoint and that's why it didn't create the wmbs_file_location entry.

That's my best bet. Given the lack of details, it's actually hard to find the root cause of this problem.

**Comment by ticoann** [comment] 2018-10-03 14:03
Thank you Alan for investigating. T1_UK_RAL_ECHO_Disk is valid PNN? Was it added after WMAgent location table is populated?

**Closed** 2018-10-03 20:43 UTC
Labels: High Priority
