### ISSUE TITLE
Some python libraries bypass the nscd cache for DNS queries and increse the load to the central DNS at CERN

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9435] opened 2019-11-25 20:34 UTC
**Impact of the bug**
All of the systems which need some communication which is not just by IP, but includes any kind of name resolution. The GlobalWorkqueue is basically generating the biggest pressure.

**Describe the bug**
It was a bug announced in a mail thread started by the http-group. Some of the central services generate increased traffic to the DNS at CERN. The biggest load comes from the GlobalWrokqueue when it has workflows to process. Some more details regarding our findings are pasted in the comments bellow. All of the cmsweb frontends and backends are running `nscd` as a caching service, which includes DNS cache too. `nscd` itself is developed based on libc and exposes its cache through a socket which should exist in: 
`/var/run/nscd/socket`
If the upper layer service/library in python is developed towards another c library and knows nothing about this socket, it simply cannot benefit from the DNS cache while making name resolutions and sends queries directly to the DNS. This is in total contrast with the behavior of a full system level DNS cache, like `named`, which affects how the system itself does the name resolution and always goes first through the cache then sends the queries to the DNS. The latter is not unfeasible solution, but we'd better try to fix the use of ncsd. The low level python module that is developed based on libc and is using the nscd cache correctly is `socket` [1]. So if a python library is using this one as an underlying interface it should be fine.

The current issue is created just to track the progress of the activities.       

[1]
https://docs.python.org/3/library/socket.html

**How to reproduce it**
Currently I am in the process of creating a test function to bypass the cache explicitly. For direct monitoring of the ill behavior a simple `tcpdump` for port 53 on any of the backends should be enough. 

**Expected behavior**
First use 
/var/run/nscd/socket
And then (if needed) open /etc/resolv.conf and send queries to the DNSs noted there.  

**Additional context and error message**

**Comment by vkuznet** [comment] 2019-11-25 21:04
Todor, why not to use direct IP addresses to avoid ANY DNS look-ups? How many URLs GlobalWorkqueu use? If it is only a few why not to change them to IPs?

**Comment by todor-ivanov** [comment] 2019-11-25 22:20
Hi Valentin. There is basically only one query that the services are doing. It is just for resolving cmsweb.cern.ch itself [1]. The problem if we start to use direct IPs will be that we need to reimplement the load-balance ourselves. Which in the current situation comes with the Round-robin DNS load balancing [2].

[1]
``` $ tcpdump -i any -nn port 53
...
19:44:34.829824 IP 188.184.66.147.50708 > 137.138.16.5.domain: 25660+ A? cmsweb.cern.ch. (32)
19:44:34.829909 IP 188.184.66.147.50708 > 137.138.16.5.domain: 42441+ AAAA? cmsweb.cern.ch. (32)
19:44:34.830172 IP 137.138.16.5.domain > 188.184.66.147.50708: 25660* 4/2/2 A 188.184.64.191, A 188.184.64.157, A 188.184.66.104, A 188.184.65.196 (174)
```

[2]
```$ dig cmsweb.cern.ch
...
;; ANSWER SECTION:
cmsweb.cern.ch.		60	IN	A	188.184.64.157
cmsweb.cern.ch.		60	IN	A	188.184.66.104
cmsweb.cern.ch.		60	IN	A	188.184.64.191
cmsweb.cern.ch.		60	IN	A	188.184.65.196
```

**Comment by todor-ivanov** [comment] 2019-11-25 22:51
The following comment is just for historical purposes. 

Here is how Muhammad and Lina tracked the process which was generating the load (Thanks for that):
```
stap -e 'probe netfilter.ip.local_out {
  if (dport == 53) # or parametrize
      printf("%s[%d] %s:%d\n", execname(), pid(), daddr, dport)
}' > traffic_detail

 [root@vocms0740 ~]# cat traffic_detail | sort | uniq -c
     50 nscd[3916] 137.138.16.5:53
      6 python[5563] 137.138.16.5:53
     22 python[5579] 137.138.16.5:53
     72 python[5595] 137.138.16.5:53
   6588 python[6100] 137.138.16.5:53
``` 

Here [2] is the `strace` of the one thread out of the 30 [1] python threads that was generating the load (the unneeded lines were truncated), and the interpretation is as follows:

[2] 99 -  a communication start with opening the service certificate

What should have happened next is to open /var/db/nscd/socket and read the cached
record for cmsweb.cern.ch from there, but what happens instead is:

[2] 101 - it opens /etc/resolv.conf
[2] 108 - reads the sequence at which the resources should be used for hostnames to ip addresses resolution
[2] 155 - creates a socket for connecting to the DNS
[2] 156 - sends the request
[2] 166 - receives the reply
[2] 172 - opens another socket for connecting to ipv6: 2001:1458:201:a4::100:262 at port 443
Which btw happens to be vocms0164.cern.ch - one of the frontends of cmsweb.cern.ch
[2] 258 - starts the communication between vocms0740.cern.ch <--> vocms0164.cern.ch
[2] 746 - the socket is closed
[2] 751 - a new iteration starts



[1]
```
[root@vocms0740 strace]# ps auxH -T |grep -e "^USER" -e workqueu
 ...
_workqu+  6100  6782  0.0  0.8 4074448 534404 ?      Sl   Nov05   0:00 python /data/srv/beHG1911c/...workqueue/1.2.8.pre3/...
_workqu+  6100  6882  8.6  0.8 4074448 534404 ?      Sl   Nov05 1924:21 python /data/srv/beHG1911c/...workqueue/1.2.8.pre3/...
_workqu+  6100  6885 11.1  0.8 4074448 534404 ?      Sl   Nov05 2481:26 python /data/srv/beHG1911c/...workqueue/1.2.8.pre3/...

```
[2]
```
...
99 stat("/data/srv/current/auth/workqueue/dmwm-service-cert.pem", {st_mode=S_IFREG|0440, st_size=2870, ...}) = 0
...
101 open("/etc/resolv.conf", O_RDONLY)      = 12
108 open("/etc/nsswitch.conf", O_RDONLY)    = 12
...
155 connect(12, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("137.138.16.5")}, 16) = 0
156 sendto(12, "\273x\1\0\0\1\0\0\0\0\0\0\6cmsweb\4cern\2ch\0\0\1\0\1", 32, MSG_NOSIGNAL, NULL, 0) = 32
...
166 recvfrom(12, "\273x\205\200\0\1\0\4\0\2\0\2\6cmsweb\4cern\2ch\0\0\1\0\1"..., 4097, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("137.138.16.5")}, [16]) = 174
...
172 connect(12, {sa_family=AF_INET6, sin6_port=htons(443), inet_pton(AF_INET6, "2001:1458:201:a4::100:262", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EINPROGRESS (Operation now in progress)
...
258 write(12, "\26\3\1\2\0\1\0\1\374\3\3\364\243\343\260\36p\25\3143\306\346\357\24\\D\315\251\372\37\326\r"..., 517) = 517
...
746 close(12)
...
751 stat("/data/srv/current/auth/workqueue/dmwm-service-cert.pem", {st_mode=S_IFREG|0440, st_size=2870, ...}) = 0
```

**Comment by bbockelm** [comment] 2019-11-26 02:23
It'd be a bit ... esoteric for Python libraries to include their own DNS resolver.  Not saying it's impossible, but would be quite surprising.

Other possibilities include:
- Can glibc stop using nscd if there are too many errors?  Does GQ continue to query DNS directly if restarted?  (N.b. - `nscd` has a pretty lousy reputation for errors and lockups.  Is `sssd` an option?)
- `curl` can optionally be compiled with the `c-ares` backend which includes an asynchronous DNS resolver that will bypass the system cache.  However, all uses of `libcurl` would see this.

**Comment by todor-ivanov** [comment] 2019-11-26 03:52
Not saying that python libraries are building their own mechanism for DNS caching, It is simply that they may ignore the nscd socket on the go. And indeed, `pycurl` is our major suspect here. Not yet proven though, but I am heading in that direction. The other one that is mostly used for communication around is urllib3, which from this post [1], I conclude is already using the underlying `socket` module from python. And I tested this module  - it does call `/var/run/nscd/socket`, before anything else. So I believe urllib3 is out of the picture for the moment. 

[1]
https://github.com/urllib3/urllib3/issues/925
https://github.com/urllib3/urllib3/blob/e4e49128ac68e4b56e20482cd2bef1700ff30fd9/urllib3/util/connection.py#L75

**Comment by vkuznet** [comment] 2019-11-26 12:43
Todor,
I understand the desire to figure this out, but at the end this simple code can solve all the issues:
```
import socket
import random

def host_ips(host, port):
    "Return IP addresses from provide host name and port number"
    addr = set()
    for item in socket.getaddrinfo(host, int(port)):
        # each item is (family, socktype, proto, canonname, sockaddr) tuple
        # so we tack 4th element sockaddr
        # for IPv4 sockaddr is (address, port)
        # for IPv6 sockaddr is (address, port, flow info, scope id)
        # we are interested only in address
        addr.add(item[4][0])
    return list(addr)

ips = host_ips('cmsweb.cern.ch', 443)
# get random IP
idx = random.randint(0, len(ips)-1)
srv = ips[idx]
print(srv)
```
You can wrap it further if you want into single function which will return random IP for the host/port pair. And of course IPs can be cached for as long as you want. This solution does not require any tweaking with dependency stack which may be not trivial at the end.

**Comment by bbockelm** [comment] 2019-11-26 12:52
> This solution does not require any tweaking with dependency stack which may be not trivial at the end.

Except you break things like TLS, right?  Host certificates use hostnames and not IP addresses.

Writing one's own DNS resolver and caching inside python seems a harrowingly bad idea, especially you have to break into every layer of the stack and find what dependencies are lurking on hostnames.  This is an incredibly tricky layer.

> It is simply that they may ignore the nscd socket on the go.

That's not possible unless they're writing their own DNS resolver, which seems unlikely.  Skipping or not skipping the NSCD socket is something only glibc can decide to do.

You can check `pycurl` by simply seeing which `libcurl` you compiled against and what backend it is loading.

**Comment by vkuznet** [comment] 2019-11-26 13:28
Brian,
TLS is a very good point and I didn't think from this angle.

**Comment by amaltaro** [comment] 2019-11-28 07:55
In case it helps:
```
>>> pycurl.version
'PycURL/7.19.3 libcurl/7.35.0 OpenSSL/1.0.1r zlib/1.2.8 c-ares/1.10.0'
```

so that's a ~6 years old version of the pycurl library. Thus I'd suggest to:
* first, create a snippet/gist such that we can easily reproduce this problem
* then, work on the pycurl spec (the py3 too) and bring it to the latest stable release:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py2-pycurl.spec

Given that that's going to be a quite wide change, we ought to wait until beginning of January to push these changes in in CMSWEB. A bunch of services rely on the pycurl library, including CRAB and DBS @belforte @yuyiguo

**Comment by belforte** [comment] 2019-11-30 04:42
I have no objection to updating pycurl, of course. It is indeed important to be up to date on all those things and be able up update "routinely". Let's hope we do not end like with sqlalchemy ! 
But from what I read here it is not clear to me if the origin of the problem is fully understood and hence if a pycurl update will fix it.  I fully agree with not writing our own resolver+DNS-casher.

**Comment by bbockelm** [comment] 2019-11-30 19:09
Note that `c-ares` is a DNS resolver that is an optional plugin to `libcurl`. Using that is guaranteed to bypass the system C library.  I think Alan found our culprit.

**Comment by todor-ivanov** [comment] 2019-12-03 07:57
Here is how I reproduce it [1]. In the doc string there are few lines of instructions how to run and trace this simple script. The use of either the broken versions of libraries from cms repository or the native OS installed pycurl/libcurl versions is controlled by this variable [2]. The behavior of these both cases is pasted in [3].

[1]
https://github.com/todor-ivanov/auxiliary/blob/master/tests/testPycurl.py

[2]
https://github.com/todor-ivanov/auxiliary/blob/master/tests/testPycurl.py#L52

[3]
With useExternals=True:
> pycurl version: PycURL/7.19.3 libcurl/7.35.0 OpenSSL/1.0.1r zlib/1.2.8 c-ares/1.10.0
And the strace is a one to one repetition of what I was observing in vocms0740

With useExternals=False:
> pycurl version: PycURL/7.43.0 libcurl/7.52.1 GnuTLS/3.5.8 zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3

And the strace clearly shows that the cmsweb-testbed.cern.ch was fetched from 'nscd':
...
[pid 12538] socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
[pid 12538] connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = 0
[pid 12538] sendto(3, "\2\0\0\0\16\0\0\0\27\0\0\0cmsweb-testbed.cern."..., 35, MSG_NOSIGNAL, NULL, 0) = 35
...

**Comment by todor-ivanov** [comment] 2019-12-18 16:34
Upgrading the pycurl library to the latest version and recompiling libcurl without the c-ares flag solves the problem. Here [1] is the commit to cmsdist that does the job. And here is the system trace that shows that shows that the name 'cmsweb-testbed.cern.ch' was actually resolved from the nscd cache.

[1]
https://github.com/cms-sw/cmsdist/pull/5420

[2]
```
========================================================================                                                                             
pycurl version: PycURL/7.43.0.3 libcurl/7.35.0 OpenSSL/1.0.1r zlib/1.2.8   
========================================================================
...
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3                                                                                                                                                                                                                    
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = 0                                                                                                                                                                                                         
sendto(3, "\2\0\0\0\16\0\0\0\27\0\0\0cmsweb-testbed.cern."..., 35, MSG_NOSIGNAL, NULL, 0) = 35                                                                                                                                                                                     
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 1 ([{fd=3, revents=POLLIN|POLLHUP}])                                                                                                                                                                                      
read(3, "\2\0\0\0\1\0\0\0\2\0\0\0\10\0\0\0\27\0\0\0\0\0\0\0", 24) = 24                                                                                                                                                                                                            
read(3, "\274\270B\372\274\270@\232\2\2cmsweb-testbed.cern.ch"..., 33) = 33                                                                                                                                                                                                       
close(3)                                = 0                                                           
...
```

**Comment by amaltaro** [comment] 2020-01-26 21:38
Fixed with a new version of pycurl/curl and the removal of c-ares: https://github.com/cms-sw/cmsdist/pull/5438
closing

**Closed by amaltaro** 2020-01-26 21:38 UTC
Labels: BUG, Medium Priority, ReqMgr, ReqMgr2, WorkQueue
