### ISSUE TITLE
Merge ACDC over xrootd

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7469] opened 2016-12-13 17:16 UTC
This was a very useful feature to speed things along during data reprocessing and will speed things up in several cases for MC. Please put this back in production.

**Comment by amaltaro** [comment] 2016-12-13 18:04
You meant, ACDC for Merge jobs over xrootd

**Comment by vlimant** [comment] 2016-12-14 10:18
yes, very likely.

**Comment by prozober** [comment] 2017-02-07 15:32
Hi guys. This is not really working.
I made an ACDC for a merge task over xrootd https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_ACDC0_SUS-RunIISpring16FSPremix-00083_00047_v0__170130_100809_6783.
If you check the JSON file in reqMgr2 you will see:
> "TrustSitelists": true, 

But, when you go through the workqueue elements you see:
> "NoInputUpdate":false

https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/element/5f406e198e545ffc7cfd703199c426e2

We got many ACDCs sitting in acquired, could you please help us to understand what is going on?
PD: The ACDC was created and assigned using the WMAgentScripts.

**Comment by vlimant** [comment] 2017-02-09 09:58
@ticoann @amaltaro shall we reopen an issue or something ? is this expected ?
we would rather have these ACDC not dangling around with doomed configuration.

**Comment by amaltaro** [comment] 2017-02-09 15:41
Hmm, I've just created a merge ACDC in testbed and I see both flags enabled in the workqueue element:
https://cmsweb-testbed.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/element/c4eb4e671f74da909c7ca7aaedf88f1a

investigating, but I think it may be the create x assign issue...

**Comment by amaltaro** [comment] 2017-02-09 15:44
@prozober can you abort one of these ACDCs and create it again? These are old enough to make it very hard to find the reqmgr logs.

**Comment by prozober** [comment] 2017-02-10 07:52
Alan, I created the ACDC once again https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_ACDC0_SUS-RunIISpring16FSPremix-00083_00047_v0__170210_085036_9266.

**Comment by amaltaro** [comment] 2017-02-10 09:09
Paola, it looks good now:
"NoPileupUpdate":false,
"NoInputUpdate":true,

perhaps you were using an outdated script (or this issue was in cmsweb since December and nobody noticed?).

Anyways, if you're happy, close the issue please.

**Comment by prozober** [comment] 2017-02-10 10:59
That's crazy, I always use the updated scripts. I had five ACDCs with the same problem, but, as the related sites are enabled now, I just aborted them and did regular ACDCs.
If I need to do this once again, and I find the same problem, I will let you know.

**Comment by vlimant** [comment] 2017-02-23 14:48
should've - could've @amaltaro ... @prozober we have to get to understand how you are assigning these acdc and what is going wrong with them

**Comment by prozober** [comment] 2017-02-23 14:55
Hi guys, we had this merge ACDC in trouble.
https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_ACDC0_task_SUS-RunIISummer16DR80Premix-00135__v1_T_170206_103530_4262
As you can see in the JSON section 
`  "TrustSitelists": true, `
But in here 
https://cmsweb.cern.ch/reqmgr2/config?name=prozober_ACDC0_task_SUS-RunIISummer16DR80Premix-00135__v1_T_170206_103530_4262
There is none `sites.trustlists = True`

We are using this script for the assignment https://github.com/CMSCompOps/WmAgentScripts/blob/master/assign.py

**Comment by vlimant** [comment] 2017-03-02 15:19
@ticoann that's the GH we are discussing

**Comment by ticoann** [comment] 2017-03-02 15:21
Thanks. I will check.

**Comment by amaltaro** [comment] 2017-03-02 21:46
The last time I checked it (current production version), it was working without any issues.
If this is still happening, please point us to a fresh ACDC workflow (those above were made before the current cmsweb version).

**Comment by vlimant** [comment] 2017-03-31 12:21
are we having an issue with https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_ACDC0_task_HIG-RunIISummer15GS-02106__v1_T_170323_095110_8480 ?

**Comment by vlimant** [comment] 2017-04-03 07:23
@ticoann @amaltaro  ping !

**Comment by vlimant** [comment] 2017-04-03 07:24
@prozober can you please redo the ACDC and re-assign it so that we move on. Leave the broken ACDC as is

**Comment by amaltaro** [comment] 2017-04-03 08:43
I looked at the ReqMgr2 logs and I couldn't find anything wrong with the creation nor with the assignment. Just in case, creation log in vocms0165
```
[23/Mar/2017:09:51:11]  INFO: Create request, input args: {u'PrepID': u'task_HIG-RunIISummer15GS-02106', u'MaxMergeEvents': 200000, u'Requestor': 'prozober', 'IgnoredOutputModules': [], u'CustodialGroup': 'DataOps', u'DQMUploadUrl': 'https://cmsweb.cern.ch/dqm/dev', u'SubRequestType': 'ReDigi', u'OpenRunningTimeout': 0, u'LumiList': {}, u'DashboardHost': 'cms-jobmon.cern.ch', u'EnableHarvesting': False, u'BlockCloseMaxWaitTime': 172800, 'SiteWhitelist': [], u'BlockCloseMaxSize': 5000000000000, u'DQMConfigCacheID': None, u'ValidStatus': 'PRODUCTION', u'Campaign': u'RunIISummer15GS', u'GlobalTag': '80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'Multicore': 1, u'NonCustodialGroup': 'DataOps', 'ReqMgr2Only': True, u'ACDCServer': 'https://cmsweb.cern.ch/couchdb', u'SizePerEvent': 60, u'ConfigCacheID': None, u'Task1': {u'PrepID': 'HIG-RunIISummer15GS-02106', u'ProcessingString': 'MCRUN2_71_V1', u'ScramArch': [u'slc6_amd64_gcc481'], u'SizePerEvent': 498, u'ConfigCacheID': 'c0d9a22e125b9a54bf6f31d8713411cc', u'Memory': 2300, u'TimePerEvent': 32.5581, u'AcquisitionEra': 'RunIISummer15GS', u'PrimaryDataset': 'MSSMbbA-HiggsToMuMu_MA-300_Tanb-30_13TeV_pythia8', u'CMSSWVersion': 'CMSSW_7_1_25_patch3', u'SiteWhitelist': [], u'SplittingAlgo': 'EventBased', u'LheInputFiles': False, u'TaskName': 'HIG-RunIISummer15GS-02106_0', u'KeepOutput': True, u'Campaign': 'RunIISummer15GS', u'GlobalTag': 'MCRUN2_71_V1::All', u'FilterEfficiency': 1, u'Multicore': 1, u'RequestNumEvents': 10000, u'SiteBlacklist': [], u'EventsPerLumi': 100, u'Seeding': 'AutomaticSeeding'}, u'Task2': {u'PrepID': 'HIG-RunIISummer16DR80Premix-02515', u'ProcessingString': 'PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'ScramArch': [u'slc6_amd64_gcc530'], u'SizePerEvent': 3500, u'ConfigCacheID': '897f38412bc34c2c839ecfda1ec4356d', u'Memory': 5900, u'MCPileup': '/Neutrino_E-10_gun/RunIISpring15PrePremix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v2-v2/GEN-SIM-DIGI-RAW', u'TimePerEvent': 35, u'AcquisitionEra': 'RunIISummer16DR80Premix', u'PrimaryDataset': 'MSSMbbA-HiggsToMuMu_MA-300_Tanb-30_13TeV_pythia8', u'CMSSWVersion': 'CMSSW_8_0_21', u'SiteWhitelist': [], u'SplittingAlgo': 'EventAwareLumiBased', u'InputTask': 'HIG-RunIISummer15GS-02106_0', u'TaskName': 'HIG-RunIISummer16DR80Premix-02515_0', u'KeepOutput': False, u'GlobalTag': '80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'InputFromOutputModule': 'RAWSIMoutput', u'FilterEfficiency': 1, u'Multicore': 4, u'SiteBlacklist': [], u'Campaign': 'RunIISummer16DR80Premix'}, u'Task3': {u'PrepID': 'HIG-RunIISummer16DR80Premix-02515', u'ProcessingString': 'PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'ScramArch': [u'slc6_amd64_gcc530'], u'SizePerEvent': 3500, u'ConfigCacheID': '897f38412bc34c2c839ecfda1ec4c5d0', u'Memory': 5900, u'MCPileup': '/Neutrino_E-10_gun/RunIISpring15PrePremix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v2-v2/GEN-SIM-DIGI-RAW', u'TimePerEvent': 35, u'AcquisitionEra': 'RunIISummer16DR80Premix', u'PrimaryDataset': 'MSSMbbA-HiggsToMuMu_MA-300_Tanb-30_13TeV_pythia8', u'CMSSWVersion': 'CMSSW_8_0_21', u'SiteWhitelist': [], u'SplittingAlgo': 'EventAwareLumiBased', u'InputTask': 'HIG-RunIISummer16DR80Premix-02515_0', u'TaskName': 'HIG-RunIISummer16DR80Premix-02515_1', u'KeepOutput': True, u'GlobalTag': '80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'InputFromOutputModule': 'PREMIXRAWoutput', u'FilterEfficiency': 1, u'Multicore': 4, u'SiteBlacklist': [], u'Campaign': 'RunIISummer16DR80Premix'}, u'Task4': {u'KeepOutput': True, u'PrepID': 'HIG-RunIISummer16MiniAODv2-02531', u'InputFromOutputModule': 'AODSIMoutput', u'GlobalTag': '80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'SiteWhitelist': [], u'ProcessingString': 'PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'Memory': 5900, u'TimePerEvent': 1.5, u'FilterEfficiency': 1, u'SplittingAlgo': 'EventAwareLumiBased', u'InputTask': 'HIG-RunIISummer16DR80Premix-02515_1', u'ScramArch': [u'slc6_amd64_gcc530'], u'SizePerEvent': 60, u'ConfigCacheID': '897f38412bc34c2c839ecfda1ecbf4a0', u'SiteBlacklist': [], u'Multicore': 4, u'TaskName': 'HIG-RunIISummer16MiniAODv2-02531_0', u'AcquisitionEra': 'RunIISummer16MiniAODv2', u'PrimaryDataset': 'MSSMbbA-HiggsToMuMu_MA-300_Tanb-30_13TeV_pythia8', u'Campaign': 'RunIISummer16MiniAODv2', u'CMSSWVersion': 'CMSSW_8_0_21'}, u'MergedLFNBase': '/store/mc', 'CouchDBName': 'reqmgr_config_cache', u'InitialPriority': 900000, u'RobustMerge': True, u'AllowOpportunistic': False, u'DQMHarvestUnit': 'byRun', u'AutoApproveSubscriptionSites': [u'T1_US_FNAL_Disk'], u'RequestWorkflow': u'https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/prozober_ACDC0_task_HIG-RunIISummer15GS-02106__v1_T_170323_095110_8480/spec', u'BlockBlacklist': [], u'BlockCloseMaxFiles': 500, u'VoGroup': 'unknown', u'DashboardPort': 8884, u'DbsUrl': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader/', 'SiteBlacklist': [], u'TaskChain': 4, u'FirstLumi': 1, u'Group': u'ppd', u'BlockCloseMaxEvents': 2000000, u'CustodialSites': [], u'ProcessingString': {u'HIG-RunIISummer16MiniAODv2-02531_0': 'PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'HIG-RunIISummer16DR80Premix-02515_1': 'PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'HIG-RunIISummer16DR80Premix-02515_0': 'PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'HIG-RunIISummer15GS-02106_0': 'MCRUN2_71_V1'}, u'ScramArch': [u'slc6_amd64_gcc530'], u'UnmergedLFNBase': '/store/unmerged', u'RequestType': 'Resubmission', u'TimePerEvent': 1.5, u'DQMSequences': [], u'OutputModulesLFNBases': [u'/store/unmerged/RunIISummer15GS/MSSMbbA-HiggsToMuMu_MA-300_Tanb-30_13TeV_pythia8/GEN-SIM/MCRUN2_71_V1-v1'], 'OutputDatasets': ['/MSSMbbA-HiggsToMuMu_MA-300_Tanb-30_13TeV_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM'], u'NonCustodialSubType': 'Replica', u'InitialTaskPath': '/pdmvserv_task_HIG-RunIISummer15GS-02106__v1_T_170316_212027_6155/HIG-RunIISummer15GS-02106_0/HIG-RunIISummer15GS-02106_0MergeRAWSIMoutput/HIG-RunIISummer16DR80Premix-02515_0/HIG-RunIISummer16DR80Premix-02515_1/HIG-RunIISummer16DR80Premix-02515_1MergeAODSIMoutput/HIG-RunIISummer16MiniAODv2-02531_0/HIG-RunIISummer16MiniAODv2-02531_0MergeMINIAODSIMoutput', u'GlobalTagConnect': None, u'MaxMergeSize': 4294967296, u'OverrideCatalog': None, u'PeriodicHarvestInterval': 0, u'RequestString': u'ACDC0_task_HIG-RunIISummer15GS-02106__v1_T', 'RequestorDN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=prozober/CN=786128/CN=Paola Katherine Rozo Bernal', 'RequestDate': [2017, 3, 23, 8, 51, 10], u'inputMode': 'couchDB', u'SubscriptionPriority': 'Low', u'EventStreams': None, u'Memory': 5900, u'IncludeParents': False, u'BlockWhitelist': [], 'OriginalRequestCouchURL': 'https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache', u'RunNumber': 0, u'AcquisitionEra': {u'HIG-RunIISummer16MiniAODv2-02531_0': 'RunIISummer16MiniAODv2', u'HIG-RunIISummer16DR80Premix-02515_1': 'RunIISummer16DR80Premix', u'HIG-RunIISummer16DR80Premix-02515_0': 'RunIISummer16DR80Premix', u'HIG-RunIISummer15GS-02106_0': 'RunIISummer15GS'}, u'CMSSWVersion': u'CMSSW_8_0_21', u'NonCustodialSites': [u'T1_US_FNAL_Disk'], 'CollectionName': None, u'MinMergeSize': 2147483648, u'RequestPriority': 900000, u'ProcessingVersion': 1, u'FirstEvent': 1, 'RequestName': u'prozober_ACDC0_task_HIG-RunIISummer15GS-02106__v1_T_170323_095110_8480', u'CustodialSubType': 'Replica', 'CouchURL': 'https://cmsweb.cern.ch/couchdb', 'CouchWorkloadDBName': 'reqmgr_workload_cache', u'OriginalRequestName': u'pdmvserv_task_HIG-RunIISummer15GS-02106__v1_T_170316_212027_6155', 'RequestTransition': [{'Status': 'new', 'DN': u'/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=prozober/CN=786128/CN=Paola Katherine Rozo Bernal', 'UpdateTime': 1490259070}], 'RequestStatus': 'new', u'ACDCDatabase': 'acdcserver', u'DQMUploadProxy': None, 'SoftwareVersions': [u'CMSSW_8_0_21'], u'ConfigCacheUrl': 'https://cmsweb.cern.ch/couchdb'} ...
```

and assignment log in vocms0161
```
[23/Mar/2017:10:04:36]  INFO: Assign request prozober_ACDC0_task_HIG-RunIISummer15GS-02106__v1_T_170323_095110_8480, input args: {u'SoftTimeout': 159600, u'BlockCloseMaxEvents': 2000000, u'MaxMergeEvents': 200000, u'CustodialSites': [], u'MaxRSS': 6041600, u'ProcessingString': {u'HIG-RunIISummer16MiniAODv2-02531_0': u'PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'HIG-RunIISummer16DR80Premix-02515_1': u'PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6', u'HIG-RunIISummer15GS-02106_0': u'MCRUN2_71_V1', u'HIG-RunIISummer16DR80Premix-02515_0': u'PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6'}, u'TrustSitelists': True, u'UnmergedLFNBase': '/store/unmerged', u'CustodialSubType': 'Replica', u'TrustPUSitelists': True, u'GracePeriod': 300, u'MergedLFNBase': '/store/mc', 'HardTimeout': 159900, u'MaxMergeSize': 4294967296, u'AcquisitionEra': {u'HIG-RunIISummer16MiniAODv2-02531_0': u'RunIISummer16MiniAODv2', u'HIG-RunIISummer16DR80Premix-02515_1': u'RunIISummer16DR80Premix', u'HIG-RunIISummer15GS-02106_0': u'RunIISummer15GS', u'HIG-RunIISummer16DR80Premix-02515_0': u'RunIISummer16DR80Premix'}, u'NonCustodialSubType': 'Replica', u'NonCustodialSites': [], u'MinMergeSize': 2147483648, u'BlockCloseMaxWaitTime': 172800, u'SiteWhitelist': [u'T2_UK_SGrid_Bristol', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_UK_SGrid_RALPP'], u'SiteBlacklist': [], u'ProcessingVersion': 1, u'Dashboard': 'reprocessing', u'Team': 'production', u'AutoApproveSubscriptionSites': [], u'MaxVSize': 4394967000, u'NonCustodialGroup': 'DataOps', u'RequestStatus': u'assigned'} ...
```

The workload configuration has the correct values
```
prozober_ACDC0_task_HIG-RunIISummer15GS-02106__v1_T_170323_095110_8480.tasks.HIG-RunIISummer16MiniAODv2-02531_0MergeMINIAODSIMoutput.constraints.sites.trustPUlists = True
prozober_ACDC0_task_HIG-RunIISummer15GS-02106__v1_T_170323_095110_8480.tasks.HIG-RunIISummer16MiniAODv2-02531_0MergeMINIAODSIMoutput.constraints.sites.trustlists = True
```

but somehow the GWQE has `"NoInputUpdate":false, "NoPileupUpdate":true`

I've just tested an ACDC merge in testbed and the flags work just fine.

Feel free to abort that ACDC if you want. More debugging is needed but it will likely take some time.

**Comment by ticoann** [comment] 2018-02-27 19:08
@prozober, @amaltaro, Alan is this still the problem?

**Comment by amaltaro** [comment] 2018-02-27 19:10
For what I'm concerned of, nope. I didn't manage to reproduce it back there and we run ACDC merge + trust in almost every cmsweb integration tests.

**Comment by amaltaro** [comment] 2018-04-09 13:51
Since this issue is more than an year old and there were no further cases, I'm closing it. Feel free to reopen it if it pops up again.

**Closed by amaltaro** 2018-04-09 13:51 UTC
Labels: Medium Priority
