### ISSUE TITLE
Putting upper limit on events per lumi

### ISSUE THREAD

**Issue by thongonary** [dmwm/WMCore#9058] opened 2019-02-28 19:59 UTC
Recently we encountered a lot of DR workflows that take GS as input, but can't run because the input GS dataset has huge events per lumi.

For example: This request [1] producing the dataset [2] which has effective lumisize of 33993 (from the original events_per_lumi of 355449). 

This big lumi size makes it impossible for any subsequent requests that take this dataset as the input to process without exceeding the walltime limit of 45h or size limit of 20GB. For example, this DRPremix request [3] taking the above input GS dataset can't run for such reason. PdmV needs to resubmit the whole chain from scratch, which is resource inefficient. 

Currently in Unified, the evts/lumi splitting of workflow is chosen as the minimum among the list of events/job on all tasks [4], which are based on input parameters of time and size per event. For a GS-only request, it will simply be the same as number of events per job.

Similarly in WMCore [5], events per lumi is scaled down to events per job. 

In both Unified and WMCore, there is no protection against the situation where both values are very high (but still fit within 8-hour job).

Given the McM convention of 1000 events/lumi for DR step, I propose to implement an upper limit on this value in the similar range (eg, 1500).

Suggestions are welcome.

[1] https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_BPH-RunIIFall17pLHE-00001__v1_T_180822_215351_2476
[2] BcstarToBcPiPi_bcvegpy_pythia8_13TeV/RunIIFall17GS-93X_mc2017_realistic_v3-v1/GEN-SIM
[3] https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_BPH-RunIIFall17DRPremix-00165
[4] https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L7517-L7522
[5] https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L83

**Comment by amaltaro** [comment] 2019-02-28 20:44
@thongonary apparently this request was correctly formed:
pdmvserv_task_BPH-RunIIFall17pLHE-00001__v1_T_180822_215351_2476

The problem is that close to the end of 2018, when we implemented changes to EventsPerJob and EventsPerLumi such that they are multiple, we didn't foresee a case that caused problems to a few requests.

Given that this request is from August 2018, it's very likely it hit that issue. Looking at the request configuration, I'm actually certain it wasn't properly splitted:
```
  "Task1": {
    "EventsPerLumi": 874, 
    "EventsPerJob": 52558864, 
```

however the splitting dict for task1 has:
```
  {
    "splitAlgo": "EventBased", 
    "splitParams": {
      "algorithm": "EventBased", 
      "events_per_lumi": 355449, 
      "deterministicPileup": false, 
      "lheInputFiles": true, 
      "trustSitelists": false, 
      "events_per_job": 500000, 
      "type": "Production", 
      "include_parents": false, 
      "trustPUSitelists": false
    }, 
    "taskName": "/pdmvserv_task_BPH-RunIIFall17pLHE-00001__v1_T_180822_215351_2476/BPH-RunIIFall17pLHE-00001_0", 
    "taskType": "Production"
  }, 
```

I don't think there is anything to fix here. I was also expecting all these very old workflows to be away of the system by now. If you have a list of such old workflows still active in the system, I can check whether they have splitting issues.

**Comment by thongonary** [comment] 2019-02-28 21:02
Fair enough. I have another example:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_JME-RunIIFall18GS-00007__v1_T_180928_180051_8346
The events per lumi is splitted to 6678, which is reasonable given the context at that time (I think even after the fix this value will not change).

However, when a new DR workflow wants to run on the GS output of the above workflow, it can't start because of similar reason, ie, 6678 events per lumi is still too high. 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_JME-RunIIAutumn18DR-00015

**Comment by vlimant** [comment] 2019-02-28 21:45
these come from https://github.com/CMSCompOps/WmAgentScripts/blob/45e189d4afed27ecf17a1e5c7eb977dc3428ea74/utils.py#L6930 which was fixed in https://github.com/CMSCompOps/WmAgentScripts/commit/62d7a6a0777f7c704bda775a9810f06dce8ce42f

**Closed** 2019-02-28 21:48 UTC
Labels: Further Discussion
