### ISSUE TITLE
Missing file location in wmbs

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6751] opened 2016-03-25 21:13 UTC
Jen reported there are mission locations for the log archived files.

I ran the query in vocms0310 I see bunch of files doesn't have location associate with it.

```
select * from wmbs_file_details fd left outer join wmbs_file_location fl on fl.fileid=fd.id 
                        where fl.fileid is null; 
```

I am not completely sure whether this is the legit case but need to be investigated. At least all the output files from job should have location set when file is inserted.

We may need to do 
1. In JobAccountant for the successful framework job report, we might need to validate the file location.
2. https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Files/SetLocationByLFN.py

Make sure this always insert somethiing sename (pnn) always exsits

**Comment by ticoann** [comment] 2016-03-25 21:30
It seems location is generally null
cmssrv219 2379610-0
```
 "logArch1": {
               "status": 0,
               "logs": {
               },
               "stop": 1457283138,
               "site": "T0_CH_CERN",
               "input": {
               },
               "errors": [
               ],
               "parameters": {
               },
               "output": {
                   "logArchive": [
                       {
                           "runs": {
                           },
                           "lfn": "/store/unmerged/logs/prod/2016/3/6/pdmvserv_BTV-RunIISummer15GS-00047_00275_v0__160305_104841_1982/Production/0008/0/1fed636a-e373-11e5-9c49-a0369f23d05a-191-0-logArchive.tar.gz",
                           "pfn": "root://eoscms.cern.ch//eos/cms/store/unmerged/logs/prod/2016/3/6/pdmvserv_BTV-RunIISummer15GS-00047_00275_v0__160305_104841_1982/Production/0008/0/1fed636a-e373-11e5-9c49-a0369f23d05a-191-0-logArchive.tar.gz",
                           "module_label": "logArchive",
                           "location": null,
                           "checksums": {
                               "adler32": "ba54555d",
                               "cksum": "2444304670"
                           },
                           "events": 0,
                           "merged": false,
                           "size": 0
                       }
                   ],
                   "analysis": [
                   ]
               },
               "analysis": {
               },
               "start": 1457283136,
               "cleanup": {
               },
               "performance": {
                   "storage": {
                   },
                   "multicore": {
                   },
                   "memory": {
                   },
                   "cpu": {
                   }
               }
           }
```

**Comment by amaltaro** [comment] 2016-03-25 21:34
I'm not sure whether we should call it an issue or just something that should not happen with the agent.

The problem here is the following, jobs were overflown to T0_CH_CERN (script ran by JR/Brian, completely outside the agent) and, since the agent does NOT have this site info into resource control, it has nothing to add to the wmbs_file_location table, that's why the location is null.

Workflows will stay stuck forever, unless we fail these files for T0_CH_CERN or we add resouce control info and then update all those files with a location. I did both cases in the past weeks...

You can x-check the workflow name with this elog:
https://cms-logbook.cern.ch/elog/Workflow+processing/23571

IMO, it's not a bug, WMAgent does not support running jobs where it's unknown to the agent.

**Comment by ticoann** [comment] 2016-03-25 21:41
Thanks, Alan, Yes. I just found out as well. The problem is if they want to run T0_CH_CERN. That location should be in wmbs_location_senames table otherwise the file location will be null.

For the safety check we should validate that before following call is made.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Files/SetLocationByLFN.py

I think there shouldn't be any case file without locations which prevent creating the job subsequently.

And stop working. :smile:

**Comment by amaltaro** [comment] 2016-09-01 07:37
It should be no longer an issue, I believe @ticoann made a fix for JobAccountant where it checks if the output location (PNN) of a job exists in the agent db. Closing

**Closed by amaltaro** 2016-09-01 07:37 UTC
Labels: Bug
