### ISSUE TITLE
Rewrite LogCollect jobs to use edmCopyUtil

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#6740] opened 2016-03-23 22:17 UTC
Hi,

`edmCopyUtil` (added for CMSSW_8_0_x) takes a list of LFNs and downloads them to the local disk.  For example,

```
edmCopyUtil /store/log/foo1 /store/log/foo2 /store/log/foo3 .
```

Will copy the three files to the current directory.  This uses the currently configured LFN access method in `site-local-config.xml` instead of using SRM to download the files.

If we use this for log collect jobs, it'll be a huge load off the site SRM servers - and probably make a 10x speedup for these job types.

Brian

**Comment by ticoann** [comment] 2016-03-24 03:12
Thanks Brian that is good to know. So this one only works on CMSSW_8_0_X and newer version, right?

**Comment by bbockelm** [comment] 2016-03-24 03:38
That's correct.  However, my understanding is that it's no longer an issue to have step X run on version Y and step Z run on version Y+1.

So, this could be independent of the CMSSW version used for the rest of the workflow, right?

**Comment by hufnagel** [comment] 2016-03-24 07:32
LogCollect jobs at the moment don't use CMSSW at all. We could hardcode any version we want to if we so choose. If a site has a working cvmfs, it has all the versions available anyways.

**Comment by bbockelm** [comment] 2016-03-29 14:05
Just to give input on the "size" of the problem, I see about 1-2% of our resources going to LogCollect jobs.  So, the overall efficiency gains of tackling this problem would probably be no more than 1% of our total throughput.

Maybe would be a good contribution for a new developer?

**Comment by hufnagel** [comment] 2016-05-25 07:41
I am taking a look at this. Need to look at LogCollect jobs anyways since they are broken on CernVM and most likely will be broken on some/most of the OSG soon. They rely on lcg-cp stageout and lcg-cp has been deprecated for years and is now actually starting to disappear.

@bbockelm , I prefer to copy in the logArchives one at a time since that minimizes the local disk space use. Shouldn't be much of an efficiency loss as far as edmCopyUtil is concerned, right ?

**Comment by bbockelm** [comment] 2016-05-26 02:45
It is a bit of an efficiency loss - you reuse the security session if you do multiple files.  [Of course, it's nowhere nearly as inefficient as running SRM commands!]

We're supposed to have 10GB of disk space dedicated, right?  Why can't we do something like 10 files at a time?  I suppose the difference in efficiency between 10 files and 500 files is likely acceptable.

**Comment by hufnagel** [comment] 2016-05-26 14:08
Ok, I have tested a first version of this but am running into problems with authentication. Which is weird since a) all the WMCore runtime code should be executed with the production user proxy and b) the stagein method used before worked. 

@bbockelm , on that stagein method, it looked like LogCollect was already using the site-local-conf access method to download the files. At least the only override was for stageout, not stagin.

**Comment by hufnagel** [comment] 2016-05-26 14:09
Which raises the question, do we really need that edmCopyUtil ? It still gives some benefits as it can copy multiple files in one go, at the expense of adding the Scram dependency and making the code more complex.

**Comment by hufnagel** [comment] 2016-05-26 15:45
I am closing this ticket. Just checked again and stagein happens one file at a time but with the site-local-conf method. It's not worth introducing a Scram and specific CMSSW version dependency (did it and the code is somewhat ugly and much harder to debug than the stagein version we have now) just to allow us to copy in multiple files at once (which anyways has the side effect of using more local disk space).

**Comment by bbockelm** [comment] 2016-05-26 15:51
@hufnagel - are you sure about that?  We saw lots of sites complain about the stage-in method being SRM instead of what's specified in `site-local-conf`.  Can you ping me on chat about it?

**Comment by hufnagel** [comment] 2016-05-26 16:56
Reopened after discussion with @bbockelm. The problem was not as originally stated.

Sites that have SRM configured for stageout also use SRM for stagein. This is by design, the same protocol is used. They are still getting killed by it. Now, IMO, that's a problem at the site for a) choosing SRM for stageout and b) not being able to survive a medium to high transaction rate on the SRM gateway. OTOH, this doesn't help the sites in question.

I'll keep developing this, it was in any ways almost done. By switching the logic around a bit I now call a single edmCopyUtil on all logArchives without using up more disk space.

Side effect will be that LogCollect can't skip input files anymore. They either get processed all or none of them. But the job itself should be faster.

**Comment by amaltaro** [comment] 2016-05-26 22:15
> Side effect will be that LogCollect can't skip input files anymore. They either get processed all or none of them. But the job itself should be faster.

IF the LogCollect failure rate is very very small, then I think it's a fair tradeoff.
Otherwise, risking 500 logArchives to get this job faster (by how much btw?) doesn't look very attractive IMO.

**Comment by hufnagel** [comment] 2016-05-26 22:29
The problem with the file by file stagein is that the timeouts (10min) apply to every single file. So if something gets stuck, it can really get stuck. I have seen LogCollect jobs hit the full timeout for every single of their input files and take basically order day to days.

With the all at once you have a single timeout of an hour, after which you know if the job worked or not (well, you still have stageout to EOS and Castor, but these are just two calls).

Do we have an analysis somewhere on LogCollect failure rates. Or better, skipped file rate in LogCollect jobs. If you have a job where all input files are gone, you don't care, you want to fail it as quickly as possible. It's only the cases where some files are there and others aren't that are problematic.

**Comment by bbockelm** [comment] 2016-05-26 23:07
One nice thing about `edmCopyUtil` is it uses the CMSSW timeout logic, which is a bit more refined than the WMCore logic.  For example, the timeouts can be done per call - meaning you can skip files much faster if the `XrdCl::Open` call itself is timing out.

If we want to, it would be very straightforward to tell `edmCopyUtil` to continue on processing error.  That would get us closer to the current behavior.

**Comment by bbockelm** [comment] 2016-05-26 23:16
For reference - looking back at old emails, in October 2015, T2_UK_SGrid_RALPP reported LogCollect jobs were triggering 150Hz of TCP connections to their SRM endpoint.  Recall transfer failures trigger retries, which push up the rates that high.  At the time, the CMS-wide stageout rate (all jobs) was about 16Hz (and that particular site was about 3% of total CMS).

Even assuming a fairly wide margin of error, LogCollect jobs were in the neighborhood of 100x more load on the SRM endpoint than the stageout - that's what triggered off the creation of `edmCopyUtil` and ultimately this ticket.

**Comment by amaltaro** [comment] 2016-05-27 06:18
> If we want to, it would be very straightforward to tell edmCopyUtil to continue on processing error. That would get us closer to the current behavior.

I think that's exactly what we need in this case. Hopefully there won't be a case where it fails to stage in 499 files and only one of them succeed :)

**Comment by hufnagel** [comment] 2016-05-27 06:58
edmCopyUtil being able to skip input files would be good, but it's not needed for this ticket to be addressed for now. If we worry about partial logArchive availability I can switch from a edmCopyUtil call on all files (which is anyways a bit much for 500 files) to one call per 10 files, which should be acceptable even without the ability to skip input files.

**Comment by hufnagel** [comment] 2016-05-27 14:21
Pull request is made #6895 , lets move the discussion there

**Closed** 2016-06-23 14:54 UTC
Labels: High Priority
