### ISSUE TITLE
Files injected to Phedex after workflow has gone in completed

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6922] opened 2016-06-09 21:28 UTC
with reference to https://cms-logbook.cern.ch/elog/Workflow+processing/24617 a file was injected days after a worklow passed to completed

https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_task_B2G-RunIISpring16DR80-00821__v1_T_160501_023624_8290

"RequestTransition":[{"Status":"new","UpdateTime":1462062990,"DN":null},{"Status":"assignment-approved","UpdateTime":1462062995,"DN":null},{"Status":"assigned","UpdateTime":1462268361,"DN":null},{"Status":"acquired","UpdateTime":1462268761,"DN":null},{"Status":"running-open","UpdateTime":1462277926,"DN":null},{"Status":"running-closed","UpdateTime":1462277997,"DN":null},{"Status":"completed","UpdateTime":1462499489,"DN":null},{"Status":"closed-out","UpdateTime":1462650382,"DN":null},{"Status":"announced","UpdateTime":1462688039,"DN":null},{"Status":"normal-archived","UpdateTime":1462778358,"DN":null}

Time_Create for this files in PhEDEx:

/store/mc/RunIISpring16DR80/TTbarDMJets_scalar_Mchi-1_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RAWAODSIM/PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3_ext1-v1/50000/4007D0BE-8E17-E611-A67E-00266CFCCBF0.root
1462982196.64 Wed May 11 17:56:36 CEST 2016
/store/mc/RunIISpring16DR80/TTbarDMJets_scalar_Mchi-1_Mphi-10000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RAWAODSIM/PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3_ext1-v1/50000/8C2065C3-E813-E611-B26F-A0369F7FC9C0.root
1462586081.74 Sat May  7 03:54:41 CEST 2016

**Comment by vlimant** [comment] 2016-07-11 19:13
somehow related to this, there are workflows moving to completed even if not all files are injected yet, making it diffcicult what to expect from the "completed" status

**Comment by hufnagel** [comment] 2016-07-11 19:36
Workflow "completed" for the WMAgent means all data processed, ie. all subscriptions finished. Nothing else.

PhEDEx injection and DBS registration happen completely asynchronously to running the workflow and job completion. That might not be what you want, but it's a very basic design feature of the WMAgent. The processing side of the agent basically throws the produced data over the fence to the DBS/PhEDEx side of the agent and never cares what happens on the other side of the fence. By design.

Now, normally we have timeouts for PhEDEx injections and DBS registrations and timeouts for workflows moving to complete that make something like what you saw very unlikely.

Given that we recently shortened some of these timeouts (workflow marked as complete even with logcollect still in the system), IMO it's perfectly possible that workflows now move to complete even with data on the PhEDEx/DBS side not fully handled. It shouldn't be days though, since usually the timeouts for PhEDEx/DBS are 24h, not more. Maybe there was a problem with the PhEDEx or DBS components in that agent ?

Now, before someone asks for the obvious, the processing side and DBS/PhEDEx side were never supposed to communicate two-ways. The agent was specifically designed to be fire and forget about data registration. That being said, it *might* be possible to implement a limited cross-check in the workflow completion check that takes into account data registration status.

**Comment by hufnagel** [comment] 2016-07-11 19:38
@ticoann , is this analysis correct or do we actually have such a cross check already ? Given the evolution that the workflow completion code went through, I am not actually sure anymore what it checks and what it doesn't check.

**Closed** 2019-03-18 08:36 UTC
