### ISSUE TITLE
Migrate t0reqmon (T0 WMStats) to the dmwm 

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10396] opened 2021-03-31 14:34 UTC
**Impact of the new feature**
T0WMStats (t0_reqmon)

**Is your feature request related to a problem? Please describe.**
With the migration to Kubernetes, we have the concept of namespaces. Almost all of the WMCore services are under the `dmwm` namespace, but `t0reqmon` (WMStats for T0 activity), which gets deployed under the `tzero` namespace.

Given that all these services (reqmgr2, global workqueue, microservices, reqmon, t0reqmon, acdcserver, etc) are extracted from the very same repository - WMCore - we usually upgrade all of those services at the same time, to ensure that all the inter-services dependencies are properly fulfilled.

**Describe the solution you'd like**
Given what is described above, I would suggest to move the `t0reqmon` service back to the `dmwm` namespace. This setup would likely make our deployments easier and less error prone. There is, of course, quite some communication with the HTTP team to be done with this issue, including a discussion on possible pros/cons.

**Describe alternatives you've considered**
An alternative would be to come up with solid and complete deployment instructions, such that whoever deploys new services into CMSWEB k8s, will always deploy `t0reqmon` as well. Of course, that person needs to first be allowed to take actions on the `tzero` namespace.

**Additional context**
none

**Comment by todor-ivanov** [comment] 2022-10-13 10:55
Hi @amaltaro As you already mentioned in the issue here: https://github.com/dmwm/CMSKubernetes/pull/1230 there is some reasoning for doing this. But I am not sure if we have ever put that in some kind of discussion with the T0 team. They may have different opinion on that. How about we mention this during the next T0 meeting, and check what their plans are. I am afraid this would be strongly correlated on how WMCore and T0 are to be packaged and uploaded to Pypi.

**Comment by vkuznet** [comment] 2022-10-13 11:04
I agree with @todor-ivanov , and I want to remind you the reason service should belong to specific namespace. We use k8s namespace to provide clear separation for dev-teams who maintain their services such that one group will not overlap and screw up services from another namespace. For example, DBS developers should not intervene with dmwm services and vice versa. Therefore, it is up to you to decide if T0 belongs to dmwm namespace, and if so both teams will have **full** access to dmwm namespace and as such anyone with access can do anything in that namespace. I hope you understand the consequences of such decision. In my view T0 services should be separate from dmwm ones, but I may be wrong from operational point of view.

**Comment by amaltaro** [comment] 2022-10-13 11:42
The options that I can see here are:
1) Deploy all our `dmwm` services and also the `t0reqmon` under the `tzero` namespace whenever we need to test/deploy things.
2) Leave `t0reqmon` deployment and tests up to the T0 team (even though we - WMCore - are the developers and responsible for this service!)
3) Given that we are responsible for `t0reqmon`, move it under the `dmwm` namespace such that we always deploy it together with all the other services.

Of course, each of them have its own impact on our workflow (and maybe affecting the T0 team). IMO, the best way forward is with option 3, more maintainable and safe in the long run. Given that the T0 are sort of our "clients", I don't think they need to have full access to the `dmwm` namespace. They NEVER had access to the CMSWEB backends, I see no reason why we should change it now (unless they want to start owning this service).

**Comment by todor-ivanov** [comment] 2022-11-25 09:21
After waiting for some time, so that all actors here (T0 && WMCore Team) come to a common mind set, the natural decision of option 3 has crystalized as the best one.   

This was coordinated with T0 Team (FYI @drkovalskyi @germanfgv @jhonatanamado) during the meeting last week and we scheduled an initial deployment  in testbed for this month's upgrade campaign. This was also coordinated with CMSWEB Team and from their side the issue is about to be followed in [this](https://its.cern.ch/jira/browse/CMSKUBERNETES-207) Jira ticket.  

During the meeting on Wednesday, we also agreed, once the deployment is completed, T0 should inject a short replay, such that we do a basic of test the services. This operation, should become part of our regular validation cycle in the future. 

FYI @vkuznet @amaltaro @khurtado @klannon

**Comment by amaltaro** [comment] 2022-11-30 18:10
@todor-ivanov I see that the testbed `dmwm` namespace now has:
```
t0reqmon
and
t0reqmon-tasks
```
pods.

I also confirm that the following REST endpoint is available:
https://cmsweb-testbed.cern.ch/t0_reqmon/data/info

Can you please have a quick look at both services logs. If everything looks fine in there as well, then I would be in favor of calling this task as completed and closing this out.

**Comment by amaltaro** [comment] 2022-11-30 18:17
Documentation has also been updated to include these 2 services:
https://github.com/dmwm/WMCore/wiki/Managing-WMCore-services-in-CMSWEB-kubernetes#deploying-wmcore-services-in-cmsweb-testx-kubernetes-cluster
and
https://github.com/dmwm/WMCore/wiki/WMCore-central-services-deployment-k8

Please update anything else that I might have missed.
I will try to get back to these 2 wikis in the coming week and merge them in a single one.

**Comment by todor-ivanov** [comment] 2022-12-02 09:59
Thanks @amaltaro  I was just waiting for a confirmation from T0 team if they had some results from at least one of their replays they were running in testbed. 

And @germanfgv just confirmed that at least one of them was running safe. So I am closing this GH issue and will paste final results from (hopefully a binary one) from their feedback in the regular release validation issue for HG2212: https://github.com/dmwm/WMCore/issues/11302

**Closed by todor-ivanov** 2022-12-02 09:59 UTC
Labels: High Priority, Tier0-systems, Feature change, PR: Update documentation, Kubernetes
