### ISSUE TITLE
CERN current thresholds affecting job throughput

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11593] opened 2023-05-15 20:10 UTC
**Impact of the new feature**
Work acquisition and job creation is pull about ~50k more work that what it should for CERN at the moment (see plot in additional context section).

**Is your feature request related to a problem? Please describe.**
 Adjusting the threshold mentioned above would essentially reduce this load that end up in just thousands of jobs in idle mode and can potentially create bottlenecks in other parts of the system (e.g.: JobSubmitted for example, has a cache that if all the jobs in the cache remain in idle, it won't iterate to new jobs for other sites unless the cache is increased). 

**Describe the solution you'd like**
The solution is not within WMCore, but rather Site Support, but a ticket is created here to discuss more on it.

Reduce threshold to more realistic limits, to e.g.: 1/3 of the current threshold. Announcing more jobs for a site that it can actually run can create a bottleneck at some point somewhere else in the system. 

**Additional context**
Grafana:
https://monit-grafana.cern.ch/d/o3dI49GMz/cms-job-monitoring-12m?orgId=11&var-group_by=ScheddName&var-Tier=All&var-CMS_WMTool=WMAgent&var-CMS_SubmissionTool=All&var-CMS_CampaignType=All&var-Site=T2_CH_CERN&var-Site=T2_CH_CERN_HLT&var-Site=T2_CH_CERN_P5&var-Type=production&var-CMS_JobType=All&var-CMSPrimaryDataTier=All&var-adhoc=data.RecordTime%7C[>%7Cnow-7d&var-ScheddName=All&from=1683815908794&to=1684161508794&refresh=30m&viewPanel=17](https://monit-grafana.cern.ch/d/o3dI49GMz/cms-job-monitoring-12m?orgId=11&var-group_by=ScheddName&var-Tier=All&var-CMS_WMTool=WMAgent&var-CMS_SubmissionTool=All&var-CMS_CampaignType=All&var-Site=T2_CH_CERN&var-Site=T2_CH_CERN_HLT&var-Site=T2_CH_CERN_P5&var-Type=production&var-CMS_JobType=All&var-CMSPrimaryDataTier=All&var-adhoc=data.RecordTime%7C%3E%7Cnow-7d&var-ScheddName=All&from=1683815908794&to=1684161508794&refresh=30m&viewPanel=17)

**Comment by amaltaro** [comment] 2023-05-15 21:39
I totally second your comment above Kenyi, you captured it well!
I am talking to Jen and Stephan and if we all agree, we should decrease CERN thresholds to something more realistic. We can then watch resource utilization / work pending and see the impact of such changes.

**Comment by jenimal** [comment] 2023-05-17 19:55
Which is actually the plan for the run3 rerecos.  As we put the data at the T1’s but we can only really run them at RAL, FNAL and CNAF due to the EL8 issue.  So we need to solve this problem sooner rather than later.

Jen

From: Alan Malta Rodrigues ***@***.***>
Date: Wednesday, May 17, 2023 at 2:40 PM
To: dmwm/WMCore ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [dmwm/WMCore] CERN current thresholds affecting job throughput (Issue #11593)

Just an update, Antonio said in the Computing Operations mattermost that the definition of production slots is not in the hands of the SI. He also provided this<https://monit-grafana.cern.ch/d/000000628/cms-job-monitoring-es-agg-data-official?orgId=11&var-group_by=Type&var-Tier=All&var-CMS_WMTool=All&var-CMS_SubmissionTool=All&var-CMS_CampaignType=All&var-Site=T2_CH_CERN&var-Site=T2_CH_CERN_P5&var-Type=All&var-CMS_JobType=All&var-CMSPrimaryDataTier=All&var-binning=1h&viewPanel=15&from=now-80d&to=now-1h&refresh=15m> grafana link which shows that there is a large difference between max and min cores used by central production (from 6k all the way to 71k).

Apparently we are not taking any actions at the moment, but this issue will likely come up again if we target high priority workflows at only 1 or 2 very large sites.

**Comment by amaltaro** [comment] 2023-06-20 02:11
In the end we didn't converge with any action and we will likely not to.
Access to the CERN resources by the central production system is fairly non-deterministic during data taking, thus large peaks (and dips) can be seen.

I also just confirmed with the Site Support team (Stephan) and site slots available for central production are not automatically updated by the SST machinery. It changes solely based upon manual changes via the Site Capacity system.

@khurtado I am in favor of closing this issue out. What do you think?

**Comment by amaltaro** [comment] 2023-06-27 10:37
I am closing this one out.

**Closed by amaltaro** 2023-06-27 10:37 UTC
Labels: Operations, WMAgent, Further Discussion
