### ISSUE TITLE
time.sleep delaying Agent components

### ISSUE THREAD

**Issue by johnhcasallasl** [dmwm/WMCore#6899] opened 2016-05-30 19:44 UTC
The polling cycle of some components in the WMAgent is taking too long. The cause is this line in the Dashboard Reporter:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Dashboard/DashboardAPI.py#L85
It is called every time that a job report is sent to Dashboard. Hundreds of jobs are reported per polling cycle when the agent has a big load, causing the delays that we observed.

**Comment by hufnagel** [comment] 2016-05-30 20:45
@juztas since that code line is from you, any particular reason for the 1 second sleep there ? If not, we should just remove it.

**Comment by amaltaro** [comment] 2016-05-30 20:58
John, thanks for catching this issue. I just started to validate the newest WMCore release and this will be very wanted there, of course.

@hufnagel are you taking care of this issue?

**Comment by hufnagel** [comment] 2016-05-30 21:01
@juztas wrote that line, I don't just want to remove it (although this is what was done for the prod Tier0 to get things moving again) without hearing from him on why he added it first.

If it was just a precaution we should just drop it. If it solved an actual problem we need to find a different way (one general way is to try without sleep, catch the error caused by the sleep and only sleep when you really need it).

**Comment by juztas** [comment] 2016-05-31 09:40
Go ahead and remove if update rate is not big. No particular reason, as it was merged from CRAB and WMAgent as they both use same code. I took crab code as precedence. How many updates are sent per second?
If really to speed up, better to get instance once for multiple updates and free it up only after all updates.
Config: SleepTime 0.005 before every send. 500 updates total.
```
== Get instance once, Sleep `SleepTime` before every send. Free it only in the end.
real	0m2.903s
user	0m0.152s
sys	0m0.086s
== Get apmon instance before every send and do not free it. Sleep `SleepTime` before every send.
real	0m34.342s
user	0m6.620s
sys	0m35.321s
== Get apmon instance before every send and free it after every send. Sleep `SleepTime` before every send.
real	0m21.762s
user	0m3.352s
sys	0m6.808s
== Get apmon instance before every send and free it after every send. Do not sleep at all.
real	0m18.590s
user	0m2.872s
sys	0m5.664s
== Get instance, send all and do not sleep between sends. free up instance after all send.
real	0m0.165s
user	0m0.082s
sys	0m0.067s
```

**Comment by hufnagel** [comment] 2016-06-03 19:23
@juztas , what you suggest sounds sensible, but is not trivial. The apmonFree calls are encapsulated within the DashboardAPI and DashboardReporter classes. You don't even see it from downstream code, you just interact with the DashboardReporter class and use its class method.

Now, the DashboardReporter class methods do support bulk operations, maybe we just have to find out which method this actual was slowing down on and make sure they make bulk calls.

Either way, even with bulk calls, adding a sleep call without a good reason is a bit pointless, so I am just removing it.

**Closed** 2016-06-03 21:43 UTC
Labels: Bug, High Priority
