### ISSUE TITLE
wmagent archivedelayhours is not working

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#6045] opened 2015-07-02 07:37 UTC
In the wmagent config.py I see

config.TaskArchiver.archiveDelayHours = 336

but workflows are disappearing from wmstats after 1 day. For example:

woodson_HLT_newconditions0_RelVal_246951_150630_140936_4826

**Comment by AndrewLevin** [comment] 2015-07-02 08:32
Actually, I see that workflow now. But this workflow is missing:

woodson_HLT_reference_RelVal_248038_150630_161538_7152

**Comment by amaltaro** [comment] 2015-07-02 09:16
When did you change the TaskArchiver configuration? The agent was redeployed on 29 of June with the default value (24h). It may be that this workflow was archived before your change (+ TaskArchiver restart, of course).

**Comment by AndrewLevin** [comment] 2015-07-02 09:23
I did not change it. 336 was the original value when it was deployed.

**Comment by amaltaro** [comment] 2015-07-02 16:21
Ok, it was in the deployment script. As I told you in the meeting, I think I know what the problem is and I'm cooking a fix for that.

**Comment by ticoann** [comment] 2015-07-08 16:38
@amaltaro, Hi Alan, this can be closed, right?

**Comment by amaltaro** [comment] 2015-07-08 17:24
Hi Seangchan, that's right. Please close this issue.

**Comment by AndrewLevin** [comment] 2015-07-08 17:35
Wait, Alan, I have a question. If you have two agents that are both on the same team, with different archivedelayhours, then does your fix (https://github.com/dmwm/WMCore/pull/6048) still work?

**Comment by amaltaro** [comment] 2015-07-08 17:36
it makes no sense to have two agents in the same team with different archiveDelay settings.

**Comment by AndrewLevin** [comment] 2015-07-08 17:42
But it is still possible to make a mistake. For relval there is only one agent, but for some teams there are like 3 or 4 agents, right? And agents are being added/removed/redeployed pretty frequently, right? So, it is probably not a good idea to require that the settings between different agents be synchronized. I recommend we set this per workflow, not per agent. Or we just set it to globally in one place.

**Comment by amaltaro** [comment] 2015-07-08 17:47
There is a stable deployment procedure and agents belonging to the same team will always have the same archiveDelay (unless someone changes it by hand).

We don't have finer granularity to control it and IMO making this setting by workflow is completely overkill (besides more work on us). You are the only 'client' interested/using this feature and it will work perfectly fine for you.

**Comment by AndrewLevin** [comment] 2015-07-08 17:56
I have been changing it by hand. It is very easy to change the config.py by hand. As you said it will work for me for now (but maybe in the future we will get multiple relval agents), so if you want please go ahead with. But I recommend we leave this issue open or create a new one (with a very low priority label) so we don't forget about this potential problem.

**Comment by amaltaro** [comment] 2015-07-08 18:19
If we want to create a GH issue for each potential problem, then we would end up with lots of tickets, making it harder to manage, to keep track of, to fix, etc. In the end it reduces our ability to track and prioritize these issues, that's why I'd rather avoid issues that will most likely not be worked on for a long time (also meaning they are not really important ;)).

**Comment by AndrewLevin** [comment] 2015-07-08 18:40
Hi Alan,

I think there is a general design flaw here.

Why should wmagents control when workflows move from announced to normal-archived? Don't you think it would be better if the workqueue or the request manager controls this?

Andrew

**Comment by ticoann** [comment] 2015-08-07 15:44
closing this there is issue need to be fixed to solve this. #6071

**Comment by ticoann** [comment] 2015-08-07 15:45
@AndrewLevin, Sorry Andrew for doing this so late. Please check new issue  #6071 and comment on that if I missed anything.

**Closed by ticoann** 2015-08-07 15:45 UTC

**Comment by AndrewLevin** [comment] 2015-08-07 16:14
Hi Seanghan,

Issue 6071 looks like it is unrelated to this one. Are you sure you referenced the right one?

Andrew

**Comment by ticoann** [comment] 2015-08-07 16:34
Sorry I messed up the number it is 6107
