### ISSUE TITLE
Changing priority in assignment-approved fails

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8457] opened 2018-02-14 16:06 UTC
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_PPD-RunIISummer17PrePremix-00006__v1_T_180212_090017_6410 trying to set up to 111000 gives people

Server error message
Invalid spec parameter value: There are invalid arguments for no-status update: {u'SoftTimeout': 129600, u'BlockCloseMaxEvents': 25000000, u'MaxMergeEvents': 100000000, u'CustodialSites': u'', u'Ma... 

please advise, and prioritize a fix

**Comment by ticoann** [comment] 2018-02-14 16:10
Were you trying to change just priority without changing the status to assignment?

**Comment by amaltaro** [comment] 2018-02-14 16:20
Yes, without changing the request status. I just reproduced this error (I think I put in this bug in my latest changes to that code...)
Jean-Roch, changing the priority via REST API still works. We'll have this fixed by the next production deployment.

**Comment by amaltaro** [comment] 2018-02-16 10:13
And this is why it fails via web UI, because there is a stricter input arg validation now:
https://github.com/dmwm/WMCore/pull/8419/files#diff-c4879fa72848db5e9f2c06c100bdd3c0R382

and when we GET a request via reqmgr2 UI, it loads most of the assignment parameters, which is posted again when one pushes the `submit` button to change "only" the priority.

There are two ways to fix it:
* hard way: when one post arguments for a request in assignment-approved, we first cross-check which arguments changed and we pass only those upstream
* easier way: when there is a "no status update", we only make changes to RequestPriority or global workqueue stats, completely disregarding any other parameters.

I'm of course going to walk the easier path :)

**Closed** 2018-02-19 15:58 UTC
Labels: Bug, High Priority
