### ISSUE TITLE
vocms0126.cern.ch JobSubmitter

### ISSUE THREAD

**Issue by scarletnorberg** [dmwm/WMCore#7702] opened 2017-03-09 06:23 UTC
Restarted already. 

https://its.cern.ch/jira/browse/CMSCOMPPR-695

It seems to still have an issue and I am not sure what it is.

**Comment by amaltaro** [comment] 2017-03-09 08:35
Sigh... I completely missed this agent. It's still running the old release which doesn't have several new features, and that's why PyCondor was crashing while figuring out the scramArch. I've applied a temporary - dirty - patch:
```
cmst1@vocms0126:/data/srv/wmagent/current $ diff -rup /data/srv/wmagent/v1.0.21.patch4/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch4/lib/python2.7/site-packages/WMCore/BossAir/Plugins/PyCondorPlugin.py{.bkp,} | colordiff
--- /data/srv/wmagent/v1.0.21.patch4/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch4/lib/python2.7/site-packages/WMCore/BossAir/Plugins/PyCondorPlugin.py.bkp	2017-03-09 09:20:12.037053954 +0100
+++ /data/srv/wmagent/v1.0.21.patch4/sw/slc6_amd64_gcc493/cms/wmagent/1.0.21.patch4/lib/python2.7/site-packages/WMCore/BossAir/Plugins/PyCondorPlugin.py	2017-03-09 09:26:13.785163719 +0100
@@ -967,10 +967,15 @@ class PyCondorPlugin(BasePlugin):
         jdl.append('request_cpus = %s\n' % numberOfCores)
 
         # Add OS requirements for jobs
-        if job.get('scramArch') is not None and job.get('scramArch').startswith("slc6_"):
-            jdl.append('+REQUIRED_OS = "rhel6"\n')
-        else:
-            jdl.append('+REQUIRED_OS = "any"\n')
+        if job.get('scramArch') is not None:
+            scram = job.get('scramArch')
+            if isinstance(job.get('scramArch'), list):
+                # this is BAD, but we're still not using this feature anyways
+                scram = job.get('scramArch')[0]
+            if scram.startswith("slc6_"):
+              jdl.append('+REQUIRED_OS = "rhel6"\n')
+            else:
+                jdl.append('+REQUIRED_OS = "any"\n')
 
         return jdl
```

because cherry-picking Eric's changes would be too much and several commits would be needed.

**Comment by amaltaro** [comment] 2017-03-09 08:36
Since I see jobs being successfully submitted, I'm closing this issue. Thanks for spotting and reporting it.

**Comment by amaltaro** [comment] 2017-03-09 17:11
Actually, the issue is not only at plugin level, but also at CMSSW level that's trying to use a list of scram as a string, causing all jobs on that agent going to cooloff :-(

I'll cherry-pick Eric's changes on this front and apply to that agent. Working on it

**Comment by amaltaro** [comment] 2017-03-09 23:25
Just an update. The previous workaround was removed and this patch was applied to the agent:
#7703 

The following sandboxes were patched as well:
```
sandboxes_list="pdmvserv_task_SUS-PhaseIIFall16LHEGS82-00003__v1_T_170302_162209_4644
pdmvserv_task_TOP-RunIISummer15wmLHEGS-00164__v1_T_170303_121705_5453
pdmvserv_task_TOP-RunIISummer16DR80Premix-00128__v1_T_170209_012758_3132
pdmvserv_EGM-PhaseIFall16GS-00002_00012_v0__170222_162051_1041
pdmvserv_HIN-pPb502Winter16GS-00004_00002_v2_MB_170308_161639_1327
pdmvserv_task_EGM-PhaseIFall16GS-00009__v1_T_170308_161711_4945
pdmvserv_EGM-PhaseIFall16GS-00004_00014_v0__170308_161328_9689
pdmvserv_task_EGM-PhaseIFall16GS-00007__v1_T_170308_161702_7407"
```

**Comment by amaltaro** [comment] 2017-03-09 23:42
I think it's fine to close this issue now.

**Closed by amaltaro** 2017-03-09 23:42 UTC

**Comment by ticoann** [comment] 2017-03-10 03:37
Thank you very much Alan,
