### ISSUE TITLE
Need for a standard procedure to create a given prod enviroment and run a job manually

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11444] opened 2023-01-18 09:55 UTC
**Impact of the new feature**
Debugging

**Is your feature request related to a problem? Please describe.**
Often times, we're asked by the sites whether they can manually run a failed prod job and reproduce the error. Here is an example [1]. @todor-ivanov told me today that this is not easily possible.

[1] https://ggus.eu/index.php?mode=ticket_info&ticket_id=160101 

**Describe the solution you'd like**
I'm suggesting making such a procedure easily possible and providing guidelines for it. I'm not sure what are the restrictions for it.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amaltaro** [comment] 2023-01-18 12:34
@khurtado Kenyi, when you were working on the PSet python decoupling, I think you also documented how to run a production job interactively, right? If so, is this wiki/section the correct reference:
https://github.com/dmwm/WMCore/wiki/List-of-PSet-tweaks-applied-by-WMAgent-during-job-runtime#pset-tweak-examples-and-job-environment-to-reproduce-the-whole-pset-tweak-stages-procedure

or is it only meant to be use to test PSet tweaks?

**Comment by khurtado** [comment] 2023-01-26 22:22
@amaltaro It works for any job. The general information is in the repository below (which the link you pointed out links to):
https://gitlab.cern.ch/khurtado/psettweakmigration/

**Comment by todor-ivanov** [comment] 2023-01-27 07:43
Hi @khurtado, 
Thanks for looking into this.
>  If this is back in TODO, I can work on it since I started this method if you want.
I absolutely agree,  it'll be better if you finish this, as you said, since this is a continuation of your previous effort. I'll   unassign myself from the issue.

**Comment by khurtado** [comment] 2023-01-31 22:16
@haozturk Here is a document that illustrates what's been asked in this issue:

https://github.com/dmwm/WMCore/wiki/Standard-procedure-to-create-a-given-prod-enviroment-and-run-a-job-manually

Please, let me know if you have any questions or difficulties with it.

**Comment by khurtado** [comment] 2023-03-27 14:14
I recently tested this and fixed a minor issue (using python rather than python3 in the last example command line). I will close this issue, but feel free to re-open it if someone test it and see problems using the guide guide.

**Closed by khurtado** 2023-03-27 14:14 UTC
Labels: New Feature, Operations, Stakeholders

**Comment by amaltaro** [comment] 2023-03-27 20:36
@khurtado better later than never, so here I go :)

I finally managed to give this a try and I confirm that I can also execute a production job with what you documented in the wiki. I made a minor update to the wiki though and started it with a "Requirements" section, to clarify the 3 pieces of data that the person will need to execute a job. Please have a look and let me know.

In addition to that, this line:
```
python Unpacker.py --sandbox=$sandbox --package=$package --index=$index
```
seems fragile to me, because it would be using the system python. 
So my suggestion would be to move those 3 cvmfs source lines above, before unpacking the job, and then running the Unpacker.py with `python3` instead. What do you think?
