### ISSUE TITLE
T0 agent not archiving workflows - CleanCouchPoller

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8680] opened 2018-07-12 16:01 UTC
@vytjan Vytas vagabundo has seen frequent heartbeat issues with CleanCouchPoller and the reason - seems to be - is that that thread isn't actually archiving workflows. Somewhere around this code:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/TaskArchiver/CleanCouchPoller.py#L235

From the logs, we see the list of archiveable workflows is ever growing, e.g.:
2018-07-12 10:35:51,942:140372278933248:INFO:CleanCouchPoller:Ready to archive normal 4619 workflows
2018-07-12 12:55:42,638:140225241270016:INFO:CleanCouchPoller:Ready to archive normal 4644 workflows
2018-07-12 15:18:54,328:140543812171520:INFO:CleanCouchPoller:Ready to archive normal 4709 workflows

This is on vocms0314. Seangchan, if you can have a look at it, be my guest ;)

**Comment by ticoann** [comment] 2018-07-14 03:49
@vytjan, Thanks Vytas, I put some debugging code in vocms0314. Please don't restart TaskArchiver.

**Comment by ticoann** [comment] 2018-07-14 05:39
It seems the problem is fwjr database view is corrupted.(24GB) I deleted the view and start regenerate the view. It will take a while to build. I also left debugging code and increate the TaskArchiverPoller cycle to 4 hours. It seems it is back logged ~7000 workflows which need to upload to dashboard for performance update. That seems take a while. I will check back tomorrow, so please don't restart the agent even it is red in tier0_wmstats. Thanks.

**Comment by ticoann** [comment] 2018-07-14 13:18
Still view is not created correctly. It might be some specific document causing this problem.  
I added some temporary patch to make by pass this error for a while. I will check back later.

**Comment by vytjan** [comment] 2018-07-16 08:11
@ticoann Thanks Seangchan, I see that workflows started being archived on vocms0314 after your patch was added.
However, the same issue persists also in the current T0 headnode, vocms014. A number of workflows to be archived is only increasing:
`
2018-07-16 05:09:53,291:140321861613312:INFO:CleanCouchPoller:There are 2881 workflows to check for archived status
...
2018-07-16 06:05:44,125:140321861613312:INFO:CleanCouchPoller:There are 2887 workflows to check for archived status
...
2018-07-16 07:00:30,552:140321861613312:INFO:CleanCouchPoller:There are 2893 workflows to check for archived status
`
How do you think, is it really just some specific document(-s) causing the problem, or could it be some other issue - as it looks like not a single case.

**Comment by ticoann** [comment] 2018-07-16 14:59
Hi Vytas, 
Although I am not sure about the cause of the error (corrupted document). I just checked vocms014. But in that machine it doesn't seems to have the same couch error. (And couch view are created fine for fwjr database). 
I will try to add some debugging statement once current cycle is over.  Thanks for the report.

**Comment by ticoann** [comment] 2018-07-16 19:21
Hi Vytas,
I didn't see any errors on vocms014. One thing is that it is set to archiveDelayedHours to 168 hours which is for a week. (I am not sure why there are 2 places in the config though. Anyway, if that is not you wan't make it smaller amount.)

**Comment by ticoann** [comment] 2018-07-17 20:03
@vytjan, Hi Vytas, what is the plan for vocms0314? I am just asking whether I should keep debugging on this or leave current patch there until it is redeployed.

**Comment by vytjan** [comment] 2018-07-18 09:57
@ticoann Hi Seangchan, the current plan for vocms0314 is to wait a bit until it finishes processing few last jobs and until it cleans up fully.
So I guess it could be reasonable to simply leave the current patch there until it is redeployed.

**Comment by ticoann** [comment] 2018-07-18 13:43
Thank you Vytas for update. In that case, I won't search for the corrupted documents, if that is indeed the reason (not sure about that). Can we close this issue, then?

**Comment by vytjan** [comment] 2018-07-18 14:18
I think it's fine to close it. The vocms0314 WMAgent still has ~200TB of PhEDEx data to clean up, but it should happen sometime soon (or whenever it finishes processing the few jobs which are still being processed).
Thanks for your help Seangchan, Alan!

**Closed** 2018-07-18 14:48 UTC
Labels: Medium Priority
