### ISSUE TITLE
reqmgr1 details page not functioning 

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7388] opened 2016-11-14 11:56 UTC
Probably a know issue

https://cmsweb.cern.ch/reqmgr/view/details/pdmvserv_EXO-RunIISummer15GS-07240_00440_v0__161005_163327_7785

 does not load and therefore we have no web control on it.
FYI @mcremone @prozober

**Comment by amaltaro** [comment] 2016-11-14 12:15
Duplicate of #7381

**Closed by amaltaro** 2016-11-14 12:15 UTC
