### ISSUE TITLE
Harvest jobs eventually failing during certificate/proxy check

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7821] opened 2017-04-27 15:50 UTC
Interesting case... the harvesting job fails most of the times during the authentication step [*]. I assume it cannot find my proxy in the X509_USER_PROXY env var, though it's there according to the condor.stdout logs.. Even more interesting, it works just fine with DQMHarvest workflows, but mostly fails in the other workflows that have harvesting enabled.

BTW, Matteo has just hit this issue in production as well.

[*]
```
INFO:root:HTTP Upload is about to start:
 => URL: https://cmsweb-testbed.cern.ch/dqm/dev;https://cmsweb.cern.ch/dqm/relval-test
 => Filename: /storage/local/data1/condor/execute/dir_3057657/glide_GVbWPk/execute/dir_3686180/job/WMTaskSpace/cmsRun1/DQM_V0001_R000202209__JetHT__CMSSW_7_2_0-RECODreHLT_TaskChain_LumiMask_multiRun_HG1705_Validation_TEST_Alan_v5-v11-202205-202209__DQMIO.root

INFO:root:HTTP POST upload arguments:
  ==> checksum: md5:bff80c3eafc583b07b48c926edb66aed
  ==> size: 63537411

ERROR:root:HTTP upload failed with response:
Problem unknown.
Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:662)>
Traceback: Traceback (most recent call last):
  File "/storage/local/data1/condor/execute/dir_3057657/glide_GVbWPk/execute/dir_3686180/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/DQMUpload.py", line 161, in httpPost
    (headers, data) = self.upload(uploadURL, args, filename)
  File "/storage/local/data1/condor/execute/dir_3057657/glide_GVbWPk/execute/dir_3686180/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/DQMUpload.py", line 255, in upload
    result = urllib2.build_opener(HTTPSCertAuthenticate()).open(datareq)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/urllib2.py", line 441, in _open
    'default_open', req)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/storage/local/data1/condor/execute/dir_3057657/glide_GVbWPk/execute/dir_3686180/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/DQMUpload.py", line 241, in default_open
    return self.do_open(HTTPSCertAuth, req)
  File "/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:662)>
```

**Comment by amaltaro** [comment] 2017-05-02 10:03
![](https://github.trello.services/images/mini-trello-icon.png) [Harvest jobs eventually failing during certificate/proxy check](https://trello.com/c/wULUZ2fs/30-harvest-jobs-eventually-failing-during-certificate-proxy-check)

**Comment by anorkus** [comment] 2017-05-03 14:52
Hi,

any news about this issue? Seems its repeating itself for some urgent RelVals

**Comment by vlimant** [comment] 2017-05-03 16:35
@amaltaro would a plain DQMHarvest workflow succeed ?

**Comment by amaltaro** [comment] 2017-05-03 16:53
I tried to reproduce this issue (with another DQM root file and CMSSW release) but with no success.
From my testbed tests, yes, DQMHarvest request type works just fine.

@vlimant is it failing for 100% of the automatic relval harvesting jobs? Are these harvesting jobs running at CERN or FNAL (apparently they only fail at FNAL...though it doesn't make much sense since the python interpreter+libraries are loaded from cvmfs...)

**Comment by anorkus** [comment] 2017-05-03 17:19
Hi,

as discussed in hypernews its not 100%. For AlCa validation few workflows failed, seems it was reproduced for one as it failed once they resubmitted it on friday.

**Comment by vlimant** [comment] 2017-05-03 17:39
@amaltaro can you try with the prod relval DQM and the dqmio dataset for which that has failed ? At least to get the files uploaded while you figure this out

**Comment by amaltaro** [comment] 2017-05-03 17:52
Yes, it's reproducible but not interactively by me :( Just ran again one of the failing configurations and the same code and it _just_ works fine.

Jean-Roch, are you asking me to create DQMHarvest workflows for those that failed? Can you point me to one small campaign? Should I assign it to the relval team or unified is going to pick that up? Anything especial?

Meanwhile, I'm going to run the same config at FNAL just to rule out one suspicious...

**Comment by vlimant** [comment] 2017-05-04 09:08
While pdmv has the handle to submit DQMHarvest workflows and notify Ops that they are in and should be taken care of in an Add-Hoc way, it seems that communication lines are broken and people sitting on blaming each others.
If you can create and assign to relval team these harvesting for 
https://cmsweb.cern.ch/reqmgr2/fetch?rid=rverma_PR_newco_RelVal_276950_170428_191716_3771
=> /MET/CMSSW_8_0_27-2017_04_28_19_16_PRnewco_80X_dataRun2_2016LegacyRepro_v3-v1/DQMIO

https://cmsweb.cern.ch/reqmgr2/fetch?rid=rverma_PR_reference_RelVal_276950_170428_191705_6912
=> /MET/CMSSW_8_0_27-2017_04_28_19_16_PRref_80X_dataRun2_2016SeptRepro_v5-v1/DQMIO

that would help move things forward a bit.

**Comment by vlimant** [comment] 2017-05-04 09:08
or show @prozober the scripts

**Comment by amaltaro** [comment] 2017-05-04 10:05
@prozober I have just updated this script:
https://github.com/amaltaro/scripts/blob/master/injectHarvest.py

and I also created DQMHarvest workflows for those 2 requests pointed by @vlimant 
  Request 'amaltaro_PR_newco_RelVal_276950_Harv_170504_115945_6835' successfully created.
  Request 'amaltaro_PR_reference_RelVal_276950_Harv_170504_120126_6277' successfully created.

Can you please run a quick check on them and if everything is fine, assign it to the relval team?

**Comment by prozober** [comment] 2017-05-04 14:17
The workflows were assigned to CERN, and relval team. Let's keep an eye on them.

**Comment by prozober** [comment] 2017-05-04 15:21
The workflows succeeded and got announced.

**Comment by vlimant** [comment] 2017-05-04 15:24
@prozober  please reply back to the thread https://hypernews.cern.ch/HyperNews/CMS/get/relval/7417/1/2/2.html

**Comment by amaltaro** [comment] 2017-05-08 09:15
@vkuznet as we discussed in the WMAgent meeting, indeed there were changes to the HTTPSConnection class and a few keyword args were deprecated (py 2.7.9) and it now requires a ssl context object to be passed (which holds the certificate credentials and further info).

As you suggested, I picked the DBS HTTPS handling code and added to WMCore, after a few adjustments it works fine in my interactive/local test, however it still fails when running an agent job in the grid.

I'm still investigating (and struggling to get access to the worker nodes). It may be that some environment var is screwing this up at the worker node...

**Comment by vkuznet** [comment] 2017-05-08 17:50
Alan,
you may add debug printouts in your code too, e.g.

```
class HTTPSClientAuthHandler(urllib2.HTTPSHandler):
    def __init__(self, key=None, cert=None, level=0):
        urllib2.HTTPSHandler.__init__(self, debuglevel=level)
```

and for time being setup debuglevel to be non-zero all the time to debug the
problem. I would suggest that you dump env on worker node, add non-zero
debuglevel and run some job. Please also capture both stdout/stderr output
that we can see the message.

Also, please show how you create SSLContext, e.g.
context = ssl.SSLContext(ssl.PROTOCOL_TLS)
urllib2.urlopen(req, context=context)

that we'll check how request is open.

Valentin.

**Comment by anorkus** [comment] 2017-05-09 13:30
Hi,

is there and ETA when this issue will be fixed? Currently for 910pre3 all workflows failed to upload DQM root files and this stops release validation. Alca validation was delayed when the files got re-uploaded.

If this issue is not resolved asap i would suggest to backport to previous python version.  As current situation does not allow for offline release validation to work.

Best regards,
    Antanas Norkus

**Comment by amaltaro** [comment] 2017-05-09 13:36
I forgot updating this issue, we've rolled back the runtime python version used by the relval agent. So it's again using 2.7.6 instead of 2.7.13 and harvesting should be working just fine now.

The real fix is still to come, *maybe* by tomorrow.

**Comment by anorkus** [comment] 2017-05-09 15:34
and are there any news on 910pre3 harvesting worflows finishing?
i see that all of them are still in assignment-approved status since yesterday.

**Comment by amaltaro** [comment] 2017-05-09 17:05
Apparently CompOps is still deciding how to proceed here, I suggest you to get in touch with the PnR team.

**Comment by amaltaro** [comment] 2017-05-10 15:17
@vkuznet I created a patch here #7844 which _was_ working fine. However, today in my final tests I saw it failing again. I'm going to update it again to print the trusted CERN CAs, just in case.

According to the library documentation, it suggests not to create a context object with SSLContext(), but with the default method that sets up the most secure protocol/cyphers/etc. You can see the code yourself (I also added comments explaining the settings being used).

I think the real problem is that some worker nodes don't have the CERN CAs in their capath, which then fails to verify the server certificate. I'm going to check these CAs, but if that's the case, maybe we'll need to NOT verify the server certificate... which is not desired and secure, but...

**Comment by vkuznet** [comment] 2017-05-10 15:27
> I think the real problem is that some worker nodes don't have the CERN CAs in their capath, which then fails to verify the server certificate. I'm going to check these CAs, but if that's the case, maybe we'll need to NOT verify the server certificate... which is not desired and secure, but...

It very well may be the case, but I disagree with you sneaky proposal :)
Why not to install CAs on worker nodes and do this in a proper way, instead of
"usual" hacking way?

**Comment by sextonkennedy** [comment] 2017-05-10 20:48
It does seem to be something that CERN IT should be interested in helping us with.  I could involve Kate (our contact), if you let me know.

**Comment by amaltaro** [comment] 2017-05-10 22:12
I talked to Diego G. this afternoon and it seems this was a struggle in the past, where the working solution was skipping the server certificate verification (surprise surprise it only bugs us now :)).

Moreover, he told me the system default CA path is /etc/grid-security/certificates and ALL worker nodes should trust CERN CAs. So the default SSL settings point to a different location (maybe somewhere in the python libraries). Thus, I updated the patch to always load CAs from the path previously mentioned. 

Initial tests are promising, I likely have to run a few more tests (a couple of other sites would be good) before we declare it solved ;)
Thanks, Liz, I hope it won't be needed.

**Closed** 2017-05-11 20:08 UTC
Labels: Bug, High Priority

**Comment by vlimant** [comment] 2017-05-14 16:00
@amaltaro can you please confirm whether this is fully fixed and pushed to the agents ?
There was a failure for one of the harvesting https://cms-logbook.cern.ch/elog/Workflow+processing/26486 created for one of the data reprocessing harvesting. That's probably before the fix was made. We need this deployed on all agents.
