### ISSUE TITLE
WMAgent runtime VSize limit are too small

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#8728] opened 2018-08-07 19:00 UTC
@amaltaro told me that the recent changes in default for maxVSize went along with a change of that number from kB to MB. From recent Tier0 logs I cannot confirm this, the number is still interpreted as kB.

WMAgent runtime log:
INFO:root:Executing CMSSW. args: ['/bin/bash', 
'/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc6_amd64_gcc700', 
'scramv1', 'CMSSW', 'CMSSW_10_2_1', \
'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']
INFO:root:Retrieved following performance figures:
INFO:root:RSS: 5543404;  VSize: 7982008; PCPU: 324; PMEM: 12.2
ERROR:root:Error in CMSSW step cmsRun1
Number of Cores: 8
Job has exceeded maxVSize: 1048576
Job has VSize: 7982008

CMSSW log:
MemoryReport> Peak virtual size 7794.93 Mbytes

So the limit is in kB, not MB as Alan claimed. The CMSSW processes exit cleanly afterwards (see #8727), the more interesting question then is, does the WMAgent still mark these jobs as failed ? If not, we would be silently stopping processing after a few events and then count the job as successful.

**Comment by hufnagel** [comment] 2018-08-07 20:35
This is production. But after hearing back from Tier0Ops as well, they only see this in specific PromptReco jobs, so we can tune down the alarm level somewhat...

**Comment by hufnagel** [comment] 2018-08-07 20:44
From Tier0Ops:

Currently we have this issue only in run 320500, and just for workflows PromptReco_Run320500_MET and PromptReco_Run320500_EGamma. Just 14 jobs were paused because of this issue.

**Comment by hufnagel** [comment] 2018-08-07 21:16
Based on reviewing the changes in #8489 I should just remove setting MaxRSS and MaxVSize from the Tier0. Setting the 'Memory' spec parameter is all I need to do now it seems.

Also checked, I passed MaxRSS via updateArgs as kB, but that call should be ignored. The 'Memory' parameter was always in MB.

**Comment by hufnagel** [comment] 2018-08-07 21:55
> Now why it's interpreting the MB MaxVSize as Kb, my only guess is that somehow you set MaxRSS to a Kb value, while the VSize is still MB, which then easily evaluates to true and the job is killed. This is the backwards logic at runtime:
> https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Monitors/PerformanceMonitor.py#L202

Tracing through this code and looking at the job log:

2018-08-03 03:32:49,624:INFO:PerformanceMonitor:Retrieved following performance figures:
2018-08-03 03:32:49,625:INFO:PerformanceMonitor:RSS: 5543404;  VSize: 7982008; PCPU: 324; PMEM: 12.2

So output[2] and output[3] are both in kb. I assume maxRSS is not in kB though (since you set it and I have no way to override it anymore), which means the code does.

That then triggers the observed behavior.

Where are output[2] and output[3] coming from ? They are in kB and you seem to expect them to be in MB.

**Comment by ticoann** [comment] 2018-08-08 04:42
> Where are output[2] and output[3] coming from ? They are in kB and you seem to expect them to be in MB.

It is coming from 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Monitors/PerformanceMonitor.py#L63

And it is always KB.  

MB conversion is only for maxRSS and maxVSize value which we will set.  Before Alan's patch the unit was KB, but we change the unit to MB since it is short. And following line convert rss, vsize to MB so we can compare. 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Monitors/PerformanceMonitor.py#L210

For me, the code is correct. Since maxRSS and maxVSize cannot be overwritten anymore.  But there must be a bug somewhere since the it fails.

> 2018-08-03 03:32:49,625:INFO:PerformanceMonitor:RSS: 5543404; VSize: 7982008; PCPU: 324; PMEM: 12.2

Both RSS and VSize here should be KB.

**Comment by ticoann** [comment] 2018-08-08 05:39
Default maxRSS and maxVSize is set through addRuntimeMonitors method. 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L220
But it seems PromptReco doesn't call this method.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/PromptReco.py

It seems it is take default memory value 
"Memory": {"default": 2300.0, "type": float, "validate": lambda x: x > 0},
But that value should be correct too. (MB)

Dirk, could you point me which production machine has this problem?

**Comment by amaltaro** [comment] 2018-08-08 11:10
Dirk, I know T0Ops has a script to update the sandbox. Can you ask them to update *only* that sandbox with the following patch:
https://github.com/amaltaro/WMCore/commit/af5d0721c27c3f8bfb9d0739c72cfe651f6bda0e
?

Otherwise point me to the script and I can take care of it. I still need someone to unpause those jobs though, I have no idea how to do that.

**Comment by cronot99** [comment] 2018-08-08 12:56
Hi @amaltaro , the jobs are not paused anymore. We increased the maxRSS and maxVSize values to resume them. Nevertheless, we kept the streamer files, so we can run a replay with that specific run and versions of CMSSW and T0. Do you want us to setup that replay?

If you want it, please let us know if we need to add a patch on deployment time, or if you want the jobs to fail and patch them after that.

**Comment by amaltaro** [comment] 2018-08-08 13:08
Hi Juan, honestly it doesn't make much difference for me. Given that it happened only to 1 workflow out of hundreds? thousands? I'd just let it go and report again when (if) it happens again.

If you want to understand what the problem is, then go ahead and setup a replay for this workflow. You can apply the patch a mentioned above during the agent deployment.

**Comment by cronot99** [comment] 2018-08-08 14:34
Hi Alan, we are going to keep an eye on that particular issue then, if it's spotted again we'll let you know.

**Comment by amaltaro** [comment] 2018-08-08 14:37
Sounds good. I relabeled it such that we wait for a month or two, if nothing happens, then we can close it.

**Comment by andresfelquintero** [comment] 2018-08-08 19:36
Hello. I have copied all the reports from job 105194 on the public folder, on the route /afs/cern.ch/user/c/cmst0/public/PromptReco_Run320500_MET_Paused_Jobs_20180808/job_105194 

This job failed after the increment of maxRSS and MaxVsize so I will take advantage of this to apply your patch and resume the jobs.

**Comment by amaltaro** [comment] 2018-08-09 08:36
Hi Andres!
Looking at this log /afs/cern.ch/user/c/cmst0/public/PromptReco_Run320500_MET_Paused_Jobs_20180808/job_105194/wmagentJob.log

I see the following settings
```
2018-08-08 08:18:42,282:INFO:Watchdog:Watchdog modified: False. Final settings:
2018-08-08 08:18:42,282:INFO:Watchdog:  maxRSS: 15360000
2018-08-08 08:18:42,283:INFO:Watchdog:  cores: 8
2018-08-08 08:18:42,283:INFO:Watchdog:  softTimeout: 604800
2018-08-08 08:18:42,283:INFO:Watchdog:  maxVSize: 15360000
2018-08-08 08:18:42,283:INFO:Watchdog:  hardTimeout: 608400
```

so you're setting both RSS and VSize to 15360000 KiB (=~15GB).

That's why this job gets killed.

**Comment by hufnagel** [comment] 2018-08-09 12:57
Question is, who is setting the 15GB. @andresfelquintero , did you override it ?

**Comment by andresfelquintero** [comment] 2018-08-09 14:54
Ok, I will change these values and restart this job. I will report as soon as I resume it.

**Comment by andresfelquintero** [comment] 2018-08-09 15:41
I resumed job 105187 on workflow MET on run 320500 with your specifications for RSS and VSize. So when it gets paused, I will copy the reports to a public folder and inform you about it.

**Comment by amaltaro** [comment] 2019-01-17 11:10
Not sure it was an issue in the end. We agreed to close it after a couple of months, so doing so.

**Closed by amaltaro** 2019-01-17 11:10 UTC
Labels: Further Discussion, Low Priority

**Comment by cronot99** [comment] 2019-01-17 11:54
:shipit: ::tada:
