### ISSUE TITLE
Files not injected in phedex after a few days

### ISSUE THREAD

**Issue by scarletnorberg** [dmwm/WMCore#7107] opened 2016-08-25 16:40 UTC
/DoubleEG/Run2015B-LogError-08Jun2016-v1/RAW-RECO is missing 10 files in phedex
http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=ReReco-Run2015B-08Jun2016-0001
fabozzi_Run2015B-DoubleEG-08Jun2016 is the name of the work flow

fabozzi_Run2015B-DoubleEG-08Jun2016_765p1_160608_195715_2425
jen_a_ACDC_Run2015B-DoubleEG-08Jun2016_765p1_160617_201953_7342
jen_a_ACDC_Run2015B-DoubleEG-08Jun2016_765p1_160617_202000_3164
jen_a_ACDC_Run2015B-DoubleEG-08Jun2016_765p1_160617_202006_7629
jen_a_ACDC_recovery-0-fabozzi_Run2015B-DoubleEG-08Jun2016_765p1__160818_214233_6617
jen_a_recovery-0-fabozzi_Run2015B-DoubleEG-08Jun2016_765p1__160816_095012_7710

/DoubleEG/Run2015D-LogError-08Jun2016-v1/RAW-RECO is missing 50 files in phedex
http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=ReReco-Run2015D-08Jun2016-0001
fabozzi_Run2015D-DoubleEG-08Jun2016 is the name of the work flow

fabozzi_Run2015D-DoubleEG-08Jun2016_765p1_160608_195144_7236
jen_a_ACDC_Run2015D-DoubleEG-08Jun2016_765p1_160617_215626_2382
jen_a_ACDC_Run2015D-DoubleEG-08Jun2016_765p1_160617_215640_2676
jen_a_ACDC_Run2015D-DoubleEG-08Jun2016_765p1_160617_215659_5867
jen_a_recovery-5-fabozzi_Run2015D-DoubleEG-08Jun2016_765p1__160803_200845_5792

I also have the list of files so if that would be helpful I can add that as well.

I can fetch any further information that could be necessary
@vlimant

**Comment by ticoann** [comment] 2016-08-25 19:14
@scarletnorberg, Scarlet, could you add the list of missing files in PhEDEx? (You are saying there are 10/50 missing files in PhEDEx, compare to DBS?

**Comment by scarletnorberg** [comment] 2016-08-25 19:34
/DoubleEG/Run2015B-LogError-08Jun2016-v1/RAW-RECO for this WF
These 10 files are missing in phedex
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/90000/52EF229F-2535-E611-9CB7-0CC47A4C8F0A.root
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/464E5F4E-472F-E611-A01C-A0000420FE80.root
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/20AA5874-1430-E611-AC34-5065F3819221.root
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/90000/8E8B73A3-2535-E611-9F17-0CC47A4C8F08.root
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/58071D95-6C30-E611-A4C8-C4346BC84780.root
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/5A1D82AE-812F-E611-B2F7-001E67F337BC.root
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/90000/9400F363-9C35-E611-8A20-0CC47A78A4A6.root
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/341FE4E3-F830-E611-974B-0025905B85EE.root
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/FAB2E0A3-D92F-E611-92F4-0025905B85FE.root
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/910000/66E78A64-1E35-E611-8E1A-0CC47A4C8E96.root

**Comment by scarletnorberg** [comment] 2016-08-25 19:36
These are the 49 files missing from this work flow:
fabozzi_Run2015D-DoubleEG-08Jun2016_765p1_160608_195144_7236

These 49 files are missing in phedex 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/66C886C6-D02F-E611-A2DC-0025905A613C.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/60FC0AE0-0D31-E611-8063-001E67E5E8B6.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/80000/C0C00C3D-F836-E611-9AD8-0CC47A4D7600.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/80000/EC072B56-0836-E611-8A95-A0000420FE80.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/A8A2D3A8-2B2F-E611-9768-00266CFFBF50.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/20C8126C-7130-E611-9198-0025905A60CE.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/1A375404-CC2E-E611-97B7-00266CFFBE5C.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/710000/1221B716-4135-E611-B366-0025905A48D8.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/EE573658-2C30-E611-9FC6-0CC47A4D76CC.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/80000/0EFB5F85-7536-E611-BC0D-00266CFFCAA4.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/122C51C4-D02F-E611-AFC2-0CC47A4C8E38.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/DCA1AB05-C532-E611-8B2A-0CC47A4C8F12.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/40000/1464630E-4430-E611-B6D0-0025905B8596.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/BEEAD1E4-B930-E611-94B6-24BE05C668E1.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/90B23352-022F-E611-BF76-24BE05C60641.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/40000/6EF93BFA-B92E-E611-B959-0CC47A4D767E.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/80000/74C25C79-CF36-E611-9077-0CC47A4D762A.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/56EFF64C-F430-E611-BC8C-0CC47A4D7618.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/58A4F6F4-BE2F-E611-BBD6-5065F3819241.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/82EDB40F-0D31-E611-BE96-0025905A48FC.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/40000/EA84DD92-5830-E611-A77D-24BE05C4C891.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/20F2731F-B12F-E611-B7F2-24BE05C44BC1.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/90598DA4-5C31-E611-A226-0CC47A4D7632.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/40000/D26632D8-772F-E611-87EF-0CC47A4C8E56.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/0EBCD26A-B032-E611-9148-0025905A60CE.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/A44F5EC5-D02F-E611-80F0-0CC47A78A446.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/F8FCB14C-B735-E611-A93C-0CC47A4D7662.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/0E139E60-7730-E611-B7A5-A0000420FE80.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/40000/C407E8B3-EA2E-E611-831E-00266CFFCD6C.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/082EBAC4-1A61-E611-851E-0CC47A4D764A.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/D292A859-AE2F-E611-97FB-C4346BBCB6A8.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/80000/6066FF30-FF35-E611-92E7-0CC47A4D75F2.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/40000/C8E16F54-C12E-E611-AD2A-0002C94D5518.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/74514DC8-D02F-E611-9709-0025905A60DA.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/10B65451-B735-E611-BB57-0025905A6092.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/10457279-B62F-E611-B0DD-0CC47A78A4B0.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/524CCBC8-1A61-E611-B066-0CC47A4D7646.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/40000/3CCE5725-AC2F-E611-BA13-001E67F33618.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/D48EAD8B-012F-E611-9AD3-0CC47A78A458.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/94F14F97-C332-E611-A1A9-003048FFD72C.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/A852FE54-B131-E611-B6E4-24BE05C6E591.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/D4DFC0A8-8330-E611-9EDE-842B2B29FE8C.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/66DC11A4-5C31-E611-9D51-00248C55CC40.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/80000/1821B182-2936-E611-A231-0025905A6136.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/7CD3CBAD-F62F-E611-BFB1-00266CFEFDEC.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/710000/F0D0A611-4135-E611-BDCD-0CC47A4D7646.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/80000/1E075EDD-F836-E611-AC5D-0025905B8576.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/58BA8CD8-CB2E-E611-8095-24BE05CE2E81.root 
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/40000/B8D2CBEC-902F-E611-9A65-0002C94CD11C.root

**Comment by ticoann** [comment] 2016-08-26 03:40
Hmm, this is weird. I searched all the files above in all production agent.
Only following 2 files are found in the db (vocms0310),

```
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/082EBAC4-1A61-E611-851E-0CC47A4D764A.root
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/70000/524CCBC8-1A61-E611-B066-0CC47A4D7646.root
```

Even for these files, in wmbs they are marked as phedex injected.

I am not sure how this happen, I will investigate more tomorrow

**Comment by amaltaro** [comment] 2016-08-26 12:55
Just a small update on this. I checked the first two files for the first dataset, which maps to the following blocks:
```
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/90000/52EF229F-2535-E611-9CB7-0CC47A4C8F0A.root -> /DoubleEG/Run2015B-LogError-08Jun2016-v1/RAW-RECO#d60572c2-3527-11e6-9a9c-002590494fb0
/store/data/Run2015B/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/10000/464E5F4E-472F-E611-A01C-A0000420FE80.root -> /DoubleEG/Run2015B-LogError-08Jun2016-v1/RAW-RECO#20ce9caa-2f49-11e6-a2d6-a0369f23cf8a
```

both files are valid in DBS - which makes me believe there was NO PhEDEx invalidation - and the blocks are not in PhEDEx at all.

Checking oracle in vocms03{08,09,10,11}, I found only one LogError block which is not related to these files.

Then we have this list of agents, workflow name and number of files created for the LogError sample (according to the workloadSummary doc):
```
++ vocms0308
jen_a_ACDC_recovery-0-fabozzi_Run2015B-DoubleEG-08Jun2016_765p1__160818_214233_6617	# /DoubleEG/Run2015B-LogError-08Jun2016-v1/RAW-RECO, files: 1
++ vocms0309
jen_a_ACDC_Run2015B-DoubleEG-08Jun2016_765p1_160617_201953_7342 # /DoubleEG/Run2015B-LogError-08Jun2016-v1/RAW-RECO, files: 2
++ vocms0304
jen_a_ACDC_Run2015B-DoubleEG-08Jun2016_765p1_160617_201953_7342		# same as vocms0309
jen_a_ACDC_Run2015B-DoubleEG-08Jun2016_765p1_160617_202000_3164		# /DoubleEG/Run2015B-LogError-08Jun2016-v1/RAW-RECO, files: 1
jen_a_ACDC_Run2015B-DoubleEG-08Jun2016_765p1_160617_202006_7629		# /DoubleEG/Run2015B-LogError-08Jun2016-v1/RAW-RECO, files: 2
```

So, only a few files. We possibly missed these files from the original workflow, which ran at least in submit2. Though I don't know the other agents.

Since we don't have the data in the database anymore, I don't think there is anything else that we can do besides watch the the system and alarm/debug such issues in a shorter time.

**Comment by amaltaro** [comment] 2016-08-26 12:59
BTW, I don't discard losing these files at agent redeployment, though that's likely not to happen with all the checks we have in place...

**Comment by ticoann** [comment] 2016-08-26 16:15
@scarletnorberg, Scarlet, it seems there is actual problems in agent we need to investigate further.
I created the new issue for that. #7115

For this specific case we can inject files you provided manually in PhEDEx (I will ask Jorge whether he has script to do that) Is it OK?

**Comment by scarletnorberg** [comment] 2016-08-26 17:16
@vlimant That is fine. I am not sure how to do this now but I can look through the Twikis. If there is a script I am sure if there is a README file I can run it.

**Comment by ticoann** [comment] 2016-08-26 18:45
The script is what Jorge has. Basically checking dbs files and get proper information (checksum, file size, etc) and inject to PhEDEx.

**Comment by vlimant** [comment] 2016-08-29 10:11
Hi,
can the files lost for /DoubleEG/Run2015D-LogError-08Jun2016-v1/RAW-RECO in this agent issue be injected properly ?

**Comment by ticoann** [comment] 2016-08-29 16:35
Jorge injected 59 files Scarlet reported to PhEDEx. @scarletnorberg, could you check files are in sync?  In that case, we can close this ticket. We still need to investigate the cause of the problem (#7115)

**Comment by vlimant** [comment] 2016-08-30 10:10
/store/data/Run2015D/DoubleEG/RAW-RECO/LogError-08Jun2016-v1/40000/B8D2CBEC-902F-E611-9A65-0002C94CD11C.root  fell through the cracks

**Comment by ticoann** [comment] 2016-09-08 14:49
@vlimant, @scarletnorberg, Can we close this one?

**Comment by amaltaro** [comment] 2017-01-09 08:47
Closing it in favor of #7115

**Closed by amaltaro** 2017-01-09 08:47 UTC
Labels: Urgent (OPS)
