### ISSUE TITLE
Commission new robot certificate for CMSWEB central services

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11548] opened 2023-04-13 13:12 UTC
**Impact of the new feature**
All central services (special attention to MSUnmerged)

**Is your feature request related to a problem? Please describe.**
As discussed over Zoom and now reported in this GH issue:
https://github.com/dmwm/CMSKubernetes/issues/1353

we are looking into having dedicated robot certificate for central services, such that WMCore services don't share it with any of the other CMSWEB tenants (e.g. CRAB). This way we can better identify HTTP activity in the overall system.

**Describe the solution you'd like**
Apparently, @arooshap has done most of the work and there is nothing expected from our side (from her comment in the issue above). However, we still need to:
1) ensure this new certificate/DN has the same CRIC roles as the current one
2) ensure this new certificate/DN has the same VOMS attributes as the current one (production role for MSUnmerged!!!)
3) map this new DN to the relevant rucio accounts in Rucio Int (wmcore_transferor, wmcore_output and maybe wma_prod)
4) map this new DN to the relevant rucio accounts in Rucio Prod (wmcore_transferor, wmcore_output and maybe wma_prod)
5) Ensure that all of the above work fine
6) Ensure that MSUnmerged is able to delete unneeded unmerged files. If needed, 1 new WMCore ticket should be created to track all the sites that are failing to accept file removal (likely an artifact of authz based on the DN instead of VOMS attributes)

**Describe alternatives you've considered**
This ticket cannot be closed until everything is deployed in production and basic check of the services performed.

**Additional context**
None

**Comment by arooshap** [comment] 2023-05-11 08:18
Hi @amaltaro @todor-ivanov, any updates on this ticket? Because I need to give an update on the next Facilities and Services meeting on Monday.

**Comment by todor-ivanov** [comment] 2023-06-19 13:01
Hi @arooshap I fail to see a new robot certificate mounted  in the testbed  pods for WMCore. The one I see mounted at `/etc/robots` seems to be the old one. Can you give us a little bit more instructions here? Thanks!

**Comment by todor-ivanov** [comment] 2023-06-28 16:21
Just an update on this issue. 
The robot certificates have been updated by complete service redeployment and using this [PR](https://github.com/dmwm/CMSKubernetes/pull/1351/files) for updating the secrets file. 

We had a temporary failure to authenticate with Rucio, but upon Erik's intervention and adding the new DN to the account mapping for the `wmagent_transferor` account in the rucio integration service, we are having all services running well now. In general we should be doing it ourselves by following the instructions provided here: https://github.com/dmwm/WMCore/wiki/trouble-shooting#updating-dn-mapping-in-the-rucio-server 

What is left to be tested is the capability of MSUnmerged to delete files at sites by having the role `Production` role associated with the proxy to be used.

**Comment by amaltaro** [comment] 2023-06-28 16:24
@todor-ivanov you probably missed the recent discussion in DMWM mattermost channel. Summarizing it here, testbed was not functional for 5 days and Aroosha rolled back the previous certificate.

**Comment by todor-ivanov** [comment] 2023-07-03 09:40
Similarly to what @amaltaro has found last Friday about `ms-transferror` and the lack of mapping of `wmcore_trasferor` account to the new robot certificate we've just figured out the same error but with the `wma_test` account in `ms-rulecleaner`: 
```
2023-07-03 08:57:57,511:DEBUG:api: Encoding detection: ascii is most likely the one.
[03/Jul/2023:08:57:57]  ERROR: terminating due to error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Main.py", line 441, in start_daemon
    self.run()
  File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Main.py", line 502, in run
    self.install_application()
  File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Main.py", line 280, in install_application
    obj = getattr(module, class_name)(self, view, path)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/Service/RestApiHub.py", line 36, in __init__
    self._add({"status": Data(app, self, config, mount),
  File "/usr/local/lib/python3.8/site-packages/Utils/Patterns.py", line 13, in __call__
    super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/Service/Data.py", line 91, in __init__
    self.mgr = getattr(module, cname)(config)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSCore/MSManager.py", line 157, in __init__
    self.msRuleCleaner = MSRuleCleaner(self.msConfig, logger=self.logger)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py", line 80, in __init__
    super(MSRuleCleaner, self).__init__(msConfig, logger=logger)
  File "/usr/local/lib/python3.8/site-packages/WMCore/MicroService/MSCore/MSCore.py", line 47, in __init__
    self.rucio = Rucio(acct=self.msConfig['rucioAccount'],
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Rucio/Rucio.py", line 86, in __init__
    self.cli = Client(rucio_host=hostUrl, auth_host=authUrl, account=acct,
  File "/usr/local/lib/python3.8/site-packages/rucio/client/client.py", line 77, in __init__
    super(Client, self).__init__(**args)
  File "/usr/local/lib/python3.8/site-packages/rucio/client/baseclient.py", line 282, in __init__
    self.__authenticate()
  File "/usr/local/lib/python3.8/site-packages/rucio/client/baseclient.py", line 929, in __authenticate
    self.__get_token()
  File "/usr/local/lib/python3.8/site-packages/rucio/client/baseclient.py", line 822, in __get_token
    if not self.__get_token_x509():
  File "/usr/local/lib/python3.8/site-packages/rucio/client/baseclient.py", line 693, in __get_token_x509
    raise exc_cls(exc_msg)
rucio.common.exception.CannotAuthenticate: Cannot authenticate.
Details: Cannot authenticate to account wma_test with given credentials
```
I am about to create  the mapping for this in rucio integration, following the instructions provided here: https://github.com/dmwm/WMCore/wiki/trouble-shooting#updating-dn-mapping-in-the-rucio-server , but I doubt I can do it for rucio production server.

**Comment by todor-ivanov** [comment] 2023-07-03 10:10
it is fixed now

**Comment by todor-ivanov** [comment] 2023-07-03 19:04
Just a note here:
I just added the mapping for the new robot certificate to `wma_prod` in `cms-rucio.cern.ch` similarly to `wma_test` in `cms-rucio-int.cern.ch`. 

FYI: @amaltaro

**Comment by todor-ivanov** [comment] 2023-07-03 19:11
As  discussed during our meeting earlier today and upon thorough looking in the logs of all WMCore services in testbed, I can confirm that, modulo the `MSUnmerged`  service which is experiencing a completely different issue, we can confirm that the new certificate has all proper mappings in both CRIC and Rucio. 

I am closing this issue with the current comment, and will follow the `MSUnmerged` debugging and eventual certificate authorization validation per site in https://github.com/dmwm/WMCore/issues/11637

**Closed by todor-ivanov** 2023-07-03 19:11 UTC
Labels: Medium Priority, Feature change, Stakeholders, QPrio: High

**Comment by amaltaro** [comment] 2023-07-03 19:13
Thanks Todor! Just making sure we do not have surprises when moving to production, did you also create the `wma_prod` mapping in Rucio Prod? As discussed during our team meeting.

**Comment by todor-ivanov** [comment] 2023-07-03 19:15
hi @amaltaro 
> id you also create the wma_prod mapping in Rucio Prod

https://github.com/dmwm/WMCore/issues/11548#issuecomment-1619019440

**Comment by amaltaro** [comment] 2023-07-05 16:14
Thanks Todor. BTW, are we - by default - deploying now services (dev / testbed / production) with the new certificate? If not, then you still need to coordinate with Aroosha and make sure her changes are merged to (CMSKubernetes) master. @todor-ivanov

**Comment by arooshap** [comment] 2023-07-05 16:44
@amaltaro yes, you don't have to make any changes from your side. It is something cluster-wide, and I kept the naming convention the same to avoid having to do changes in the services manifests.

**Comment by todor-ivanov** [comment] 2023-07-05 17:33
I have just checked  and it seems all the pods are already having the new robot certificate and proxy
So I think we are good to proceed with our validation.

**Comment by amaltaro** [comment] 2023-07-05 17:58
@todor-ivanov @arooshap thank you for the confirmation!
