### ISSUE TITLE
Missing error message in wmstats

### ISSUE THREAD

**Issue by jhonatanamado** [dmwm/WMCore#11275] opened 2022-09-07 14:01 UTC
**Impact of the bug**
wmstats not showing error message from T0 agent

**Describe the bug**
Since the 2nd of Sept, wmstats is taking a considerable amount of time to show wfs in the request alert tab. After ~10-20 minutes finally it appears in the request alert tab but the error message is not showed. This happened with the following two workflows.
`PromptReco_Run358283_MinimumBias ` and `Express_Run358509_StreamCalibration` where a single job per wf was in state paused. The table showing the task, status, site and exit code shows the message `No data available in table`.
Even after the jobs were resubmitted, the state of the job was not updated from `Paused` to `running` in wmstats and the wf in the request tab disappeared after a considerable amount of time

**How to reproduce it**

**Expected behavior**
Error message should appear once the wf is showed in the request alert tab

**Additional context and error message**

- T0 tracks the paused jobs in Grafana but just showing a quantitative description (how many paused jobs we have in the system). And this issue about not showing the error message happened even after 2 days where a promptreco job was paused.
<img width="1616" alt="PausedJobs" src="https://user-images.githubusercontent.com/50465903/188895868-f279405a-ba5b-4d4d-af62-85aa31a1a046.png">

**Comment by amaltaro** [comment] 2022-09-30 20:17
@jhonatanamado do I understand it right that both the "alert" and the "requests" tab were missing some job details?

AFAIK this information gets propagated from the agent, through CouchDB replication. The agent updates both the relational and couch databases, and in a few minutes this gets propagated to central tier0 wmstats.

I don't think there is much that we can do without looking at the system whenever it happens again. It could be that something is down, it could be that we have soft failures here and there allowing couchdb document to stay like this, or it could be that we actually have some sort of problem with central tier0 wmstats.

Regarding having those requests vanishing from the system. This is likely a consequence of having the agent "archiving" them.

**Comment by jhonatanamado** [comment] 2022-09-30 20:34
> do I understand it right that both the "alert" and the "requests" tab were missing some job details?

yes

> I don't think there is much that we can do without looking at the system whenever it happens again. It could be that something is down, it could be that we have soft failures here and there allowing couchdb document to stay like this.

I agree. Now T0 is monitoring how much it takes for some components of the agent to update between cycles. If this happen again I can come back with more evidence on what's going on.

> or it could be that we actually have some sort of problem with central tier0 wmstats.

Do you know how can T0 monitor those problems in central wmstats?


@amaltaro, Alan feel free to close this issue and I will reopen if this happens again.

**Comment by germanfgv** [comment] 2023-03-20 10:41
We are bringing attetntion back to this issue after we have noticed a few more occurrences. Checking RetryManager for logs on the stateupdate from failed to paused, we found a series of `doc is null` errors:
```
2023-03-14 17:48:29,119:140412728809216:ERROR:ChangeState:Error updating job in couch: CouchInternalServerError - reason: Internal Server Error, data: None result: b'{"error":"render_error","reason":"function raised error: (new TypeError(\\"doc is null\\", \\"updates.jobSum
maryState\\", 2)) \\nstacktrace: (null,[object Object])@updates.jobSummaryState:2\\nrunUpdate(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \\"OK\\"];},[object Object],[object Array])@./share/server/main.js:10
52\\n(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \\"OK\\"];},[object Object],[object Array])@./share/server/main.js:1143\\n(\\"_design/WMStatsAgent\\",[object Array],[object Array])@./share/server/main.js:1
621\\n()@./share/server/main.js:1667\\n()@./share/server/main.js:1688\\n@./share/server/main.js:1\\n"}\n'
2023-03-14 17:48:29,123:140412728809216:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 131, in makeRequest
    result, status, reason, cached = JSONRequests.makeRequest(
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 185, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 202, in makeRequest_pycurl
    response, result = self.reqmgr.request(uri, data, headers, verb=verb,
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 353, in request
    raise exc
http.client.HTTPException: url=http://localhost:5984/wmagent_summary/_design/WMStatsAgent/_update/jobSummaryState/Repack-79b81198-9b22-41a9-aae6-fde115e81202?newstate=jobpaused&timestamp=1678812509, code=500, reason=Internal Server Error, headers={'Cache-Control': 'must-rev
alidate', 'Content-Length': '741', 'Content-Type': 'application/json', 'Date': 'Tue, 14 Mar 2023 16:48:28 GMT', 'Server': 'CouchDB/3.2.2 (Erlang OTP/22)', 'X-Couch-Request-ID': '4ccc4d1150', 'X-CouchDB-Body-Time': '0'}, result=b'{"error":"render_error","reason":"function ra
ised error: (new TypeError(\\"doc is null\\", \\"updates.jobSummaryState\\", 2)) \\nstacktrace: (null,[object Object])@updates.jobSummaryState:2\\nrunUpdate(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \\"OK\
\"];},[object Object],[object Array])@./share/server/main.js:1052\\n(function (doc, req) {doc.state = req.query.newstate;doc.timestamp = parseInt(req.query.timestamp);return [doc, \\"OK\\"];},[object Object],[object Array])@./share/server/main.js:1143\\n(\\"_design/WMStatsA
gent\\",[object Array],[object Array])@./share/server/main.js:1621\\n()@./share/server/main.js:1667\\n()@./share/server/main.js:1688\\n@./share/server/main.js:1\\n"}\n'
```

**Comment by germanfgv** [comment] 2023-03-20 10:59
Tracking the missing docs issue, we found two error JobAccountant logs that might be related to the issue:

 1. Request Entity Too Large Error (The full object is too long to print here)
 ```
 2023-03-16 19:11:40,498:140097117923072:INFO:AccountantWorker:Job 326378 , handle successful job
2023-03-16 19:11:44,289:140097117923072:ERROR:ChangeState:Error updating job in couch: NEW ERROR STATUS! UPDATE CMSCOUCH.PY!: 413
CouchError - reason: Request Entity Too Large, data: {'docs': [{'_id': '72181-0', 'jobid': 72181, 'jobtype': 'Merge', 'jobstate': 'success', 'retrycount': 0, 'archivestatus': 'ready', 'fwjr': {'WorkerNodeInfo': {'HostName': 'b7g20p7303.cern.ch', 'MachineFeatures': {'hs06': None, 'total_cpu': None}, 'JobFeatures':...
2023-03-16 19:11:44,816:140097117923072:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/3.0.7/sw/slc7_amd64_gcc630/cms/t0/3.0.7/lib/python3.8/site-packages/WMCore/Database/CMSCouch.py", line 131, in makeRequest
    result, status, reason, cached = JSONRequests.makeRequest(
  File "/data/tier0/srv/wmagent/3.0.7/sw/slc7_amd64_gcc630/cms/t0/3.0.7/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 173, in makeRequest
    result, response = self.makeRequest_pycurl(uri, data, verb, headers)
  File "/data/tier0/srv/wmagent/3.0.7/sw/slc7_amd64_gcc630/cms/t0/3.0.7/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 190, in makeRequest_pycurl
    response, result = self.reqmgr.request(uri, data, headers, verb=verb,
  File "/data/tier0/srv/wmagent/3.0.7/sw/slc7_amd64_gcc630/cms/t0/3.0.7/lib/python3.8/site-packages/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/data/tier0/srv/wmagent/3.0.7/sw/slc7_amd64_gcc630/cms/t0/3.0.7/lib/python3.8/site-packages/WMCore/Services/pycurl_manager.py", line 341, in request
    raise exc
 ```
 1. KeyError: 'TotalJobCPU'
 ```
 2023-03-14 17:01:57,013:140412740974336:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 178, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 361, in recordInCouch
    updateSummaryDB(self.statsumdatabase, job)
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 167, in updateSummaryDB
    sum_doc = fwjr_parser(document)
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 86, in fwjr_parser
    pdict['totalJobCPU'] += float(perf['cpu']['TotalJobCPU'])
KeyError: 'TotalJobCPU'

 ```
 
We didn't find anything in JobCreator's logs

**Comment by todor-ivanov** [comment] 2023-03-20 12:32
Thanks @germanfgv

**Comment by germanfgv** [comment] 2023-03-20 17:57
I reproduced the error in a replay. You can find the agent in vocms001. The paused job withoud documents is 976, from workflow `Repack_Run364706_StreamRPCMON_Tier0_REPLAY_2023_ID230224170514_v24170514`. You can check https://cmsweb-testbed.cern.ch/tier0_wmstats/index.html to see that the error appears reported in `Request Alerts`, but there is no info about the paused job in the active request tab.

**Comment by germanfgv** [comment] 2023-03-20 18:27
This is the only paused job in this machine. 

**RetryManager**
I see the `doc is null` error in RetryManager, just as it tries to change the job state from Cooloff to Paused.

**JobAccountant** 
Shows the `TotalJobCPU` error when failing this job.
```
2023-03-20 15:12:43,655:139904782075648:ERROR:AccountantWorker:Job 976, expected output modules: ['logArchive', 'write_RPCMonitor_RAWRAW'], but has FWJR output modules: ['logArchive']
2023-03-20 15:12:43,656:139904782075648:WARNING:AccountantWorker:Job 976 , bad jobReport, failing job
2023-03-20 15:12:43,661:139904782075648:DEBUG:AccountantWorker:Job 976 , register output /store/unmerged/data/logs/prod/2023/3/20/Repack_Run364706_StreamRPCMON_Tier0_REPLAY_2023_ID230224170514_v24170514/Repack/0000/3/Repack-f1067a24-321d-4451-84db-c3f44e5c7efb-3-logArchive.
tar.gz
2023-03-20 15:12:43,713:139904782075648:ERROR:ChangeState:Error updating job in couch: 'TotalJobCPU'
2023-03-20 15:12:43,713:139904782075648:ERROR:ChangeState:Traceback (most recent call last):
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 178, in propagate
    self.recordInCouch(jobs, newstate, oldstate, updatesummary)
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/JobStateMachine/ChangeState.py", line 361, in recordInCouch
    updateSummaryDB(self.statsumdatabase, job)
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 167, in updateSummaryDB
    sum_doc = fwjr_parser(document)
  File "/data/tier0/srv/wmagent/3.0.8/sw/slc7_amd64_gcc630/cms/t0/3.0.8/lib/python3.8/site-packages/WMCore/JobStateMachine/SummaryDB.py", line 86, in fwjr_parser
    pdict['totalJobCPU'] += float(perf['cpu']['TotalJobCPU'])
KeyError: 'TotalJobCPU'
``` 
**JobStatusLite**
No errors

**JobCreator**
No errors

**Comment by germanfgv** [comment] 2023-03-20 19:19
You can find the logs for the job in:
```
/afs/cern.ch/user/c/cmst0/public/PausedJobs/MissingWMStats/job_976
```
Looking into the `Report.3.pkl` file, I see that, indeed, it does not contain a performance section, while other jobs have something like this:
```
FrameworkJobReport.cmsRun1.performance.cpu.TotalInitCPU = '10.0565'
FrameworkJobReport.cmsRun1.performance.cpu.TotalJobCPU = '262.213'
FrameworkJobReport.cmsRun1.performance.cpu.TotalLoopCPU = '244.701'
```

This is a job that had a segmentation fault in CMSSW due to a streamer file incompatibility. I guess the fact that the job whent to segmentation fault prevented the acquisition of performance info?

**Comment by amaltaro** [comment] 2023-04-06 18:16
Moving this one from Q1 to Q2, still a work in progress item.

**Closed** 2023-05-17 02:37 UTC
Labels: BUG, WMAgent, High Priority, WMStats, Tier0-systems, QPrio: High
