### ISSUE TITLE
[py2py3] validate Services/DBS/DBS3Reader.py - slice 8

### ISSUE THREAD

**Issue by mapellidario** [dmwm/WMCore#10293] opened 2021-02-16 18:33 UTC
**How to reproduce it**

We have not seen any bug yet, but it is likely that the changes to `Services/DBS/DBS3Reader.py` introduced in #10289 will break something.

**Describe the bug**

`Services/DBS/DBS3Reader.py` required major changes in strings management, wihch is always troublesome. For more information look directly at the changes in #10289 

**Impact of the bug**

Not sure yet

**Expected behavior**

This modernization should make `Services/DBS/DBS3Reader.py` compatible with both py2 and py3. Moreover, it should behave in both py2 and py3 as it behaved in py2 before #10289

**Comment by amaltaro** [comment] 2021-02-18 19:42
Just a note from the slice 8 review, as discussed along the code, in case it gets lost.

Some pieces of DBS3Reader module seem to cast python2 strings (sequence of bytes) to unicode (sequence of code points), code like:
```
        # Pointless code in python3
        if isinstance(block, str):
            block = unicode(block)
        if isinstance(dataset, str):
            dataset = unicode(dataset)
```
which has now been modernized to:
```
        block = decodeBytesToUnicode(block)
```

A thoroughly investigation is required for that (not now though!), but I have a feeling that that code is not really necessary and it's probably some legacy code from DBS2 era. Something to keep in mind.

**Comment by belforte** [comment] 2021-02-21 09:54
maybe all part of the old confusion between JSON and a dictionary printout ?

**Comment by amaltaro** [comment] 2021-08-17 10:39
DBS3Reader seems to be working properly in Py3 WMAgent `>= 1.5.2.pre2`.
Still to be confirmed from a Py2 stack though, via a T0 replay.

**Comment by amaltaro** [comment] 2021-08-30 07:57
The T0 team is migrating the T0 agent to python3, and since this has been fully validated in Python3, I'm closing this issue (we can always reopen it if a new issue is found in this module).

NOTE: there is this open issue that can affect DBS3Reader: https://github.com/dmwm/WMCore/issues/10745
however, this is a problem on the dbs3-client package.

**Closed by amaltaro** 2021-08-30 07:57 UTC
Labels: High Priority, Python3, py3 potential bug, Testing
