### ISSUE TITLE
Handling Blocks with only Invalid Files

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7441] opened 2016-12-02 08:28 UTC
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_BTV-RunIISummer16MiniAODv2-00029_00039_v0__161122_005312_2045

is in assigned, with one block 
/QCD_Pt-15to20_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISummer16DR80Premix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v2/AODSIM#63bcf038-ae2a-11e6-97bb-02163e0184a6
not complete anywhere. Is this the reason for not moving to acquired and will this move if the block gets wiped out? 

More info in #7466

**Comment by amaltaro** [comment] 2016-12-02 09:24
It will get acquired once we have this block complete in one of the expected locations:
https://cmsweb.cern.ch/phedex/datasvc/xml/prod/blockreplicas?block=/QCD_Pt-15to20_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISummer16DR80Premix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v2/AODSIM%2363bcf038-ae2a-11e6-97bb-02163e0184a6

Though I also think that piece of code could be improved and not crash in GQ.

**Comment by vlimant** [comment] 2016-12-02 09:46
the block is doomed IMO as that block has been deleted somehow. If the block disappears from TMDB, would that work ?

**Comment by ticoann** [comment] 2016-12-02 15:56
> the block is doomed IMO as that block has been deleted somehow. If the block disappears from TMDB, would that work ?

No, it wouldn't work. So we don't have any replica for this block?

Alan, Was this crashing the GQ?

**Comment by amaltaro** [comment] 2016-12-02 21:43
As Seangchan said, if data is not in TMDB, then there is no way to get it working.

Seangchan, yes, you can have a look at today's workqueue log (vocms0140). Otherwise I'll check it in the next week

**Comment by ticoann** [comment] 2016-12-03 15:39
HI Alan, I tried to look at vocms0140 log but it seems there is no work queue log /srv-log/vocms0140

**Comment by amaltaro** [comment] 2016-12-05 16:16
Seangchan, you can have a look at vocms022:/build/srv-logs/vocms0140/workqueue/workqueue-20161201.log

in any case, I paste it here before that gets lost/archived:
```
2016-12-01 01:05:03,648 INFO     WorkQueueReqMgrInterface: Processing request pdmvserv_BTV-RunIISummer16MiniAODv2-00029_00039_v0__161122_005312_2045 at https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_BTV-RunIISummer16MiniAODv2-00029_00039_v0__161122_005312_2045/spec
2016-12-01 01:05:03,648 INFO     WorkQueue: queueWork() begin queueing "https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/pdmvserv_BTV-RunIISummer16MiniAODv2-00029_00039_v0__161122_005312_2045/spec"
2016-12-01 01:05:04,389 INFO     WorkQueue: Resume splitting of "pdmvserv_BTV-RunIISummer16MiniAODv2-00029_00039_v0__161122_005312_2045"
2016-12-01 01:05:04,639 INFO     WorkQueue: Splitting /pdmvserv_BTV-RunIISummer16MiniAODv2-00029_00039_v0__161122_005312_2045/StepOneProc with policy Block params = {'ResubmitBlock': {'args': {}, 'name': 'ResubmitBlock'}, 'MonteCarlo': {'args': {}, 'name': 'MonteCarlo'}, 'Dataset': {'args': {}, 'name': 'Dataset'}, 'Block': {'args': {}, 'name': 'Block'}, 'DatasetBlock': {'args': {}, 'name': 'Block'}}
2016-12-01 01:05:17,206 ERROR    WorkQueue: Exception splitting wqe pdmvserv_BTV-RunIISummer16MiniAODv2-00029_00039_v0__161122_005312_2045 for pdmvserv_BTV-RunIISummer16MiniAODv2-00029_00039_v0__161122_005312_2045: '/QCD_Pt-15to20_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISummer16DR80Premix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v2/AODSIM#63bcf038-ae2a-11e6-97bb-02163e0184a6'
2016-12-01 01:05:17,648 ERROR    WorkQueueReqMgrInterface: Unknown error processing pdmvserv_BTV-RunIISummer16MiniAODv2-00029_00039_v0__161122_005312_2045
Traceback (most recent call last):
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/workqueue/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 104, in queueNewRequests
    units = queue.queueWork(workLoadUrl, request=reqName, team=team)
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/workqueue/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 630, in queueWork
    work = self.processInboundWork(inbound, throw=True)
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/workqueue/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1073, in processInboundWork
    continuous=continuous)
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/workqueue/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1019, in _splitWork
    units, rejectedWork = policy(spec, topLevelTask, data, mask, continuous=continuous)
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/workqueue/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py", line 142, in __call__
    self.split()
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/workqueue/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/Block.py", line 36, in split
    for block in self.validBlocks(self.initialTask, dbs):
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/workqueue/1.0.22.pre10/lib/python2.7/site-packages/WMCore/WorkQueue/Policy/Start/Block.py", line 188, in validBlocks
    self.data[block['block']] = self.siteDB.PNNstoPSNs(dbs.listFileBlockLocation(block['block']))
  File "/data/srv/beHG1611o/sw/slc6_amd64_gcc493/cms/workqueue/1.0.22.pre10/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 666, in listFileBlockLocation
    return locations[singleBlockName]
KeyError: '/QCD_Pt-15to20_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/RunIISummer16DR80Premix-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v2/AODSIM#63bcf038-ae2a-11e6-97bb-02163e0184a6'
```

**Comment by ticoann** [comment] 2016-12-05 16:39
Thanks Alan, stupid me! I was looking at vocms140 not vocms0140. Thanks

**Comment by vlimant** [comment] 2016-12-12 22:48
How did this go forward ?

**Comment by ticoann** [comment] 2016-12-13 06:04
How many ways this can happen? (Block is deleted from TMDB)
I mean there could be some legit case as well as error case?

Alan and I discussed about this, what we think is we should just report (alarm) if the block doesn't have the location, instead of doing anything automatically (Mark the block Canceled or Done). unless if we can validate the cause of this automatically.

**Comment by amaltaro** [comment] 2016-12-13 10:17
I think we should:
1. get the block location
2. if empty, then fallback to another phedex call for # of files within that block in (TMDB)
3. if 0, then - still not clear - we either
3.a. create the workqueue element and mark it Canceled
3.b. don't even create the workqueue element, simply reject this block and MAYBE report it to logDB.

Comments?

**Comment by amaltaro** [comment] 2016-12-15 08:21
I had a look at the code and we already handle these blocks with invalid files only, see this start policy (same for the Dataset policy):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Dataset.py#L106

This NumberOfFiles comes from a dbs call for valid files only:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L374

such that those blocks are skipped from work (wqe) creation.

The harvesting workflow that went through (after patching the agents again) is a prove that it works now.

So I'm closing this issue. If you consider this problem is still there, please reopen.

**Closed by amaltaro** 2016-12-15 08:21 UTC

**Comment by vlimant** [comment] 2017-01-20 14:07
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_HIG-RunIISummer16DR80Premix-00209__v1_T_170105_140314_3378 is sitting in assigned because some blocks are only in dbs
https://cmsweb.cern.ch/das/request?input=block%3D%2FTTToHplusToWZprime_WToENu_ZToMuMu_MH-140_MZ-5_13TeV-madgraph%2FRunIISummer15wmLHEGS-MCRUN2_71_V1-v1%2FGEN-SIM%235d4ab96c-9230-11e6-8fc0-001e67abf518&instance=prod%2Fglobal
https://cmsweb.cern.ch/das/request?input=block%3D%2FTTToHplusToWZprime_WToENu_ZToMuMu_MH-140_MZ-5_13TeV-madgraph%2FRunIISummer15wmLHEGS-MCRUN2_71_V1-v1%2FGEN-SIM%236d618bba-9298-11e6-840c-001e67abf518&instance=prod%2Fglobal

/TTToHplusToWZprime_WToENu_ZToMuMu_MH-140_MZ-5_13TeV-madgraph/RunIISummer15wmLHEGS-MCRUN2_71_V1-v1/GEN-SIM @sidnarayanan

**Comment by amaltaro** [comment] 2017-01-20 14:42
The first fix (which is in production right now) is buggy. The second fix made to WMCore:
#7457 will fix this issue in the next cmsweb deployment. Can you please blacklist these blocks?

**Comment by vlimant** [comment] 2017-01-20 15:03
@prozober will do

**Comment by prozober** [comment] 2017-01-21 00:32
I blacklisted those blocks in the clone
https://cmsweb.cern.ch/reqmgr2/fetch?rid=prozober_task_HIG-RunIISummer16DR80Premix-00209__v1_T_170120_180043_4823
but still, the clone is sitting in assigned.

**Comment by amaltaro** [comment] 2017-01-23 08:15
Seems to be hitting the same issue as reported by JR in #7534 , this block is not completed anywhere:
/TTToHplusToWZprime_WToENu_ZToMuMu_MH-140_MZ-5_13TeV-madgraph/RunIISummer15wmLHEGS-MCRUN2_71_V1-v1/GEN-SIM#b1026b82-91f8-11e6-8fc0-001e67abf518
