### ISSUE TITLE
Create monitoring or alerts for workflows failing in MSTransferor

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10215] opened 2021-01-11 11:41 UTC
**Impact of the new feature**
MSTransferor

**Is your feature request related to a problem? Please describe.**
If a workflow fails to be processed by MSTransferor, the only way to spot those - and see what the error is - is by scanning the service logs from CMSWEB. Thus, we should make it easier to access this information, either with some sort of monitoring; or via push notifications/alerts.

**Describe the solution you'd like**
A final solution isn't well defined yet. However, a few options that I could list now are:
a) push details to the LogDB, in central CouchDB, via `error logs` WMStats tab
b) send email alerts. Need to make sure not to spam too much with duplicated alerts
c) maybe, setup something in MonIT
d) or perhaps, provide this information through some REST API (still, someone would have to spot those workflows stuck in assigned)

any other suggestions?

The error description does not necessarily need to be a log of the workflow processing in MSTransferor, but a clear message identifying why the workflow does not move forward in the service.

**Describe alternatives you've considered**
A few described above, now we need to agree on one of them.

**Additional context**
none

**Comment by vkuznet** [comment] 2021-01-11 13:20
Alan, why not to use CMS Monitoring infrastructure for that. We have everything in place to setup alerts and integrate them into whatever channel of notification you may prefer. For that we use AlertManager service running in our k8s cluster. It collects and process all alerts from our dashboards and CLI tools.  In your case you may write full details to LogDB and send alert notification through `amtool` (see below). Doing this way you'll have persistent info in LogDB and alert will be integrated in CMS Monitoring infrastructure. The alert can be redirected to different channels like email, slack, etc.

To send an alert you may use `/cvmfs/cms.cern.ch/cmsmon/amtool`. And, here is an example how it can be called:
```
# in this example we setup cron4phedex alert

# set appropriate alert message
msg="cron4phedex completed with non zero status"
# set alert expire timestamp
expire=`date -d '+1 hour' --rfc-3339=ns | tr ' ' 'T'`
# setup command we used
cmd="cron4phedex"
# send alert, as you can see you can set severity, tag values, add annotations, etc.
amtool alert add cron4phedex \
                 alertname=cron4phedex severity=medium tag=cronjob alert=amtool \
                 --end=$expire \
                 --annotation=summary="$msg" \
                 --annotation=date="`date`" \
                 --annotation=hostname="`hostname`" \
                 --annotation=status="$status" \
                 --annotation=command="$cmd" \
                 --annotation=log="$log" \
                 --alertmanager.url=http://cms-monitoring.cern.ch:30093
```

The only limitation is that amtool should send alert to our cms-monitoring service accessible within CERN network.

**Comment by vkuznet** [comment] 2021-01-11 13:23
For the monitoring itself, I strongly suggest to either use exporter and/or REST end-point for which we can add new exporter. Then everything will be integrated in CMS Monitoring and we can can easily create MONIT dashboard for your set of metrics. The exporter can provide any set of meta-data and it is not that hard to write. The benefits will be that everything will be integrated and we can create dashbaord as we're doing for many services.

**Comment by amaltaro** [comment] 2021-01-11 13:59
Thanks for this feedback, Valentin.

> To send an alert you may use /cvmfs/cms.cern.ch/cmsmon/amtool. And, here is an example how it can be called:

Do you know whether we mount CVMFS on the kubernetes environment (pods?)? 

> The only limitation is that amtool should send alert to our cms-monitoring service accessible within CERN network.

MSTransferor is a central service, so it runs within the CERN network and it should not be a problem.

I'm still not sure whether I would like to have such hard dependency though, on CVMFS. Is there any other option - if possible through HTTP/REST calls - that we could create an alert in the CMS Monitoring infrastructure?

**Comment by vkuznet** [comment] 2021-01-11 14:23
Alan, even though we can access CVMFS from pods, you don't have to. The amtool is static executable (it's Go :) which you can just copy to your pod, or add it to Dockerfile of your service. For instance:
```
# download alertmanager
curl -ksLO https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
# untar
tar tvfz alertmanager-0.21.0.linux-amd64.tar.gz
drwxr-xr-x circleci/circleci 0 2020-06-17 11:35 alertmanager-0.21.0.linux-amd64/
-rwxr-xr-x circleci/circleci 28871879 2020-06-17 10:54 alertmanager-0.21.0.linux-amd64/alertmanager
-rwxr-xr-x circleci/circleci 23987848 2020-06-17 10:55 alertmanager-0.21.0.linux-amd64/amtool
-rw-r--r-- circleci/circleci      457 2020-06-17 11:34 alertmanager-0.21.0.linux-amd64/NOTICE
-rw-r--r-- circleci/circleci    11357 2020-06-17 11:34 alertmanager-0.21.0.linux-amd64/LICENSE
-rw-r--r-- circleci/circleci      380 2020-06-17 11:34 alertmanager-0.21.0.linux-amd64/alertmanager.yml

# use amtool
./alertmanager-0.21.0.linux-amd64/amtool --help
usage: amtool [<flags>] <command> [<args> ...]
...
```

**Comment by scarletnorberg** [comment] 2021-04-21 14:50
Possible MSTransfer issue: https://its.cern.ch/jira/browse/CMSCOMPPR-18772

**Comment by todor-ivanov** [comment] 2021-04-21 16:14
Thanks for mentioning it here  @scarletnorberg. The problem is actually traced in this dedicated issue now:
https://github.com/dmwm/WMCore/issues/10464

**Comment by amaltaro** [comment] 2021-07-02 15:47
This is meant to be lower priority than #10061 (provided by Hasan in the Q3 planning).

**Closed** 2022-02-15 21:19 UTC
Labels: New Feature, High Priority, Further Discussion, Monitoring, MSTransferor, Stakeholders
