### ISSUE TITLE
scram arch validation doesn't work (reliably) ?

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#7411] opened 2016-11-22 19:20 UTC
Testing WMCore master in the Tier0, this line

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L949

triggers the ScramArch of the request being checked against the TagCollector, an external service.

Independent of having parameter validation rely on an external service (which IMO is a bad idea), this doesn't work currently. Somewhere deep in the code there is a failure to contact the external service

{"reason": "HTTPError, url=https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML?anytype=1, args={}, headers={}, error=<urlopen error [Errno -2] Name or service not known>", "error": "Unable to contact https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML?anytype=1"}

which then throws an exception trying to parse the return xml of the call since no error checking is done.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Tools/cms.py#L50

**Comment by hufnagel** [comment] 2016-11-22 19:20
@amaltaro , I assume you added this ?

**Comment by hufnagel** [comment] 2016-11-22 19:28
Same thing for validation of CMSSWVersion btw.

**Comment by amaltaro** [comment] 2016-11-22 21:08
There should be a cache for this data. Where are you testing it? Maybe it fails if the cache is expired and we cannot contact tagCollector... I'll investigate it tomorrow.

But for the record, I haven't had a single problem with this case in all the validations we have been running for the last weeks (this includes Jenkins).

**Comment by hufnagel** [comment] 2016-11-22 21:30
I am testing on vocms001, Tier0 vobox.

**Comment by amaltaro** [comment] 2017-02-23 14:30
@johnhcasallasl  John asked me about this issue again - since it's hitting a T0 replay instance - and it turns out T0 is still deploying a non-production release (1.1.0.pre6) [*] Please move to the latest pre-release in the cycle, in this case `1.1.0.pre10`. It has a fix for TagCollector such that it can fetch all CMSSW releases in all ScramArchs. That will solve the "reliability" problem :-)

[*] other weird thing is that according to the files path, the tier0 WMAgent is supposedly running 1.0.20.pre5 ?? Aren't you guys updating the WMAgent RPM to be deployed?
`sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.0.20.pre5-comp/`

Can you guys please fix it, report here the outcome and if everything is fine, close this issue? Thanks

**Comment by hufnagel** [comment] 2017-02-23 17:41
Tier0 releases are decoupled from WMAgent. We don't care about the WMAgent production releases since we have to build T0 releases at our own schedule with very limited possibility to do upgrades.

@johnhcasallasl , just find out which patch is needed and add the cherry-pick instructions to the 2.0.6 release twiki.

**Comment by amaltaro** [comment] 2017-02-23 18:08
Your comment is, at the very least, funny :) The Tier0 "agent" runs most of the WMAgent code and you say it doesn't matter?

You can do whatever is best for the moment, but in the future, I suggest you to always consult me/Seangchan and get the latest *production* release. Just my 2cents

**Comment by ticoann** [comment] 2017-02-23 19:23
Dirk, I think it is time for T0 WMCore branch. 😄

**Comment by ericvaandering** [comment] 2017-02-23 19:25
Past time. :-)

**Comment by hufnagel** [comment] 2017-02-23 21:58
The more I think about it, the more I think it wouldn't help. Tier0 has no defined release building schedule, therefore what good would the Tier0 branch be for ? Just extra overhead compared to using exisiting WMCore tags.

Tier0 releases are build so infrequently, I just use the latests WMCore at the time, test things, fix problems with it as I find them and then make a release. If we find other problems later they are just added as patched to the release.

**Comment by amaltaro** [comment] 2017-02-23 22:08
Yep, I don't think the tier0 branch can be that useful as well, unless T0 agent is based on a production tag and you have patches on top of that.

Otherwise, my general suggestion to you would be to always use the latest WMCore `pre` tag, since this is what's deployed and it's largely validated (central services wise). Otherwise you could use the final (production release as well) that usually carries a few agent-only fixes and/or features, e.g. `1.1.0.pre10` and `1.1.0` should be basically the same, besides a few agent-side fixes that would be in `1.1.0`.

**Comment by ticoann** [comment] 2017-02-23 22:16
Hi Dirk, I am not suggesting that create the branch for start of the test. 
Once T0 Agent deployed in production we can create the branch and keep track of what is updated. Since T0Agent is updated infrequently. I think it is useful for the patch management. 

I am not sure how T0 manages those patches and handling more patches if necessary.
But if you are already keeping the record and have own systemic way, branch might be the redundant. Or instead of keeping the record separately we can just do that in GitHub branch. 
Anyway, if you think branching T0 will be overhead. I am fine with whatever T0 is doing for patch management.

**Comment by hufnagel** [comment] 2017-02-23 22:32
The thing is, we already write down all the patches we deploy on top of the tags in the T0 release twikis. I am not sure what benefit the tag would be on top of it. It's not like we would ever use it to actually build anything...

It's not like we need to keep track of what to use for the next T0 release. That always starts from the latest WMCore tag (production or pre-releases) because the T0 wants to use the latest and greatest WMCore code without any changes (in the ideal case). Problems are fixed as they show up in testing or in replays, but these fixes go into the main WMCore and we usually (if we can afford to) wait for them to get merged before building the release.

A T0 WMCore branch would then in fact only be after the fact bookkeeping. Duplicate bookkeeping for that matter. Maybe there is some other benefit I don't see, feel free to tell me so.

**Comment by hufnagel** [comment] 2017-02-23 22:41
It potentially could make deploying replay instances easier since instead of checking out individual patches in the deployment you could just checkout the T0 branch. But that has downsides too, you can't easily see which patches are applied and for testing sometimes you might not want all the patches.

**Comment by amaltaro** [comment] 2017-02-24 12:19
John, you need at least the following 2 patches:
https://github.com/dmwm/WMCore/commit/8783799802f5cf43a5af7ec0e33fab4bb664a8b6
https://github.com/dmwm/WMCore/commit/ba7f851b4fbd2a7c800219b7b7d661954fa0f35f

which are in the `1.1.0.pre10` tag, in case you want to bump it for the next T0 release.

Once it's patched and confirmed it works, please close this issue.

**Comment by johnhcasallasl** [comment] 2017-02-24 13:53
Thanks for your prompt answer Alan. I added both patches and the replay is now running. All the workflows were created with no inconveniences and I've seen no crashes so far.  I will let it run for a while before closing the issue.

**Comment by amaltaro** [comment] 2017-03-01 12:49
John confirms it works, so closing the issue.

**Closed by amaltaro** 2017-03-01 12:49 UTC
