### ISSUE TITLE
Need to update proceedure on draining agents to make sure work is archived

### ISSUE THREAD

**Issue by jenimal** [dmwm/WMCore#7172] opened 2016-09-08 16:09 UTC
There are currently 2185 workflows in status "Announced" that have no connection to an agent, meaning the agent was redeployed before the workflow went into archived.  We have now lost the information that should have been archived on these workflows.  Before an agent is redeployed we need to make sure that all the information is in status Archived.

Jen

**Comment by ticoann** [comment] 2016-09-08 19:53
I think we also need to change how to make transition from announced to archived. (Instead of moving the status from agent it should be in reqmgr2) we already have issue for that.

**Comment by amaltaro** [comment] 2016-09-13 12:23
I don't follow this issue. There is no information that is archived, but only wiped out from the databaseS. If the workflow is already in a "WF team final status (aborted, rejected, announced)", there is nothing else that you guys would be interested in, is there?

In summary, I don't think there is any problem w.r.t. to archival of workflows and agent redeployment. As Seangchan mentioned before, the problem is with workflow archival that is not optimal and we have to fix it, but it should have 0 impact on Ops.

**Comment by jenimal** [comment] 2016-09-13 13:07
If a workflow has not moved to abort-archived, reject-archived or announced-archived when the machine is wiped, it stays in the abort, reject, announced state until somebody manually flips it.  In the case of announced archived, there may actually be information that people would want at some point.

**Comment by amaltaro** [comment] 2016-09-13 13:14
@ticoann don't we have a cherrypy thread taking care of these 'orphan' requests?

Jen, the only information people may care about is: workloadSummary that is uploaded when the workflow is moved to completed (or even before) or the logcollect tarballs, that run (or get killed) before the agent is redeployed.

**Comment by jenimal** [comment] 2016-09-13 13:28
Just trying to make sure the agents get cleaned up of old stuff.  Of course doing so manually gives me something to do during meetings ;) but it would be best to have it done automatically of course. No reason to have workflows that sitting around for literally months that we are done with.

**Comment by amaltaro** [comment] 2016-09-13 13:37
I agree! BTW, if you're manually archiving workflows, it has the same impact as redeploying agents while there are workflows still not in archived (meaning, data is not cleaned from that agent... but wait... data is gone anyways during redeployment :P)

**Comment by jenimal** [comment] 2016-09-13 13:41
SeangChan or I have been manually moving them (OK sending them through with scripts) to get them into the "archived state" in the agent so they disappear from the main monitoring pages.

**Comment by vlimant** [comment] 2016-09-15 00:57
Is there any procedure update that the agent doc @scarletnorberg should be aware of ?
Is there a fix to speed up archiving ? @ticoann please reference the issue you mentioned.
Is there an actual "performance hit" of having all these workflow announced around and not moving anywhere ? if not we (P&R) should just not care.

If we actually care, we don't want to do thing manually, and we want to pay attention during meetings ; so 
a- the archiving needs no delays 
b- redeployement cannot be done carelessly 
c- how does one detect those programmatically using available exposed information (so that we can take those forward automatically) ?

**Comment by amaltaro** [comment] 2016-09-15 06:35
There is a "procedure" that changes according to the status and output of those agent checks.
I've discussed it with Scarlet a week or two ago and I need to share with her all those details. She knows better what draining process is now and AFAIK she is going to help on that (but the final check/redeployment is still up to me).

The performance issue is on wmstats, since data is not cleaned from there until we run a database rotation in cmsweb.

>  a- the archiving needs no delays 

By default, any workflow waits for 24h before getting archived. It was a request that came from Ops.

>  b- redeployement cannot be done carelessly 

Never! It's a source for stuckness and dark issues in production if done unproperly.

>  c- how does one detect those programmatically using available exposed information (so that we can take those forward automatically) ?

Already mentioned above. Just for completeness, we could of course have a script taking care of it. However, we can do better and start with the WMCore libraries, such that we can integrate it to a component in the future.

**Comment by vlimant** [comment] 2016-09-15 10:48
@amaltaro I don't read any ways to get this detected with a script is this

>@ticoann don't we have a cherrypy thread taking care of these 'orphan' requests?

if not, please spell it out so that I can include it in Unified.

**Comment by amaltaro** [comment] 2017-05-02 09:46
![](https://github.trello.services/images/mini-trello-icon.png) [Need to update proceedure on draining agents to make sure work is archived](https://trello.com/c/q0BkDJKL/23-need-to-update-proceedure-on-draining-agents-to-make-sure-work-is-archived)

**Comment by amaltaro** [comment] 2017-11-03 13:45
With the global workqueue refactoring, most of the request transitions are triggered by central services and there should be no orphan requests anymore. I'm closing this issue. Please reopen if there was anything left.

**Closed by amaltaro** 2017-11-03 13:45 UTC
Labels: Medium Priority
