### ISSUE TITLE
Add validation to MergedLFNBase/UnmergedLFNBase arguments

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8002] opened 2017-07-13 14:41 UTC
We have these LFNs defined here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Tools/cms.py#L68

and unmerged just below it. I suggest we create a validate function in the Lexicon module and call that function from the StdSpecs validate function.

Or even better, we could have these MergedLFNBase lfns in the aux db

In addition to that:
* remove the assignment default values
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1092
* I don't know how correct are those "/store/results/" lfns, thus I'd suggest to validate it on `startswith('/store/results/')` and that's all, they are rarely used anyways and we can always enforce it to be assigned via script.

@ticoann what do you think?
BTW, slightly related to #7979

**Comment by amaltaro** [comment] 2017-07-13 14:42
BTW2: Ops does not rely on the default assignment values:
https://github.com/CMSCompOps/WmAgentScripts/issues/235

**Comment by hufnagel** [comment] 2017-07-14 20:47
The current validation breaks the Tier0.

AssertionError: '/store/backfill/1/data/Tier0_REPLAY_vocms001/HLTPhysics/RAW/v125' does not match regular expression /store/results/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\.\-_]+)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)

This prevents the latest T0 release from being used (it "worked" before since we didn't override the LFN at assignment and got the wrong/default values).

**Comment by ticoann** [comment] 2017-07-14 21:05
@amaltaro, Alan, all suggestions sounds good to me.
@hufnagel, Dirk, you are validating LFN base, right? Actually that is just last checking. For T0, the actual validation happens below.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L393

Is that the all the string? Is seems '(counter)' part is missing.

**Comment by hufnagel** [comment] 2017-07-14 21:09
The counter is not part of the base, never has been. It's injected by WMCore itself, like for any other workflow.

**Comment by hufnagel** [comment] 2017-07-14 21:11
Isn't the counter injected into the LFN in runtime stageout code ?

**Comment by hufnagel** [comment] 2017-07-14 21:13
Ah, no, these are the directories based on the run number. Let me check where they are added...

**Comment by ticoann** [comment] 2017-07-14 21:13
I think is added here. https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMTask.py#L1662

**Comment by hufnagel** [comment] 2017-07-14 21:16
Yes, which means we cannot override the LFN bases during assignment for Tier0 workflows since they are specially constructed when the workflow is created and only then.

**Comment by ticoann** [comment] 2017-07-14 21:17
I think the problem is it fails here in Tier0
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L514

We are using the same validation function when spec is created and task is created but for tier0, it needs to use different lexicon for those case (one with counter - run number) one without it.

**Comment by hufnagel** [comment] 2017-07-14 21:21
Nah, I think one version with only the counter - runnumber is fine. I just can't pass the version without the counter - runnumber to the updateArguments() method.

Basically, the LFN bases that are passed to spec creation is not the LFN base that is internally set in the spec. I need to pass that new version to updateArguments(), which means I need to retrieve the changed LFN bases after creation. This is a bit hacky but should work.

Something clean would not force me to pass parameters to updateArguments() that are not supposed to be changing...

**Comment by hufnagel** [comment] 2017-07-14 21:23
Basically, if a value for a parameter already exist in the spec after creation, why does the assignment fall back to default values instead of using that pre-exisiting value ?

**Comment by ticoann** [comment] 2017-07-14 21:30
But isn't that the code actually gives you the error?

LFN base is parameter which need to be specified in assignment in Production/Processing workflow.  But Tier0 it is set in creation

If setting is skipped here when LFNBase is not passed, would that work?
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L514

**Comment by hufnagel** [comment] 2017-07-14 21:54
Yeah, you are right. My idea doesn't work because WMWorkload.getMergedLFNBase doesn't return the counter - runnumber either. It's only set internally.

 The code you point at doesn't fail btw. It's somewhere else

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMTask.py#L1668

although the error message I get points at a different line number. Were there changes in this code recently ?

**Comment by hufnagel** [comment] 2017-07-14 22:03
File "/data/tier0/srv/wmagent/2.0.8/sw/slc6_amd64_gcc493/cms/t0/2.0.8/lib/python2.7/site-packages/T0/RunConfig/RunConfigAPI.py", line 682, in configureRunStream
    wmSpec.updateArguments(specArguments)
  File "/data/tier0/srv/wmagent/2.0.8/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch1/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 1652, in updateArguments
    self.setLFNBase(kwargs["MergedLFNBase"], kwargs["UnmergedLFNBase"])
  File "/data/tier0/srv/wmagent/2.0.8/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch1/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 891, in setLFNBase
    self.updateLFNsAndDatasets(runNumber=runNumber)
  File "/data/tier0/srv/wmagent/2.0.8/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch1/lib/python2.7/site-packages/WMCore/WMSpec/WMWorkload.py", line 610, in updateLFNsAndDatasets
    task.updateLFNsAndDatasets(runNumber=runNumber)
  File "/data/tier0/srv/wmagent/2.0.8/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch1/lib/python2.7/site-packages/WMCore/WMSpec/WMTask.py", line 1632, in updateLFNsAndDatasets
    lfnBase(mergedLFN)

**Comment by hufnagel** [comment] 2017-07-14 23:09
Ok, I finally see the real problem.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1728

does not check for a runnumber being present and pass that runnumber. You cannot call setLFNBase for Tier0 workflows and not pass the runnumber, this will lead to wrong LFN bases.

**Comment by amaltaro** [comment] 2017-07-15 06:21
I see you guys had lots of fun yesterday evening :-)
Dirk, I'll make a new PR by Monday which might superseed yours. As partly described here, I think we should: a) remove the default value from assignment and b) not update LFNBases if there is no value or it's null.

**Comment by hufnagel** [comment] 2017-07-15 14:03
Ok, I'll wait for your take on this then and wait announcing my changes til Monday at least. They do fix the problems of the wrong LFN for Tier0 replays, so I don't want to wait too long though...

**Closed** 2017-07-18 14:51 UTC
