### ISSUE TITLE
A workflow is when all the jobs failed in parent task

### ISSUE THREAD

**Issue by andresfelquintero** [dmwm/WMCore#8952] opened 2018-12-12 22:53 UTC
Hello

We have been talking with Seangchan about this problem. On vocms013, there is a workflow that has not been able to finish and it does not have paused or pending jobs. It does have the tasks in [1] as unfinished but we don't need them for anything. So Seangchan proposed that the status should be changed manually to finally clean that machine and be able to use it for other things. However all the tasks have failed, and due to that, if child task couldn't start should we should close that task and advance or what can be done?

Regards
Andres Quintero

[1]
['/Express_Run322222_StreamExpress/Express/ExpressAlcaSkimwrite_StreamExpress_ALCARECO/ExpressAlcaSkimwrite_StreamExpress_ALCARECOAlcaHarvestALCARECOStreamPromptCalibProdSiStripGains', '/Express_Run322222_StreamExpress/Express/ExpressAlcaSkimwrite_StreamExpress_ALCARECO/ExpressAlcaSkimwrite_StreamExpress_ALCARECOAlcaHarvestALCARECOStreamPromptCalibProd', '/Express_Run322222_StreamExpress/Express/ExpressAlcaSkimwrite_StreamExpress_ALCARECO/ExpressAlcaSkimwrite_StreamExpress_ALCARECOAlcaHarvestALCARECOStreamPromptCalibProdSiStripGainsAAG', '/Express_Run322222_StreamExpress/Express/ExpressAlcaSkimwrite_StreamExpress_ALCARECO/ExpressAlcaSkimwrite_StreamExpress_ALCARECOAlcaHarvestALCARECOStreamPromptCalibProdSiPixelAli', '/Express_Run322222_StreamExpress/Express/ExpressAlcaSkimwrite_StreamExpress_ALCARECO/ExpressAlcaSkimwrite_StreamExpress_ALCARECOAlcaHarvestALCARECOStreamPromptCalibProdSiPixel', '/Express_Run322222_StreamExpress/Express/ExpressAlcaSk

**Comment by ticoann** [comment] 2018-12-18 05:43
Looking at the code, it seem fileset for those tasks are  not closed due to child task is not created. (I think it is due to the all the jobs are failed for the parent tasks)
However, when I manually close the subscription for parent tasks, it didn't still move the state to Processing Done. It seems still couldn't move to further state due the tasks which doesn't have jobs in them. I will investigate more tomorrow.

**Comment by amaltaro** [comment] 2019-01-03 17:50
@andresfelquintero are those workflows still stuck?

**Comment by andresfelquintero** [comment] 2019-01-21 17:16
No, they are now completed and the machine has completed cleanup

**Comment by vytjan** [comment] 2019-01-22 15:24
Since this may be related... 
On vocms0313 (HI data WMAgent) there are still ~380 jobs not cleaned up, ~180 open subscriptions and 26 incomplete workflows.
Those workflows are from the following 3 runs:
326546, 326545 and 326100.
Few WFs:
Express_Run326100_StreamExpressCosmics
Express_Run326546_StreamHIExpress
Repack_Run326546_StreamPhysicsHIMinimumBiasReducedFormat0
@amaltaro could you please check if these stuck WFs are related to this issue? Even though there were no manually failed jobs in these newer stuck WFs.

**Comment by amaltaro** [comment] 2019-01-23 11:08
Just to keep record of some of this debugging. Besides unfinished subscriptions, this agent has 2 files in the wmbs_sub_files_acquired. Not sure how they even showed up in there, given that these files belong to a subscription with a T0-specific job splitting called `Condition`.  From the Condition src code, it simply addds that file information in a different TOAST instance and deletes if from wmbs_sub_files_available (thus it should not appear in the acquired/completed/failed tables).
And that's why I couldn't find any jobs associated to these two files. I'm going to delete their rows from the *_acquired table.

For the record, before I delete them, this is what we have in the database:
```
SQL> select wsfa.subscription, ws.fileset, wsfa.fileid, ws.workflow, ws.split_algo, ws.subtype, ws.finished
  from wmbs_sub_files_acquired wsfa
  inner join wmbs_subscription ws on ws.id = wsfa.subscription;  2    3  

SUBSCRIPTION	FILESET     FILEID   WORKFLOW SPLIT_ALGO																							 SUBTYPE   FINISHED
------------ ---------- ---------- ---------- --------------------------------------------------- ---------- ----------
       11272	  35223     184338	11272 Condition 																							       7	  0
       11272	  35223     184339	11272 Condition 																							       7	  0
```

and
```
SQL> SELECT * from WMBS_FILE_DETAILS where id in (184338,184339);

	ID LFN																													  FILESIZE     EVENTS FIRST_EVENT M
---------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------- ---------- ----------- -
    184338 /store/express/tier0_harvest/2018/Run326100@SiPixelQualityFromDbRcd_stuckTBM@2fd84749-8d54-4f9e-84cf-06a990e14509.db 														 0	    0		0 0
    184339 /store/express/tier0_harvest/2018/Run326100@SiPixelQualityFromDbRcd_stuckTBM@2fd84749-8d54-4f9e-84cf-06a990e14509.txt														 0	    0		0 0
```

**Comment by hufnagel** [comment] 2019-01-23 14:20
That's by design. The PCL condition upload uses the available, acquired, complete, failed logic, but does not actually run a job, the transition happens within the Tier0Feeder component.

**Comment by hufnagel** [comment] 2019-01-23 14:21
These files being stuck in acquired means that for some reason they are not being upload to the Dropbox.

**Comment by hufnagel** [comment] 2019-01-23 15:12
Hm, that's funny. Streamers are only supposed to be set to deleted after the Express workflow is completely done. First order, just reset the streamer deleted status to 0 and see if that triggers closeout.

**Comment by hufnagel** [comment] 2019-01-23 15:16
ALso, if these are old workflows, all this step does is to make sure that all streamer files have been reported as completely processed to P5 before we mark the workflow as injected so we can clean it up internally.

For really old workflows, that wait is kind of useless (P5 has long since cleaned up these streamers), so if the streamer deletion status reset doesn't work you can just set the workflow to injected directly.

**Comment by hufnagel** [comment] 2019-01-23 16:26
Double-checking the query, what is going on here is actually quite different.

It's stuck because some streamer files are still at deleted=0. The query only marks workflows as injected where all streamer files are deleted=1, i.e all streamer files have been processed.

I don't know why some streamers here aren't, but the other statement, that for old workflows this really doesn't matter, still stands. So you could just update all streamers for this workflow with deleted=1 and it should close out.

**Comment by vytjan** [comment] 2019-01-23 18:18
@amaltaro thanks for your help, it seems that there may be a bug in Tier0 code. 
I just referenced this issue on the newly created issue in T0 repo.

**Comment by amaltaro** [comment] 2019-01-25 09:10
@vytjan Vytas, can you please close this issue once you apply those changes to the T0 database. From our discussion, I don't think there is anything to be done within WMCore.

**Comment by vytjan** [comment] 2019-01-25 10:00
Sure, this issue is not useful anymore (but I cannot close it :) ). 
However, let's figure out what went wrong with those too early closed filesets on the T0 repo issue.

**Closed** 2019-01-25 17:14 UTC
Labels: High Priority, Tier0-systems, WMAgent
