### ISSUE TITLE
Run WMCore central services validation for HG2301

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11413] opened 2022-12-20 02:50 UTC
**Impact of the new feature**
WMCore central services

**Is your feature request related to a problem? Please describe.**
Monthly task

**Describe the solution you'd like**
Validate central services in cmsweb-testbed and provide the final feedback by the January deadline, specified by the CMSWEB team.
It also includes the creation of the service release notes and the validation check-list twiki.

Note that in this cycle we are also going to validate new docker images, based on the WMCore PyPi packages (instead of RPMs), so special attention is required on that front.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by todor-ivanov** [comment] 2023-01-09 21:27
One minor thing to notice for this release is we  are currently missing the T0 reqmon service deployed in testbed. 
https://cmsweb-testbed.cern.ch/t0_reqmon/data/info

@amaltaro  do you know if we actually deployed the service or if  this is a glitch.

**Comment by todor-ivanov** [comment] 2023-01-09 22:46
We may also consider adding a flag for skipping tape rules creation for `MSOutput` in testbed, because we are constantly hitting the same exception in the testbed logs:
```
2023-01-09 00:18:07,052:ERROR:MSOutput: MSOutputConsumer PipelineRelVal General error from pipeline. Err: <@========== WMException Start ==========@>
Exception Class: WMRucioException
Message: Provided RSE expression is considered invalid: rse_type=TAPE\(cms_type=test|rse=T1_RU_JINR_Tape). Error: Provided RSE expression is considered invalid.
Details: RSE Expression resulted in an empty set.
```

**Comment by todor-ivanov** [comment] 2023-01-09 23:08
Other than the above, I did not notice anything alarming while iterating through the central services logs in testbed. 

There is of course the usual situation with few micro services not being testable in preproduction (like `MSUnmerged`), but this is by design, and the errors I see there are not any different than the ones we usually have  for those services in testbed. So I'd say, based on my initial checks, no change of behavior was spotted in the Pypi deployed services.

**Comment by todor-ivanov** [comment] 2023-01-10 17:59
And here are the validation results and reports for the WMCore workflows. 
https://twiki.cern.ch/twiki/bin/view/CMS/WMAgentEndtoEndValidationHG2301

No issues or bugs have been spotted.

P.S. After @amaltaro has fixed the issue with the forntend now the T0 reqmon is also successfully deployed in testbed and we only need confirmation from T0 team that it looks ok. Upon that we may consider this validation as  complete.

**Comment by todor-ivanov** [comment] 2023-01-11 15:44
And we did receive the green light from T0 Team for `t0_reqmon` as well. So i am now closing this issue.

**Closed by todor-ivanov** 2023-01-11 15:44 UTC
Labels: Operations, High Priority, Testing, QPrio: High
