### ISSUE TITLE
"Failed to find a COMP python3 installation in the worker node setup." issue @NERSC

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11105] opened 2022-04-19 16:44 UTC
**Impact of the bug**
Not sure

**Describe the bug**
Thousands of prod jobs failed at NERSC w/ the following issue:
```
========== condor.455668.99.err ==========
Adding end of condor.455668.99.err to error message:

Failed to find a COMP python3 installation in the worker node setup.
  Without a known python3, there is nothing else we can do with this job. Quiting!
```
Alan and Dirk are suspicious that it might be happening due to a recent change in the agent. Thus, I'm opening this issue.

https://monit-grafana.cern.ch/d/u_qOeVqZk/wmarchive-monit?from=1650153600000&orgId=11&to=1650412799000&var-campaign=All&var-jobtype=LogCollect&var-jobtype=Merge&var-jobtype=Processing&var-jobtype=Production&var-host=All&var-jobstate=jobfailed&var-exitCodes=All&var-site=All

**How to reproduce it**
Not sure

**Expected behavior**
We shouldn't have this issue obviously. I cannot provide technical details unfortunately.

**Additional context and error message**
None

**Comment by amaltaro** [comment] 2022-04-21 03:24
I had a quick look at workflows that were failing at NERSC and I found this workflow/job in WMStats:
```
WMBS job id: 56091
Workflow: cmsunified_task_BPH-RunIISummer20UL17GEN-00127__v1_T_220224_123156_2874
Task: /cmsunified_task_BPH-RunIISummer20UL17GEN-00127__v1_T_220224_123156_2874/BPH-RunIISummer20UL17GEN-00127_0
Status: jobfailed
Site: T3_US_NERSC
Agent: cmsgwms-submit7.fnal.gov
Exit code: 99303
```

then ssh'ing to that agent and looking for that specific job id:
```
[cmsdataops@cmsgwms-submit7 current]$ vim install/wmagentpy3/JobArchiver/logDir/c/cmsunified_task_BPH-RunIISummer20UL17GEN-00127__v1_T_220224_123156_2874/JobCluster_56/Job_56091.tar.bz2
```

I see this error reported in the condor job .out file:
```
======== WMAgent CMS environment load starting at Tue Apr 19 12:10:21 GMT 2022 ========
WN missing VO_CMS_SW_DIR/OSG_APP/CVMFS environment variable, forcing it to CVMFS=/cvmfs/cms.cern.ch
WMAgent bootstrap: WMAgent thinks it found the correct CMSSW setup script
======== WMAgent CMS environment load finished at Tue Apr 19 12:10:21 GMT 2022 ========

======== WMAgent COMP Python bootstrap starting at Tue Apr 19 12:10:21 GMT 2022 ========
Job requires OS: , thus setting ScramArch to: _x86_64
======== WMAgent final job runtime checks STARTING at Tue Apr 19 12:10:21 GMT 2022 ========
Tue Apr 19 12:10:21 GMT 2022: Job Runtime in seconds:  0
Tue Apr 19 12:10:21 GMT 2022: Job bootstrap script exited:  252
```

which makes me think that the `REQUIRED_OS was not set, as per the output message starting with "Job requires OS:".
However, looking at the condor dump at the very same log file, I see REQUIRED_OS has been properly set to `rhel7`:
```
  REQUIRED_OS = "rhel7"
```

With that, it looks to me that this environment variable is not available in the job environment, but only through the usual `_CONDOR_JOB_AD` environment variable. Still to be confirmed though.
On what concerns why we only see such errors in the new WMAgent release, it could because in the previous version we were default'ing things to slc6_*, while now it relies completely on REQUIRED_OS env var. Just in case, here is the PR adding these recent changes to the job wrapper:
https://github.com/dmwm/WMCore/commit/765a7203517430dc8b118b9b4980e54de5fbcc80

@hufnagel is there anything missing on the NERSC job setup that would cause this environment variable not to be accessed? This is something peculiar to NERSC, because it's working pretty well in all the other sites.

PS.: I haven't marked this issue as a BUG yet because it could be a site-related issue.

**Comment by hufnagel** [comment] 2022-04-21 23:05
Yeah, it's very possible this problem is due to how NERSC is integrated into HEPCloud, that we are not passing along REQUIRED_OS at some point. We'll investigate from our end (likely only next week since Steve Timm is taking a few days vacation).

**Comment by hufnagel** [comment] 2022-04-21 23:09
What would help in tracking this down is some suggestions in how REQUIRED_OS is supposed to make it from a HTCondor class ad into the job environment, ie. what piece of code takes care of that.

**Comment by amaltaro** [comment] 2022-04-22 02:22
@hufnagel can you please involve the SI team on this discussion? Even though this variable is set on the WMAgent side, I think it's glideinWMS that is responsible for pushing them to the job wrapper scope.

**Comment by hufnagel** [comment] 2022-04-23 20:42
Problem is understood (we think). REQUIRED_OS is put into the job environment by the singularity wrapper (both the new direct GlideinWMS support and the old-style CMS way), that's why it works everywhere but NERSC. At NERSC we don't use singularity, we use shifter.

We have OS specific factory entries for NERSC and as a workaround will just override the job environment from the factory entry.

**Comment by amaltaro** [comment] 2022-04-25 18:09
We could have use of a label like "Not an issue", but for now I am marking it with the "wont-do" one.
@hufnagel since the issue has been identified and it's not on the WMCore side, shall we close this issue out?

**Comment by hufnagel** [comment] 2022-04-25 19:05
Yes, you can close this.

**Comment by amaltaro** [comment] 2022-04-25 20:04
Perfect! Thanks to you and Hasan for following this up! Closing.

**Closed by amaltaro** 2022-04-25 20:04 UTC
Labels: WMAgent, High Priority, Further Discussion, wont-do
