### ISSUE TITLE
reqmgr2 api gives internal server error for relval workflows

### ISSUE THREAD

**Issue by sharad1126** [dmwm/WMCore#9419] opened 2019-11-12 18:25 UTC
**Impact of the bug**
Batchor module is affected in unified which causes the relvals to stop working. 

**Describe the bug**
http://cmsweb.cern.ch/reqmgr2/data/request?status=assignment-approved&request_type=TaskChain&requestor=kaura&detail=true is giving 501 internal server error

**How to reproduce it**
http://cmsweb.cern.ch/reqmgr2/data/request?status=assignment-approved&request_type=TaskChain&requestor=kaura&detail=true

**Expected behavior**
should return a proper json

**Additional context and error message**

**Comment by amaltaro** [comment] 2019-11-12 20:53
@sharad1126 can you please point me to the code making such request?
It seems that if you set `detail=False` it works just fine. It might be related to the huge amount of requests in the system.

**Comment by sharad1126** [comment] 2019-11-12 21:38
Hi @amaltaro it's here - https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L6205 which is called by https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/batchor.py#L17

**Comment by sharad1126** [comment] 2019-11-12 21:41
Also, it cannot be a huge amount of workflows as we look for workflows by a user that are in assignment approved only, so it's supposed to return an empty JSON (if that user submitted no workflows) or JSON with 10-15 workflows max. the query is probably taking too long a time to search in the whole db.

**Comment by sharad1126** [comment] 2019-11-12 21:45
eg. 
```
https://cmsweb.cern.ch/reqmgr2/data/request?status=assignment-approved&request_type=TaskChain&requestor=kaura&detail=False
```
gives an empty json 
```
{
result: [ ]
}
```

and so should it give with True. No?

**Comment by amaltaro** [comment] 2019-11-13 07:15
The problem is how it's implemented somehow. Such query is actually creating 2 internal queries to CouchDB, one asking for status and request type view:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L312

which loads TONS of data at the moment; then it does a second call with:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L316

which shouldn't load anything. Afterwards, this information is merged and intersected to yield the results to the client.

Actually, here is a problem in WMCore. Such call creates a 3rd call:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L323

which loads even more data (especially with details=True). This needs to be **fixed!**

In addition to that, we need to fix the client as well (Unified), which is not using the service properly. From the logs, It looks like Unified runs the same query every 5min for EVERY single requestor. That can be fixed by a single call where you provide all the users as argument (and you probably want to maintain/cleanup that list of reval users...), e.g.:
http://cmsweb.cern.ch/reqmgr2/data/request?status=assignment-approved&requestor=kaura&requestor=fabozzi&requestor=prebello&detail=true

**Comment by sharad1126** [comment] 2019-11-13 09:53
Thanks for the explanation Alan from wmcore side. 

Yes, you are right that Unified makes queries for all the requestors of relvals through this api call one by one. why it does one by one and not all at once is something I am not sure. I think it could be because every user's requests goes in one batch maybe or every use submit's requests that belong to different campaigns, I am not sure about it. 

we can discuss this more and see what changes should be done in unified for this. 

Although, it's so weird that no one ever saw how this is running since so long being never discussed, but what I can see is this issue appeared from our side last week only.

**Comment by amaltaro** [comment] 2019-11-13 10:25
Nope, Unified is actually putting all the requests (for whatever user(s)) into the same basket. I made a temporary fix for Unified, until we get the proper API in WMCore to support this use case in an efficient way.

**Comment by sharad1126** [comment] 2019-11-13 10:28
thanks @amaltaro .

**Closed** 2019-11-15 08:38 UTC
Labels: BUG, High Priority, ReqMgr2
