### ISSUE TITLE
stage out log files to eos

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#5719] opened 2015-03-26 15:54 UTC
Hi,

We have set up a special phedex instance to transfer log files from castor to eos. Right now we are using a cronjob to inject the log files into phedex. This cronjob is crashing a lot and @merictaze recommends that wmagent should directly inject the log files into the phedex instance.

Andrew

**Comment by ticoann** [comment] 2015-05-21 14:35
Could you point me the cronjob script code?

**Comment by merictaze** [comment] 2015-05-21 14:52
Hi,

Just a clarification, it's not crashing a lot, it was crushing in the first implementation when castor file listing returned a lot of file. It got fixed 3 months ago and working without any problem since then.

However, instead of listing files on castor everyday with a cronjob, it would be better if WMAgent injects the log files into PhEDEx Ops instance once they're created. 

The script can be found at:
https://github.com/CMSCompOps/TransferTeam/blob/master/log_transfer/LogTransfer.py

Cheers,
Meric

**Comment by AndrewLevin** [comment] 2015-05-22 11:53
Hi Seangchan,

We would like WMAgent to do three things:

1) Inject all of the log files into the phedex instance
2) When the workflow is finished, create a replica subscription to transfer its log files from T0_CH_CERN_MSS to T2_CH_CERN
3) Approve this subscription

Andrew

**Comment by merictaze** [comment] 2015-05-22 12:17
Hi,

Current procedure in the script is the following:
<pre>
1) Get log files under '/castor/cern.ch/cms/store/logs/prod/[YEAR]/[MONTH]/WMAgent'
2) Filter out the files already injected to PhEDEx
3) Create injection xml
dataset: /Log[YEAR]/[MONTH]/[WFNAME]
block: /Log[YEAR]/[MONTH]/[WFNAME]#01
LFN: /store/logs/prod/[YEAR]/[MONTH]/WMAgent/[LOGFILE]
4) Inject to T0_CH_CERN_Export
5) Create subscription&approve at T2_CH_CERN
</pre>

Injection and subscription should happen at the same time as a WF can run even 1 month. so no need to wait WF to finish.

Another approach might be:
<pre>
1) Create&approve a subscription for [1] at T2_CH_CERN in the beginning of WF submission
2) Inject new log files into [1] whenever they're produced
3) PhEDEx will transfer them from T0 to T2 automatically.
</pre>

Regards,
Meric

[1] /Log[YEAR]/[MONTH]/[WFNAME]

**Comment by amaltaro** [comment] 2015-06-08 15:30
Meric just told me the phedex log instance is running in virtual dev machines, not in cmsweb.
I would not advice any WMCore development against external services running in other's private VM, that means it will most likely not be done for July.

**Comment by AndrewLevin** [comment] 2015-06-08 15:44
OK, can you put it in cmsweb @merictaze?

**Comment by merictaze** [comment] 2015-06-10 10:55
I asked to migrate it to cmsweb in the next deployment.

https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/1999/1/1/1/1/1.html

**Comment by ticoann** [comment] 2015-06-18 14:07
What kind of log files are under /castor/cern.ch/cms/store/logs/prod/[YEAR]/[MONTH]/WMAgent?
Is are those log archive files? or something else?

**Comment by amaltaro** [comment] 2015-06-18 14:08
The logCollect tarballs, like this one
/castor/cern.ch/cms/store/logs/prod/2015/06/WMAgent/amaltaro_ReDigi_cmsRun2_LumiMask_Agent107_Validation_v2_lazy_150616_141051_4986/amaltaro_ReDigi_cmsRun2_LumiMask_Agent107_Validation_v2_lazy_150616_141051_4986-LogCollect-server-d429648e-a427-4338-9300-659b69d7eaaf-1-logs.tar

**Comment by ticoann** [comment] 2015-06-18 14:11
Isn't that only in the tape for the reason? (i.e because of it size, if it is stored T2_CH_CERN isn't it using too much disk space to store that?)

**Comment by amaltaro** [comment] 2015-06-18 14:13
We use tape in order to archive those logs "forever". The idea of writing it also to T2_CH_CERN is more for the ~new workflows (last 6 months or so). Later on someone will need to do some clean up, but I guess we don't need to worry about it right now.

**Comment by merictaze** [comment] 2015-06-18 14:18
Currently anything at this path older than 2 months are being deleted by EOS cleanup script.

**Comment by AndrewLevin** [comment] 2015-06-25 14:50
Hi,

@nikmagini told me it is possible to copy files from outside of CERN to eos, using lcgcp for example. I think the best solution is that we write the log files directly to eos instead of castor (or we write them to both castor and eos).

Andrew

**Comment by ticoann** [comment] 2015-07-01 19:55
It seems following code (eventually) triggers log archived file to go castor.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py#L71

I am not sure whether we can stage out to both. If we stageout to eos we have to move to castor somehow.

@hufnagel, Dirk, could you give me some advise?

**Comment by hufnagel** [comment] 2015-07-02 09:50
Hm, the LogCollect Executor code is basically a customized Stageout Executor. You can see it in the comment in line 5 that it started out as a simple copy. All they do here is hardcode using the overrides and hardcode the default override settings. Its done in a bit convoluted way, but I guess they wanted to keep the ability to use a real override for staging out logcollect too.

We could just modify it further to do two stageouts with two different overrides, but then the question becomes: What to do if there is a real override, do we copy twice to the same location ? Do we make the code more complex to catch that case ? I assume here we want to keep the override functionality to be able to do self-contained tests.

**Comment by ticoann** [comment] 2015-07-02 16:28
Thanks for the comments Dirk.
Assuming we can/want two stage out. There are a couple of things need to be hacked to make this work.
1. output file locations need to be set on eos location which would be T2_CH_CERN (assuming PNN transition is done) instead of castor.
2. The log archive files need to be recorded in DBSBuffer with meaning pull dataset name and block name (it doesn't mean it will be uploaded to DBS. (Maybe we can control that with block status).
3. PhEDEx Injection is made on those block. 

Or we can make to stage out to eos and create replica subscription to castor. (I am not even sure that is possible). And do 2. 3. above.

@amaltaro, @hufnagel, It seems hacky way to do this. Do you have any other suggestions?

**Comment by hufnagel** [comment] 2015-07-02 16:39
As far as I remember, these will go into a separate DBS and PhEDEx instance, correct ? Which is not really supported by DBSBuffer...

**Comment by hufnagel** [comment] 2015-07-02 16:40
And if I wanted to do this in a clean way, I would make logArchive output files from a job look exactly like any other ouput files from a job (with the possible caveat to override the stageout to T2_CH_CERN). If they are treated like anything else, you can setup the usual subscriptions etc.

**Comment by AndrewLevin** [comment] 2015-07-02 16:51
Hi Seangchan,

If we can stage out the log files to both castor and eos, I think we probably won't use a phedex instance for log files. We can then just delete old log files from eos with a cron job. Do you agree @merictaze?

Andrew

**Comment by ticoann** [comment] 2015-07-02 16:55
Hi Andrew, so Is PhEDEx not used for search, just for the transferring files?
In that case current naming conversion for lfn, is sufficient for getting the file you want efficiently?

**Comment by AndrewLevin** [comment] 2015-07-02 16:59
Hi Seangchan,

Yes, the log file phedex instance is just used right now for transferring and deleting the files. Having lfns for log files is not necessary.

Andrew

**Comment by hufnagel** [comment] 2015-07-02 17:02
If all you want is to have have copies on eos and castor instead of just castor, having WMAgent make the copies is indeed the easiest way to handle that. That's runtime code only changes in WMAgent.

Retrofitting WMAgent to be able to get logArch information up from the runtime to the PhEDExInjector and then be able to inject files into a different instance would be a major pain.

In an ideal world it would be nice to have it, as it would be the cleanest way to deal with these files. But I would put that as "VeryLowPriority, maybe in a year or two if we have nothing better to do" and solve this differently now.

**Comment by amaltaro** [comment] 2015-07-02 17:55
I second the idea of double stage out and that is IT. Or stage out to EOS and then copy it to castor.

However, in the past when this issue was discussed, it seems everyone was in favor of using a PhEDEx instance for this purpose (and letting the FTS server/system) handle any transfers. Of course, for that it was discussed we would inject logs into PhEDEx in a similar way as we do for real data/datasets (which IMO was too much, but ....).

If people don't push us to use PhEDEx, than staging out to EOS and copying it to castor is the way to go here.

**Comment by hufnagel** [comment] 2015-07-02 18:03
If you do treat logArchives like any other data, you can even just use the normal stageout rules, define a dataset and then have move/copy subscriptions to T0_CH_CERN_MSS and T2_CH_CERN. Advantage is that you don't hack around, you just treat it as any other data produced by the jobs. Which in the long run should help quite a bit as it simplifies the system.

The problem is that this is a lot of work, especially as this data wouldn't go into the normal PhEDEx instances, which means we need to add support for some data going to one PhEDEx instance and some to another. Which means potentially major changes to the PhEDExInjector and DBSBuffer.

The only solutions feasible NOW (ie. at least 6 months timescale) are double stageout from WMAgent or a single stageout with a later copy (not from WMAgent, but cronjob or whatever).

So coming back to the original issue reported, is the cronjob not feasible. Some later comments seemed to suggest it works again ? Would we gain anything from double stageout compared to the cron job we have now ?

**Comment by AndrewLevin** [comment] 2015-07-02 18:39
Hi Dirk,

See the new title of the issue. I think we should try to have the double stage out from wmagent, plus a cronjob to delete from eos. We should forget about putting log files into phedex. That is totally overkill.

Andrew

**Comment by ticoann** [comment] 2015-07-04 02:46
Thanks Dirk, Andrew for all the inputs. So we will just add the code to double stage out LogCollect files.

**Comment by ticoann** [comment] 2015-07-10 15:04
@hufnagel, Assigning to Dirk, since he is much more expert than me and kindly agreed to handle this ticket. (I am not sure how this will fit generic plug in he is planning to do - maybe not very well). 
Thanks Dirk. :smile:

**Comment by ticoann** [comment] 2015-08-20 16:09
@nikmagini, @merictaze, Hi Nicolo, Meric, which command should we use for transferring data from outside CERN and CERN to eos area.
Jorge tested srm, eos but it doesn't seems to work. But glite-transfer-submit worked.
Could you give me some examples which command to use?
It will be staging out directly from worker node from log archive jobs agent creates, is there special permission needed?

Thanks

**Comment by nikmagini** [comment] 2015-08-25 15:42
Hi,

1) You can use xrdcp to copy the files to EOS:

> xrdcp $localfile root://eoscms.cern.ch//eos/cms/store/logs/$etc

(SRM should also work with this SURL, but it will be phased out eventually:
srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs

Question for you: do you hardcode the SURL or should we add a proper rule in the TFC for WMAgent

2) In any case, you need proper authorization to write files directly to EOS. I suppose that we will need to map the DN of the production pilots to a user with write permission on /eos/cms/store/logs

Cheers
N.

**Comment by nikmagini** [comment] 2015-08-25 15:42
Hi,

1) You can use xrdcp to copy the files to EOS:

> xrdcp $localfile root://eoscms.cern.ch//eos/cms/store/logs/$etc

(SRM should also work with this SURL, but it will be phased out eventually:
srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs

Question for you: do you hardcode the SURL or should we add a proper rule in the TFC for WMAgent

2) In any case, you need proper authorization to write files directly to EOS. I suppose that we will need to map the DN of the production pilots to a user with write permission on /eos/cms/store/logs

Cheers
N.

**Comment by nikmagini** [comment] 2015-08-25 15:42
Hi,

1) You can use xrdcp to copy the files to EOS:

> xrdcp $localfile root://eoscms.cern.ch//eos/cms/store/logs/$etc

(SRM should also work with this SURL, but it will be phased out eventually:
srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs

Question for you: do you hardcode the SURL or should we add a proper rule in the TFC for WMAgent

2) In any case, you need proper authorization to write files directly to EOS. I suppose that we will need to map the DN of the production pilots to a user with write permission on /eos/cms/store/logs

Cheers
N.

**Comment by hufnagel** [comment] 2015-08-25 15:48
The reason I suggest EOS is that inside the LogCollect executor we already use SRM stageout to write to castor, so duplicating this and changing the URL to write to EOS is trivial, while changing the stageout method to xrdcp is not trivial.

Its not as simple as calling the command, because this code actually re-used the WMCore stageout code, with the rety features that gives you. We want to keep this.

**Comment by amaltaro** [comment] 2015-08-25 15:54
Dirk, what you say would be easier to code is to copy the same tarball twice from siteX to CERN, right?

IMO, the proper way of fixing it would be:
 1. copy the tarball from siteX to castor
 2. if the copy succeeded, then right away ...
 3. copy the tarball from castor (it should be in buffer anyways) to EOS - in the *best effort* mode.

Thus, the logCollect only fails if it fails to copy the tarball to castor.
And we make a local copy to EOS.
Would it be a major change?

**Comment by hufnagel** [comment] 2015-08-25 16:08
I wouldn't do that because then again you have to code the castor to eos copy manually. Plus how are you supposed to do an efficient castor->EOS copy from a job that runs on a node at a site somewhere else ? Third-part xrdcp is tricky enough within CERN, I wouldn't want to call that from somewhere else.

Duplicate the SRM stageout code lines, change the URL and be done with it.

**Comment by ticoann** [comment] 2015-08-25 16:13
Thanks all. 
Dirk, I think Alan was the same thing as you, copy to castor and copy to eos (not copy from castor)
The change wouldn't be a major change. And Dirk suggested we should go with srm for now. 
Dirk has plan to do the refactoring (more of rewriting StageOut anyway) This will be temporary.
The one problem was last time Jorge tested srm command didn't work. We will retest it.
How does the permission granted, the copy is from worker node, right? How is the copy to castor is granted now? Shoudn't be the same way to grant the permission to eos.

> Question for you: do you hardcode the SURL or should we add a proper rule in the TFC for WMAgent

I think it is better to have proper rule in TFC for WMAgent if it is not a big trouble.

**Comment by amaltaro** [comment] 2015-08-25 17:35
Nope, I really meant from castor to eos. That's why I said the proper way, at least from the network point of view. Anyways, provided we run 300k jobs per day, that would result in average in 600 logCollect jobs (let's say 1000), so it's not a big deal in the end.

What's a SURL? Does it mean we would need to map/set this url in the TFC of ALL sites? If that's the case, then I'm in favor of defining it directly in the WMCore code.

**Comment by ticoann** [comment] 2015-08-25 17:55
Sorry Alan, I misunderstood you again. :smile: Is there advantage is doing that (copy back from castor) instead of directly stageout from site?

**Comment by amaltaro** [comment] 2015-08-25 18:21
The advantages would be that:
 1. we don't need to transfer files (between 1MB - 400MB size) twice over WAN, castor to eos would be local
 2. less prone to network failures

However, since the logCollect load is not that high, we can just go for the easier fix as Dirk suggested.
Especially if Dirk knows how to do this change :-P

**Comment by ticoann** [comment] 2015-08-27 14:42
> What's a SURL? Does it mean we would need to map/set this url in the TFC of ALL sites? If that's the case, then I'm in favor of defining it directly in the WMCore code.

I think SURL is just this (I think is acronym for Site URL) srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/logs.
I don't know how to change TFC rules, is it under each sites admin's hand or can be changed centrally. If it is first case, may we should hard code it as Alan said.

**Comment by hufnagel** [comment] 2015-08-27 14:47
TFC does not need to be changed. We write the logcollect files to standard namespace on EOS. In any case, the settings are hard-coded now

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py#L65

we just need to add another set of rules for EOS. Basically just change seName, lfnPrefix and lfnBase, create a second StageOutMgr instance with these settings and then make a second call here

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py#L196

**Comment by nikmagini** [comment] 2015-08-31 17:01
Hi all,

in any case, I think I'll ask Meric to add a proper SRM rule for /store/logs in the T2_CH_CERN TFC - even if you hardcode it, it's better to have it there for consistency.

And again a reminder: eventually SRM in front of EOS is going to disappear. At some point you'll have to change the stageout method anyway (either to xrdcp or gfal-copy)

Cheers
N.

**Comment by merictaze** [comment] 2015-09-01 12:53
Hi Nicolo,

The rule you asked has been added to T2_CH_CERN TFC:
https://git.cern.ch/web/siteconf.git/blob/HEAD:/T1_CH_CERN/PhEDEx/EOS.storage.xml#l80

Regards,
Meric

**Closed** 2015-10-01 20:32 UTC
Labels: High Priority
